### ISSUE TITLE
Generate S3 file URL in QuerySet or using {% url %}

### ISSUE THREAD

**Issue by rez0n** [jschneier/django-storages#1013]
Hi, I have a page with multiple entries displayed along with its related file.

```
{% for row in context %}
{{row.name}} - {{ row.related.data_file.url }}
{% endfor %}
```

This generated thousands of similar queries and increasing page load time significantly.
I'd prefer to annotate `data_file` name or its database id and build URL using {% URL 'dinwload_file' row.annotated_file_id %}

Anybody have any suggestions on how to deal with it?

**Comment by nl-emmanuellodovice** [comment]
I think this issue is not specific to `django-storages` and more on your database  models. Maybe give more info about the models. If `related` is just a `ForeignKey` of `row` then maybe adding `select_related('related')` would do the trick to reduce the number of queries.

**Comment by hemebond** [comment]
@rez0n are you talking about SQL or HTTP queries?

If it's HTTP queries, accessing the `url` attribute of an `ImageFile` causes django-storages to make an HTTP query in order to resolve it to an S3 endpoint. On large querysets this is definitely a problem.

**Comment by rez0n** [comment]
Hi @hemebond 
I was talk about the SQL queries, to be clear I have no success finding (remember) issue that I faced, now I have it works great. Most probably I solved this using select_related and in one place where the file was fetched from set of files by the model method, I used cache.

**Comment by hemebond** [comment]
@rez0n Okay, then I think this issue can be closed then. Unless you use select_related Django will do an SQL query for each item referenced in a template; that doesn't seem to be an issue with django-storages.
