### ISSUE TITLE
S3 storage backend's `size` method raise `botocore.exceptions.ClientError` instead of FileNotFoundError

### ISSUE THREAD

**Issue by nl-emmanuellodovice** [jschneier/django-storages#1022]
When you call `default_storage.size(path_that_does_not_exists)` with `S3Boto3Storage` as the default storage backend, it will raise `botocore.exceptions.ClientError` instead of `FileNotFoundError`.

**Comment by jschneier** [comment]
Let's say I wrap this but now some other client error is encountered, what should happen?

**Comment by nl-emmanuellodovice** [comment]
Thanks for checking this. I am not a boto expert but I was thinking may be we can check the response for the exception and see if the code is 404 and only then raise the `FileNotFoundError`.

Something like
```
try:
    size = default_storage.size("does_not_exists.file")
except ClientError as e:
    if e.response.get("Error", {}).get("Code", None) == '404':
        raise FileNotFoundError("does_not_exists.file does not exist.")
    else:
        raise
```
