### ISSUE TITLE
ImportError: cannot import name 'generate_blob_sas' from 'azure.storage.blob'

### ISSUE THREAD

**Issue by susajsnair** [jschneier/django-storages#1025]
azure-common==1.1.27
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
Django==3.2.3
django-storages==1.11.1

And **python 3.8**

**Comment by jschneier** [comment]
That has never been in the repository as far as I can tell. Regardless I am going to merge the new Azure backend so this issue is stale.
