### ISSUE TITLE
Multiple Buckets / Multiple Environments

### ISSUE THREAD

**Issue by steverecio** [jschneier/django-storages#1028]
After looking around quite extensively, I see lots of people with the same issue. They need both public media and private media storage which changes in dev and production (ie FileSystemStorage on dev and a public bucket and a private bucket on production).

Has anyone found a clean way to achieve this? If you pass in `storage=S3Boto3Storage(bucket='myprivatebucket')`, this can't easily be switched between environments. If you leave `storage` blank, then default storage gets added into the data migration and you end up using DefaultStorage on production. Is there a clean way to solve for this? Maybe a custom storage class that inherits from a different base class depending on environment?

**Comment by sww314** [comment]
In recent versions of Django, storage can be a callable vs just a class. 

We pass in:
`storage=get_storages`
where `get_storages` is a callable that returns the storage you need. In there you can handle the differences by looking at settings or whatever you need. 

Unfortunately, the callable is not passed the field or model that it is called from so you have to work around that.

**Comment by steverecio** [comment]
@sww314 Thanks for the quick response. Do you have a code sample that we can reference here?
