### ISSUE TITLE
New pypi release?

### ISSUE THREAD

**Issue by halfnibble** [jschneier/django-storages#103]
There are fixes in master that fix critical bugs for Google Cloud Storage. Any chance for a new pypi release?

**Comment by pnovotnak** [comment]
Bump

**Comment by pnovotnak** [comment]
We're waiting for this at my company. If you don't have time do push uploads you could add someone (or a couple someones) as a maintainer

**Comment by halfnibble** [comment]
I'm thinking about forking this and making a new library specifically for Google Cloud Storage. There are a few things that Google does differently than the others. Thoughts on making a GCS specific library?

**Comment by jschneier** [comment]
Just released to pypi. Sorry about my lack of responsiveness.

@halfnibble personally I don't think it makes a _ton_ of sense to have all of these different storage backends in 1 library at all. I personally don't use them all (how could you?) but am happy to accept fixes on them as they come up. I think the google cloud one is one in particular that could be rethought. I wasn't (and still am not) thrilled with the quality of the codebase but hey, it's what I have inherited.
