### ISSUE TITLE
Query String Auth not being added on all static files in Django with Amazon S3

### ISSUE THREAD

**Issue by nitishsainani** [jschneier/django-storages#1031]
To be specific the base.css is being served and fonts.css is not being served(Err 403). This is happening in Django Admin Console. I have confirmed that the fonts.css is in the bucket

The problem being these files don't have query string auth
```
# This is working
GET https://bucket-name.s3.amazonaws.com/static/admin/css/base.css?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AFD34GE4VTLUKQOTHAW7%2F20210726%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20210726T193438Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=815bd068805f60f90c6acf27b24028424e85afbf7ba2939b51471cab2ba8e8b9

# This isn't working
GET https://bucket-name.s3.amazonaws.com/static/admin/css/fonts.css
```

Almost all static files are being served

The fonts.css is not in the HTML page source and maybe is being called from a JS code that is not appending the Query String Auth
Also when I shift from S3 to django default storage, it works perfectly fine.

**Comment by voyc-jean** [comment]
This is happening for me with both `fonts.css` and `widgest.css`.

I believe the cause is that the Django admin CSS makes used of `@import url('widgets.css');` and `@import url('fonts.css');`- see [Django admin CSS](https://github.com/django/django/blob/0b31e024873681e187b574fe1c4afe5e48aeeecf/django/contrib/admin/static/admin/css/forms.css#L1).

Since this import is executed by the browser, there's no way for querystring auth to be added.

**Comment by matthiaslesage** [comment]
Hi, same for me also, on `admin/css/fonts.css`, `admin/img/icon-addlink.svg` and `admin/img/icon-changelink.svg`.

Would you know how to ask the Django team to correct this ?

**Comment by nimish-1** [comment]
@jschneier this is also happening in Google cloud storage(GCS). Can we please look into it ASAP?
<img width="880" alt="image" src="https://user-images.githubusercontent.com/86397926/182578052-c75142b7-c06d-4041-85fb-e18034a70ee6.png">

**Comment by DeD1rk** [comment]
For S3, you could look into setting up CloudFront to serve the static files without requiring authentication

**Comment by leikoilja** [comment]
still an issue for the admin page if hosting static files on s3 bucket using django-storages

**Comment by oesah** [comment]
We have the same issue, any fix without CloudFront?

**Comment by DeD1rk** [comment]
@oesah

A solution without cloudfront could be to make a separate, _public read_ S3 bucket for your staticfiles, which you do not use for any private files.
Or possibly, you can configure your `django-storages` staticfiles S3 storage object to write all its objects with a 'public read' ACL (so make all static files publicly accessible individually even if the bucket is not pubic by default).

**Comment by voyc-jean** [comment]
> We have the same issue, any fix without CloudFront?

In our case we opted to switch to [whitenoise](https://github.com/evansd/whitenoise) to serve static content instead.

Of course, this may not be possible for you depending on your use case. For the problem to be resolved, the Django team would need to change how their CSS is structured.

**Comment by jschneier** [comment]
Please open a bug with upstream Django around this.

**Comment by DeD1rk** [comment]
Anyway I don't think this is even an issue at all. It just doesn't make sense to require querystring auth for static files as querystring auth typically has a timeout, which would make the urls not-actually-static and makes caching impossible. So the suggested alternatives such as cloudfront or just a public bucket are really the right way to go
