### ISSUE TITLE
Boto3 and Infrequent Access Storage Class

### ISSUE THREAD

**Issue by m1schka** [jschneier/django-storages#104]
Hey there.
Just want to ask a quick question. Do you plan to implement a new S3 Backend based on boto3? This would be super nice, because also comes with the option to upload a key with the new infrequent access storage option, which has not been (and probably will not be) backported to boto2 [reference](https://github.com/boto/boto/issues/3359)

**Comment by mbarrien** [comment]
See https://github.com/jschneier/django-storages/pull/66

**Comment by jschneier** [comment]
Hi, the Boto3 backend has now been merged and released, if this feature isn't available in it please feel free to open a PR.
