### ISSUE TITLE
GCS: Intermittent 403 on upload

### ISSUE THREAD

**Issue by robwatkiss** [jschneier/django-storages#1043]
Hi there,

We're facing an intermittent yet persistent 403 error returning when uploading to GCS with the below message. This occurs on ~25% of requests and I'm yet to identify a pattern of what's causing it. The service account definitely has the correct permissions as we can successfully upload the rest of the time. We're using unique filenames so clashes aren't possible and even so the service account has permissions to overwrite.

Has anyone faced this before? Can anyone point me in the right direction for a fix or suggest steps to debug?

`403 POST https://www.googleapis.com/upload/storage/v1/b/bucket-name/o?uploadType=multipart: ('Request failed with status code', 403, 'Expected one of', <HTTPStatus.OK: 200>)`

Cheers,
Rob

**Comment by jschneier** [comment]
Sorry doesn’t seem like an issue with this library
