### ISSUE TITLE
Azure Files Don't Get Deleted

### ISSUE THREAD

**Issue by creyD** [jschneier/django-storages#1044]
Using the Azure Storage connector with the default `storages.backends.azure_storage.AzureStorage` the file upload and handling works, but the problem is that they don't get deleted when the object get's deleted.

**Comment by sww314** [comment]
You need to make your `model.delete()` call delete explicitly. 

I use something like this (in this case the Model actually has 3 files). 

```
    def _delete_files(self):
        """ delete any externally stored files """
        self._delete_file(self.file)
        self._delete_file(self.thumbnail)
        self._delete_file(self.preview)

    def _delete_file(self, file_field):
        try:
            self.file.storage.delete(file_field.name)
        except exceptions.NotFound:
            # Blob might get deleted from GCS
            pass
        except (TypeError, ValueError):
            # field_field can be None or Blob name is empty
            pass

    def delete(self, *args, **kwargs):
        self._delete_files()
        super(MediaMixin, self).delete(*args, **kwargs)
```

**Comment by creyD** [comment]
Ok thanks. I thought this might be a function which should be included.

**Comment by provinzkraut** [comment]
@sww314 I came across this issue while investigating files not being deleted. Can you maybe expand on your explanation as to *why* this functionality is not included by default?

This behaviour is quite unexpected and not documented somewhere, so it would be good to know why it is like this.
