### ISSUE TITLE
Django 3.2 support

### ISSUE THREAD

**Issue by mariajgrimaldi** [jschneier/django-storages#1046]
Hello! I hope you're doing well @jschneier @jdufresne!

I'm reaching out as part of the Open edX effort to update the [platform](https://github.com/edx/edx-platform/) to Django 3.2, `django-storages` is one of its dependencies to be updated. [Here](https://github.com/edx/upgrades/issues/44) is the issue!

After some research, I found two essential issues that can help with the Django 3.2 support:

- Fix all CI: https://github.com/jschneier/django-storages/pull/1042
- Fix CI and add Django 3.2 support: https://github.com/jschneier/django-storages/pull/1005

What can we do to help moving forward?

**Comment by mariajgrimaldi** [comment]
Update: I cherry-picked the commits and triggered testing via travis CI: https://github.com/mariajgrimaldi/django-storages/runs/3509577400

All tests passed.

**Comment by mariajgrimaldi** [comment]
Update: what we need to close this issue is to make a new release. Can you help us with that? @jschneier 

Thank you so much!

**Comment by jschneier** [comment]
I need to look through and see what is low risk to merge, take those, and then release.

**Comment by jschneier** [comment]
I need to look through and see what is low risk to merge, take those, and then release.

**Comment by mariajgrimaldi** [comment]
Hi there! Let me know when you create a new release :)

Many thanks for considering my request.
