### ISSUE TITLE
Google backend failing to build on alpine docker image

### ISSUE THREAD

**Issue by RobertRR** [jschneier/django-storages#1048]
Attempting to install this via pip on alpine in docker results in a build failure.

Docker = v20.10.8
Alpine = alpine:3.14 (sha256:e841d0f0881ea22080e84088337646ada15871abbc3ce19b3219e8fc2cb0cc22)
pip = 21.2.4
Python = 3.9.5

Error as below.

```
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python3.9 -c src/google_crc32c/_crc32c.c -o build/temp.linux-x86_64-3.9/src/google_crc32c/_crc32c.o
  src/google_crc32c/_crc32c.c:3:10: fatal error: crc32c/crc32c.h: No such file or directory
      3 | #include <crc32c/crc32c.h>
        |          ^~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for google-crc32c
Failed to build google-crc32c
ERROR: Could not build wheels for google-crc32c which use PEP 517 and cannot be installed directly
```

Is there something that can be done to work around using google-crc32c? or is this dependent on a fix from that project.

[django-storages.txt](https://github.com/jschneier/django-storages/files/7095590/django-storages.txt)

**Comment by jschneier** [comment]
This is an upstream problem. You can see the various workarounds [here](https://github.com/googleapis/python-crc32c/issues/83).
