### ISSUE TITLE
Can You Help Me Code snippet of using gcp api on firebase storage

### ISSUE THREAD

**Issue by TheSwordBreaker** [jschneier/django-storages#1052]
I want to used firebase storage and I know gcp and firebase storage are same. But I don't have gcp account. 
All My Work is on firebase apis so can someone pls help with Code Snippet.

Thanks in Advance

**Comment by sww314** [comment]
Go here: https://console.cloud.google.com/
All your firebase projects and your account is linked behind the scenes to Google.  The setup up for authentication will be the main difference.

As far as I know, you can not run python inside Firebase. You need a different compute, Cloud Functions, Cloud Run, AppEngine, or a VM.
