### ISSUE TITLE
Weird connection failure using SFTP backend

### ISSUE THREAD

**Issue by phnazari** [jschneier/django-storages#1056]
Hi Everybody,

I'm not sure if I have encountered a weird bug, so I thought I would post my question here.
I have a strange Problem using the SFTP API. I am trying to create a Proxy in order to fetch my media files from an external server. I figured that Middleware provides a good hook:

 ```
   import mimetypes
    
    from storages.backends.sftpstorage import SFTPStorage
    from django.http import HttpResponse
   
    
    
    from storages.backends.sftpstorage import SFTPStorage
    
    class SFTPMiddleware:
        def __init__(self, get_response):
            self.get_response = get_response
    
    
        def __call__(self, request):
            # Code to be executed for each request before
            # the view (and later middleware) are called.
    
            response = self.get_response(request)
    
            try:
                path = request.get_full_path()
                SFTP = SFTPStorage()  # <- this is where the magic happens
    
                if SFTP.exists(path):
                    file = SFTP._read(path)
    
                    type, encoding = mimetypes.guess_type(path)  
                    response = HttpResponse(file, content_type=type)
                    response['Content-Disposition'] = u'attachment; filename="{filename}"'.format(filename=path)
            except PermissionError:
                pass
    
            return response
```

which works fine, but obviously it opens a new connection every time a website call is issued which I don't want (it also crashes after 3 reloads or something, I think it has to many parallel connections by then). So I tried just opening one connection to the Server via SFTP by moving the `SFTP = SFTPStorage()`-initialization into the `__init__()`-method which is just called once:

   ```
 import mimetypes
    
    from storages.backends.sftpstorage import SFTPStorage
    from django.http import HttpResponse
    
    
    from storages.backends.sftpstorage import SFTPStorage
    
    
    class SFTPMiddleware:
        def __init__(self, get_response):
            self.get_response = get_response
            self.SFTP = SFTPStorage() # <- this is where the magic happens
    
    
        def __call__(self, request):
            # Code to be executed for each request before
            # the view (and later middleware) are called.
    
            response = self.get_response(request)
    
            try:
                path = request.get_full_path()

    
                if self.SFTP.exists(path):
                    file = self.SFTP._read(path)
    
                    type, encoding = mimetypes.guess_type(path)  
                    response = HttpResponse(file, content_type=type)
                    response['Content-Disposition'] = u'attachment; filename="{filename}"'.format(filename=path)
            except PermissionError:
                pass
    
            return response
```

But this implementation doesn't seem to work, the program is stuck either before the `SFTP.exists()` or after the `SFTP._read()` methods. Do wou know why that would be? It seems really odd to me.

Thanks for taking time. If you need any more information, just let me know.

Cheers,
Philipp

**Comment by jschneier** [comment]
Need more info. Can you step through it using `pdb`?

**Comment by jschneier** [comment]
Need more info. Can you step through it using `pdb`?

**Comment by Kingrimursel** [comment]
> Need more info. Can you step through it using `pdb`?

Yes, but as I am not very experienced with pdb, could maybe tell me which information you need?

**Comment by SorianoMarmol** [comment]
maybe you can test again with the latest version ( because this fix could help https://github.com/jschneier/django-storages/issues/1064 ;) )

FYI https://www.uni-muenster.de/AMM/num/Vorlesungen/Pythonkurs_SS15/pdb_cheatsheet.pdf 

* you can add the breakpoint before the exists and see exactly where it stops
* you can "step into" / step through with "s" command (check the cheasheet)
