### ISSUE TITLE
SFTPStorage: keep trying to connect when timeout (in a loop)

### ISSUE THREAD

**Issue by SorianoMarmol** [jschneier/django-storages#1064]
I was implementing saving a file in SFTP and, when testing time out, it was never launched.
I have debugged and it goes into a loop trying to connect.

Specifically:

- https://github.com/jschneier/django-storages/blob/master/storages/backends/sftpstorage.py#L67
```
        try:
            self._ssh.connect(self._host, **self._params)
        except paramiko.AuthenticationException as e:
```

the exception thrown is socket "timeout" (`from socket import timeout`)

I may not have done something correctly, but I have done this workaround (maybe it helps someone, or to illustrate the problem)

```
from socket import timeout
from storages.backends.sftpstorage import SFTPStorage

class SFTPStorageWithException(SFTPStorage):

    @property
    def sftp(self):
        try:
            return super().sftp
        except timeout as exc:
            log_message(f'Timeout connecting to SFTP: {exc}', 'error')
            raise paramiko.AuthenticationException(exc)
```

thanks

**Comment by amolinaalvarez** [comment]
I came across the same issue and was able to work around it by using @SorianoMarmol's approach.

**Comment by jschneier** [comment]
The patch does work, I will merge the fix shortly.

**Comment by SorianoMarmol** [comment]
thanks a lot!
