### ISSUE TITLE
collectstatic fails

### ISSUE THREAD

**Issue by spechtx** [jschneier/django-storages#1073]
Hello everyone,

I might came across a potential issue with the azure functionality in django-storages in version 1.12.1.

Django's python manage.py collectstatic fails with following error:

`azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x00000226A68C26D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed`

However the combination of the following works just fine, so i assume its not my settings, that cause the error:
django-storages==1.11.1
azure-storage-blob==2.1.0
azure-storage-common==2.1.0

Thanks :)

**Comment by pjsier** [comment]
Unfortunately I haven't been working with this for a while, but this sounds familiar to the error described here https://stackoverflow.com/a/64600812 where the resources may not exist
