### ISSUE TITLE
Secret key issue

### ISSUE THREAD

**Issue by Nando-bog** [jschneier/django-storages#109]
I'm running the latest master from github, since PyPi package threw similar error to what I'm getting now.
I'm attempting to create a custom S3BotoStorage class. Very simple... just a new location to put files in a specific folder.

When I import the class or the S3BotoStorage anywhere into my project, I get an ugly error related to the secret key being empty.

Any suggestions for possible fixes?

**Comment by jschneier** [comment]
Hi are you referring to the s3boto `AWS_S3_SECRET_ACCESS_KEY` or the Django `SECRET_KEY`. It sounds like a problem with your configuration. If you've got a repository I could take a look but I don't think this is a problem with this package.
