### ISSUE TITLE
: gets escaped as %3A (sometimes, and sometimes not?)

### ISSUE THREAD

**Issue by gabn88** [jschneier/django-storages#110]
I have this issue with the S3 file storage that keeps haunting me.

The problem is that sometimes the : is replaced by %3A and sometimes not. 

Normally this wouldn't mean a problem as Amazon accepts both, but if an signature is created for one of the two ways to write :, and the url is replaced with the other way the signature is incorrect.

The strange thing is, if I do file.url in my template it shows the :, but if I do file.url in my views it shows the %3A. Does anyone know how to circumvent/solve this?

**Comment by jschneier** [comment]
Hi and thanks for the report. That sounds like it might be an issue with storages but I honestly can't say for sure. Do you have a sample project that reproduces the 2 issues you mention? That would be very helpful for debugging.

**Comment by sww314** [comment]
Stale
