### ISSUE TITLE
GCS Interoperability mode for django-storages

### ISSUE THREAD

**Issue by ep4sh** [jschneier/django-storages#1102]
Dear community,

I am looking for information on how to configure the [pulp project](pulpproject.org) which uses django-storage.
I was told that currently AWS S3 and Azure are supported.

We're using Google Cloud Storage and I wonder how can I use GCS The Interoperability API to configure the storage?
I've tried to change AWS Secret/Access keys with GCS HMAC keys but the storage doesn't work. 

```
AWS_ACCESS_KEY_ID = '.....'
AWS_SECRET_ACCESS_KEY = '.......'
AWS_STORAGE_BUCKET_NAME = 'pulp-storage'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
```

I'll appreciate any suggestion, thanks in advance!

**Comment by jschneier** [comment]
You can just use the `gcloud.GoogleCloudStorage` directly. Django has a general storage API and this library implements a few.
