### ISSUE TITLE
Gevent is not compatible with boto3 S3 `use_threads`

### ISSUE THREAD

**Issue by Uxio0** [jschneier/django-storages#1110]
Since `boto3` version `1.4.2` S3 uploads set `use_threads=True` by default. It breaks S3 requests if `gevent` is used (https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3.html#threads).

I implemented a fix for `django-s3-storage` on https://github.com/etianen/django-s3-storage/pull/136

**Comment by jschneier** [comment]
I will merge a pull request if you want to put one together.

**Comment by Uxio0** [comment]
https://github.com/jschneier/django-storages/pull/1112
