### ISSUE TITLE
DEFAULT_FILE_STORAGE seems to be ignored

### ISSUE THREAD

**Issue by goldentoaste** [jschneier/django-storages#1115]
I would like my S3 bucket to have 2 folders, one for static, another for media. My understanding is that DEFAULT_FILE_STORAGE should the storage that handles media files, while STATICFILES_STORAGE handles static files. However it appears that DEFAULT_FILE_STORAGE is ignored and doesnt do anything, because for example if I set DEFAULT_FILE_STORAGE = "somestring", no error is thrown while running collectstatic.  

Here's my code:
```python
    #s3utils.py
    from storages.backends.s3boto3 import S3Boto3Storage                                          
    StaticRootS3BotoStorage = lambda: S3Boto3Storage(location='static')              
    MediaRootS3BotoStorage  = lambda: S3Boto3Storage(location='media') 

    #settings.py
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_OBJECT_PARAMETERS = {'ACL': 'private',}
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_LOCATION = 'static'
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'
    MEDIA_URL =  f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, "file-storage/")
    DEFAULT_FILE_STORAGE = 'backend.s3utils.MediaRootS3BotoStorage'                 
    STATICFILES_STORAGE = 'backend.s3utils.StaticRootS3BotoStorage'   
```

**Comment by Tudyx** [comment]
`collectstatic` will only use `STATICFILES_STORAGE` because it only collect static files. That's why you don't have an error when you change `DEFAULT_FILE_STORAGE`. If you want to test your `DEFAULT_FILE_STORAGE` you can do it by uploading a file through the admin panel. You will necessitate a model which have a `FileField` and not explicit storage parameter, i.e. that will use the `DEFAULT_FILE_STORAGE`
