### ISSUE TITLE
Setting similar to `AWS_LOCATION` but instead prepend a dynamic param for each model's files

### ISSUE THREAD

**Issue by pljspahn** [jschneier/django-storages#1122]
I have some other web services that will access files stored through Django/S3 and I'd like to keep my naming scheme consistent. 

I have a Django model `MyModel` that will store up to 10 images for each instance. `MyModel` has a `CharField` that is set with `unique=True` and I'd like to use this field's value when uploading files to S3, as this field is used commonly with our business and is analogous to a SKU.

So for example, I have two model instances saved, "Item A" and "Item B". I want the files to be uploaded to S3 so that the path looks like `/media/MyModel/<sku>/`

Item A's image paths would look like:

`/media/MyModel/ITM-A/item-a-base-photo.jpg`
`/media/MyModel/ITM-A/another-photo-of-item-a.jpg`
`/media/MyModel/ITM-A/these-photos-dont-have-consistent-naming-conventions.jpg`
`/media/MyModel/ITM-A/photo-9.jpg`

Item B, like so:

`/media/MyModel/ITM-B/some-photo.jpg`
`/media/MyModel/ITM-B/another-photo.jpg`

**Is there a strategy for having `django-storages` build these dynamic paths for me when uploading files for each model's instance?**

I'd prefer not to need to rely on tags assigned to each photo for this, as I plan to use tags in a different manner and being able to just access the images by path would be preferable.

**Comment by 9akashnp8** [comment]
You can modify the `upload_to` parameter to take a callable that creates the dynamic path for you. 

How I implemented dynamic paths based on year & date.

```# Helpers
def invoice_storage_path(instance, filename):
    from datetime import datetime
    TODAY = datetime.now()
    YEAR = TODAY.strftime('%Y')
    MONTH = TODAY.strftime('%B')
    return f'{YEAR}/{MONTH}/{instance.invoice_number}-{filename}'

# Create your models here.
class Invoice(models.Model):
    invoice_number = models.CharField(max_length=255)
    invoice_doc = models.FileField(upload_to=invoice_storage_path)
```

**Comment by jschneier** [comment]
Please see the comment from @9akashnp8 ^
