### ISSUE TITLE
How can I create a invalidation for AWS CloudFront? (CDN)

### ISSUE THREAD

**Issue by Gabym950** [jschneier/django-storages#1124]
Hello,
I have to implement a invalidation for a file on CDN. I have seen that boto had a boto.cloudfront implementation (https://github.com/boto/boto/tree/develop/boto/cloudfront).

How do I perform an invalidation on django in a easy way? Can I use django_storage?

Thanks!

**Comment by merwok** [comment]
I think the general practice is to use the manifest storage class, so that each file gets a filename dependent on its contents and gets cached forever, and a new version of the same file will get a different filename so that new requests go from clients to cloudfront to s3.

**Comment by jschneier** [comment]
Hi this is outside the scope of this library.
