### ISSUE TITLE
Way to failover gracefully on S3 timeout

### ISSUE THREAD

**Issue by carlosnasillo** [jschneier/django-storages#1125]
I am having an issue with Spaces (w/CDN) DigitalOcean (FRA1) where it seems to timeout on some objects at random, therefore causing server-side view render to fail. The issue its currently under investigation with DO support. But this has lead me to investigate a more resilient way to mitigate for this on my end. 

Is there a configuration option for storages to either failover to a local copy of the file, or a way to have it retry using another static/media endpoint URL (ie. a carbon-copy S3 bucket on another region)?

Would really appreciate any pointers here. Thanks!

**Comment by jschneier** [comment]
Nothing like this exists but I'd welcome something that adds retries if they're not already implemented
