### ISSUE TITLE
Support for Oracle Object Storage

### ISSUE THREAD

**Issue by anhilash** [jschneier/django-storages#1127]
Hi All,

Is there any support for Oracle Object Storage, We have client who is insisting  to host on oracle.

**Comment by pwqw** [comment]
OCI Object Storage **is full compatible** with AWS S3 **API**.

You can check this https://medium.com/oracledevs/use-aws-python-sdk-to-upload-files-to-oracle-cloud-infrastructure-object-storage-b623e5681412

**Comment by jschneier** [comment]
It is S3 compat and docs exists for it now!

**Comment by MuhammadWaqarAnwar** [comment]
Can someone please provide the docs link for it?
