### ISSUE TITLE
[GCP] Django's GET request return `null` for image field but upload the images.

### ISSUE THREAD

**Issue by jeetpatel9** [jschneier/django-storages#1136]
I am using `django storages` for uploading and retrieving the images from the `google cloud storage`. 

I did everything as told in the documentation -

1. Created a private bucket on Cloud Storage.
2. Created a service account with Storage Admin privileges and also generated a JSON key.
3. Installed Django Storages for GCP and Pillow.
4. Created relevant environment variables like GOOGLE_APPLICATION_CREDENTIALS, GOOGLE_CLOUD_PROJECT and GS_BUCKET_NAME.
5. Wrote a POST & GET request and it works like a charm on the local machine.

However, when I deployed this on Cloud Run I am able to upload the images but I get NULL instead of the image's URL in response while fetching the image via **_GET_** request. As Cloud Run uses Compute Engine Default Service Account so I decided to give it a Cloud Storage Admin permission and then I tried again but still no luck.

How can I make it work on cloud run as well? I did not provide `GOOGLE_APPLICATION_CREDENTIALS` as the environment variable on the cloud run. As I believe it will use Compute Engine Default Service Account to get the necessary permissions.

**Comment by jeetpatel9** [comment]
can anyone help me here please? @alex

**Comment by gionn** [comment]
what was the issue here? I am facing a similar problem and I am not getting any error, just null field but file has been properly uploaded.
