### ISSUE TITLE
Gcloud "This backend doesn't support absolute paths.")

### ISSUE THREAD

**Issue by ericel** [jschneier/django-storages#1149]
>  NotImplementedError: This backend doesn't support absolute paths

I am getting this error with Google Cloud when I try something like this:
`template_media_path = default_storage.path(filetemplate.template_html.name)`
Which is understandable.
My question is, can we use default_storage.path in google GCloud with this package?

**Comment by jschneier** [comment]
[Docs](https://docs.djangoproject.com/en/4.0/ref/files/storage/#django.core.files.storage.Storage.path) are pretty clear on this point.
