### ISSUE TITLE
s3boto backend does not set CORS rules on bucket

### ISSUE THREAD

**Issue by fghaas** [jschneier/django-storages#115]
When using the s3boto backend for static asset storage and/or compressed assets, browsers will enforce CORS rules on at least some assets (fonts being the canonical example).

Currently it is up to the user to set appropriate CORS rules on the bucket, such that the required CORS headers are set; `Access-Control-Allow-Origin` being the most prominent example (API documentation [here](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTcors.html); user documentation [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) and [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/ManageCorsUsing.html)).

boto supports the creation of CORS rules via the [`CORSConfiguration`](http://boto.cloudhackers.com/en/latest/ref/s3.html#boto.s3.cors.CORSConfiguration) object. It would be great if the s3boto backend could automatically add rules adding the current site to the allowed origins listing, doing something akin to the following:

``` python
current_site = get_current_site(request)
cors = boto.s3.cors.CORSConfiguration()
for method in ['GET', 'HEAD']:
  cors.add_rule(method, current_site.domain)
bucket.set_cors(cors)
```

The above code isn't expected to actually work, just trying to illustrate the concept.

**Comment by jnegro** [comment]
Is there any chance this issue might be addressed any time soon.  I too am having this problem while setting up automated deployments, and have to manually alter the bucket if I let django_storages create it.  The fonts being an issue for me as well.

**Comment by mar77i** [comment]
Please excuse me if relevancy of what I'm going to say is limited for this issue, but the way I understand the problem, it also applies to `backend.s3boto3.S3Boto3Storage` regarding the CORS configuration.

For now, I wrapped `_get_or_create_bucket()` as a `backends.s3boto3.S3Boto3Storage` subclass. Maybe there's an even more elegant way?
```python
from django.utils.deconstruct import deconstructible
from storages.backends.s3boto3 import S3Boto3Storage


@deconstructible
class S3Boto3CorsStorage(S3Boto3Storage):
    def __init__(self, *args, **kwargs):
        self.cors = kwargs.pop("cors", None)
        super().__init__(*args, **kwargs)
        print(type(self.connection))

    def _get_or_create_bucket(self, name, cors=None):
        bucket = super()._get_or_create_bucket(name)
        if self.cors is not None:
            bucket.Cors().put(CORSConfiguration=self.cors)
        return bucket

```

**Comment by fghaas** [comment]
Hi @jschneier, I'm the original reporter of this issue — could I ask you to add a brief comment how to address this, now that the issue is closed? Are you suggesting people use the workaround from https://github.com/jschneier/django-storages/issues/115#issuecomment-384260630, or has this been fixed some other way?

**Comment by jschneier** [comment]
Hi, bad news unfortunately. I’ve decided to deprecate bucket creation with this library because it encourages granting overly broad credentials.

**Comment by fghaas** [comment]
Ah, fair. So you mean the bucket has to be created manually (or at least, it isn't being transparently created by the library), and thus the onus for setting ACLs, CORS rules etc. is on the bucket creator. Did I get that right?

**Comment by jschneier** [comment]
Yup

**Comment by fghaas** [comment]
Works for me, thanks!
