### ISSUE TITLE
can't save file without loading whole file into memory

### ISSUE THREAD

**Issue by darkNavi** [jschneier/django-storages#1153]
When trying to save any content to FileField backed with django-storages, resulting in loading whole file into RAM, that is absolutely unacceptable when you need to save large file.

```python
with open(file_name, "rb") as csv_file:
    mode_instance.file_field.save(file_name, csv_file)
```

Any ideas how to instruct s3boto3 to upload using chunks? I think in `GoogleCloudStorage` there is a setting for such case - `GS_BLOB_CHUNK_SIZE`, but i need such settings for S3

**Comment by jschneier** [comment]
Does `AWS_S3_MAX_MEMORY_SIZE` not cover it?

**Comment by jschneier** [comment]
Does `S3Boto3StorageFile` not upload in 5 MB chunks?

**Comment by jschneier** [comment]
Also see the new `TransferConfig` setting.
