### ISSUE TITLE
[gcloud] Feature request: allow to upload static files to a specific folder similar to what `STATIC_ROOT` does

### ISSUE THREAD

**Issue by gdalmau** [jschneier/django-storages#1155]
In https://django-storages.readthedocs.io/en/latest/backends/gcloud.html#getting-started it shows that we can configure `STATICFILES_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'` to upload the static files to a Google Cloud Storage bucket, but all the files will be uploaded on the root or on the location specified by `GS_LOCATION`.

It would be nice to allow to specify a folder to upload the static files in order to differentiate them with the user-uploaded files (media files via the `upload_to` parameter on `FileField`).

**Comment by KarovInal** [comment]
+1

**Comment by jschneier** [comment]
This was doable via subclassing before 4.2 and with OPTIONS with 4.2
