### ISSUE TITLE
Implement file.path for S3BotoStorage

### ISSUE THREAD

**Issue by ketanbhatt** [jschneier/django-storages#117]
I felt the need to use `file.path` in my project, and it wasn't implemented. 

I am guessing it was left unimplemented for some reason. If there was no reason I would like to submit a PR for it.

Thanks

**Comment by jschneier** [comment]
Hi and thanks for your interest. The Django docs specifically say that `file.path` should only be available for storages that are on the local filesystem.

```
path(name)[source]¶

The local filesystem path where the file can be opened using Python’s standard open().
For storage systems that aren’t accessible from the local filesystem, this will raise
NotImplementedError instead.
```

I'd suggest looking at `file.url`.
