### ISSUE TITLE
Can you release unreleased version please? 

### ISSUE THREAD

**Issue by zcuric** [jschneier/django-storages#1175]
Hi, can you release unreleased version please? The fix #1172 and other fixes is highly needed. Thank you!

**Comment by jeroenpeters1986** [comment]
@zcuric I think you can just check it out from source for exactly this usecase, see also https://github.com/jschneier/django-storages#installation

**Comment by jschneier** [comment]
Unfortunately that fix doesn't always work, see this comment: https://github.com/jschneier/django-storages/issues/1117#issuecomment-1213111057

I don't want to release something that is known broken. A pull request would be welcome.

**Comment by zcuric** [comment]
@jschneier Oh, i'm sorry, I missed that comment. Will look into it!
