### ISSUE TITLE
If "~/.ssh/known_hosts" does not exist, SFTP backend fails

### ISSUE THREAD

**Issue by jonazn** [jschneier/django-storages#118]
In the SFTPStorage backend, the _connect() method attempts to "automatically add host keys from the current user," by loading the "~/.ssh/known_hosts" file. However, it doesn't check if that file actually exists before trying to use it. I spent a while trying to figure out why the SFTP backend wasn't working on my own server before pinpointing this issue. This happens on line 97 of sftpstorage.py:

`self._ssh.load_host_keys(os.path.expanduser(os.path.join("~", ".ssh", "known_hosts")))`

Perhaps it would be useful to wrap that line in a try/except?

**Comment by jschneier** [comment]
Yeah we should definitely catch that error.

Hmm, the default is to automatically accept unknown hosts which seems...eager? My thinking is to deprecate that default and then if we do catch an error and you haven't told us to auto add I'll just raise a full on exception. What do you think of that plan?

**Comment by jonazn** [comment]
That sounds like a reasonable solution, but there are also times you'd maybe want that behavior? For example, the reason I'm using SFTP is so that I can have an inexpensive DigitalOcean server to host all my media files, but I'm using AWS for everything else (S3 data transfer is just too expensive). My Django app will upload user files to the DigitalOcean server. But EC2 instances that spin up with Elastic Beanstalk don't have a known_hosts file by default, nor is there an easy, built-in way to set one. I'm hacking together a solution by simply running the command "touch known_hosts" in ~/.ssh every time a new EC2 instance starts up to have an empty file.

Perhaps a solution could be an additional setting that, if set, lets you accept unknown hosts? It could default to False.

**Comment by jschneier** [comment]
Oh yeah, of course. I'm not even sure how I feel about the fact that it automatically loads the keys in `~/.ssh/knows_hosts`.

Not sure how big of a deal it is though.

**Comment by freshquiz** [comment]
This issue just bit me, but in a roundabout way.

In the `SFTPStorage.exists()` method there is try/catch `IOError` around this `self.sftp.stat(remote_path)` and that call goes down to hit this issue.

So that try/catch is catching the wrong exception and returning False, which causes infinite recursion when trying to create a directory that doesn't exist.

**Comment by sallyruthstruik** [comment]
Pull request with fix: https://github.com/jschneier/django-storages/pull/325

**Comment by jschneier** [comment]
Fix merged
