### ISSUE TITLE
Add support for version v2 for Google signed URLs

### ISSUE THREAD

**Issue by databaaz** [jschneier/django-storages#1180]
The current v4 version used for generating signed URLs has a max expiration time of 7 days, any value set higher than this for `GS_EXPIRATION` leads to an exception.

I suggest to allow the users to set an additional flag (such as `GS_SIGNED_URL_VERSION`) to choose which one they prefer to use. Would greatly help for use cases where a longer expiration time is desired.

**Comment by jschneier** [comment]
This is fixed by #1193.
