### ISSUE TITLE
release an updated docs on readthedocs

### ISSUE THREAD

**Issue by luzfcb** [jschneier/django-storages#119]
since https://github.com/jschneier/django-storages/commit/7875a755f07009f0e6885280d2a782269bb8c258 becomes the [official package](pypi.python.org/pypi/django-storages) in PyPi, it's good to update the documentation on ReadTheDocs.

@jschneier Perhaps @ericholscher can help you with the permissions on ReadTheDocs

update:
> The updated docs was pushed to readthedocs on 2016-10-17

**Comment by derek-adair** [comment]
In addition, an updated changelog / bugfix list would be very slick .

**Comment by paulfurley** [comment]
I just got very confused by this: the [current S3 documentation](http://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html) talks about multiple backends:

> There are two backend APIs for interacting with S3. The first is the s3 backend (in storages/backends/s3.py) which is simple and based on the Amazon S3 Python library. The second is the s3boto backend (in storages/backends/s3boto.py) which is well-maintained by the community and is generally more robust (including connection pooling, etc...). s3boto requires the python-boto library.

... but I see this was completely changed in a [commit from December 2014](https://github.com/jschneier/django-storages/commit/0cf4396340edb1106733401de9fd93cc184d0449#diff-620fc48798a1f60f7ceea7f84832ff22L12)

This is making it quite difficult to use with otherwise fantastic project :)

**Comment by derek-adair** [comment]
ya this is probably going to be a hug effort tho, very difficult to retroactively update documentation without complete understanding of the code base.

**Comment by paulfurley** [comment]
The documentation has already been updated in the repo, it just hasn't been published to readthedocs.

Sent on the move.

**Comment by rygwdn** [comment]
looks like the readthedocs documentation is pointed at the wrong repo (as per https://github.com/jschneier/django-storages/issues/153). It would be very helpful to have the updated docs published for this project!

**Comment by luzfcb** [comment]
@richleland I saw that https://django-storages.readthedocs.io/ apparently is linked to your username. 

if possible, you could give the necessary permissions to @jschneier, so it can publish the a new version of the documentation.

To add permission, please, do the login https://readthedocs.org/accounts/login/

and add @jschneier and/or my username on https://readthedocs.org/dashboard/django-storages/users/

thanks

**Comment by richleland** [comment]
Hey everyone - happy to get this resolved. I just tried to add jschneier as an admin but readthedocs tells me `User jschneier does not exist`. Let me know what the proper username is and I'll take care of it.

**Comment by richleland** [comment]
In the meantime I went ahead and updated the URLs in the project and made sure the latest versions were published.

**Comment by luzfcb** [comment]
@richleland thank you so much

**Comment by luzfcb** [comment]
@jschneier I think you may need to create an account in readthedocs and/or inform your readthedocs username .

**Comment by jschneier** [comment]
@richleland thanks for taking care of this. i just created a readthedocs account as username `jschneier`.

**Comment by richleland** [comment]
No problem! I added you to the readthedocs project.
