### ISSUE TITLE
Allow multiple S3 buckets to be defined

### ISSUE THREAD

**Issue by VaZark** [jschneier/django-storages#1192]
Use Case  : When dealing with multitenant services, it'd be ideal if we could define the multiple S3 buckets for each client and dynamically set the bucket to use with django-storages.

Moreover, we do not have to look far for inspiration. We can reuse the Databases logic to handle and set the S3 bucket config. Users can then dynamically select the bucket with threading local or their preferred setup.

```python
## settings.py
STORAGES = {
    "S3_1": {
        "AWS_ACCESS_KEY_ID": "",
        "AWS_SECRET_ACCESS_KEY": "",
        "AWS_STORAGE_BUCKET_NAME": "",
        "AWS_CLOUDFRONT_URL": "",
        "AWS_S3_CUSTOM_DOMAIN": "",
    }, 
     "S3_2": {
        "AWS_ACCESS_KEY_ID": "",
        "AWS_SECRET_ACCESS_KEY": "",
        "AWS_STORAGE_BUCKET_NAME": "",
        "AWS_CLOUDFRONT_URL": "",
        "AWS_S3_CUSTOM_DOMAIN": "",
    }
}

## S3Router.py
class OpenStorage(S3Boto3Storage):
   storage_settings = settings.STORAGES["S3_1' ]
  ## or 

dynamicStorage = S3BotoStorage("S3_1")
```

**Comment by nitsujri** [comment]
Dynamic storages is handled by [`get_storage_class()`](https://docs.djangoproject.com/en/4.1/ref/files/storage/#django.core.files.storage.get_storage_class).

Specifically you'd want something like:

```python
# users.model.py

def storage_picker(user_instance):
    ...picking-logic...
    picked_storage_klass = get_storage_class(...)
    return picked_storage_klass()

class User(AbstractUser):
    avatar = ImageFiled(storage=storage_picker)
```

**Comment by VaZark** [comment]
Thanks. I'll give that a shot. Is the storage picker called invoked on every request or calculated once during start

**Comment by bodgerbarnett** [comment]
> Dynamic storages is handled by [`get_storage_class()`](https://docs.djangoproject.com/en/4.1/ref/files/storage/#django.core.files.storage.get_storage_class).
> 
> Specifically you'd want something like:
> 
> ```python
> # users.model.py
> 
> def storage_picker(user_instance):
>     ...picking-logic...
>     picked_storage_klass = get_storage_class(...)
>     return picked_storage_klass()
> 
> class User(AbstractUser):
>     avatar = ImageFiled(storage=storage_picker)
> ```

It looks to me as if the storage callable isn't passed the user_instance (or indeed anything at all!) so there's no way of calculating the storage class from the instance as you've written it here.

**Comment by jschneier** [comment]
No library updates are needed to support `STORAGES` so you should be good to go on 4.2+
