### ISSUE TITLE
Make django-storages compatible with the new Django's settings `STORAGES`

### ISSUE THREAD

**Issue by pauloxnet** [jschneier/django-storages#1207]
In Django 4.2 the new settings ``STORAGES`` has been added.
https://github.com/django/django/commit/1ec3f0961fedbe01f174b78ef2805a9d4f3844b1

The ``DEFAULT_FILE_STORAGE`` and ``STATICFILES_STORAGE`` settings are deprecated in Django 4.2 and will be removed Django 5.1.
https://github.com/django/django/commit/32940d390a00a30a6409282d314d617667892841

**Comment by philgyford** [comment]
It looks like the new docs are wrong. They say to use the new `STORAGES` setting like this:

```python
    STORAGES = {"default": "storages.backends.s3boto3.S3Boto3Storage"}
```

But it should be:

```python
    STORAGES = {"default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"}}
```

Django docs: https://docs.djangoproject.com/en/4.2/ref/settings/#storages

**Comment by pauloxnet** [comment]
Thanks for reporting.
Can you open a PR with the fix?

**Comment by philgyford** [comment]
When I get a chance. Currently trying to fix a couple of other "I upgraded to Django 4.2" bugs!
