### ISSUE TITLE
Readme file confusing

### ISSUE THREAD

**Issue by willyhakim** [jschneier/django-storages#121]
Readme file should say 
`pip install django-storages-redux` instead of `pip install django-storages`

**Comment by mbarrien** [comment]
It was just renamed to take over the old pypi django-storages. The README is correct.

**Comment by jschneier** [comment]
@willyhakim yeah I _just_ received access to the old `django-storages` PyPI name and all future releases will be as that package name.

Thanks @mbarrien.

**Comment by jschneier** [comment]
(And the current one is as well, that is the only change between 1.3.2 and 1.4)
