### ISSUE TITLE
django-storages and mypy integration

### ISSUE THREAD

**Issue by KMoreno96** [jschneier/django-storages#1214]
When using mypy, the next error appeared: 

"Skipping analyzing "storages.backends.s3boto3": module is installed, but missing library stubs or py.typed marker  [import]mypy"

As for third-party modules, the solution will be to add support by bulding a django-storages-stubs package, so it can integrate well.

For now, for any user that may face this error, in the mypy.ini, add the following lines so mypy ignores the error:

```
[mypy-storages.*]
ignore_missing_imports = true
```

**Comment by jschneier** [comment]
Given that Django itself does not do typing I don't think it makes sense for the directly downstream libraries to do it either. I would accept pull requests adding it though.
