### ISSUE TITLE
Serving and Opening Media Files using FTP storage

### ISSUE THREAD

**Issue by yulianrudenko** [jschneier/django-storages#1215]
Hi, could anyone explain how to properly configure project to serve media files directly from FTP server (if it's possible using this package).
I've already managed to connect project with remote FTP server and I'm even able to upload files to it, however I have no idea how can I open/serve those uploaded sites now, documentation for FTP does not provide that much info, what is the right way to set MEDIA_URL, MEDIA_ROOT etc. to enable that? Not experienced enough with FTP and it's seems to be more complicated that usual File storage or AWS3. Thanks in advance.
![Screenshot from 2023-02-13 18-46-13](https://user-images.githubusercontent.com/88377969/218533477-f33d1010-23b8-40fb-a3b8-e47c9355ec01.png)

**Comment by jschneier** [comment]
Essentially you need to make the files available over HTTP if using Django. So generally you'd open the file (using the storage generally), `read` it in and serve via something like `FileResponse`. Another option is to serve via some kind of CDN like Cloudfront and just template out the link for the frontend.

Your question isn't really about this library so I'm going to close this issue but let me know if that was helpful or not.

**Comment by yulianrudenko** [comment]
> Essentially you need to make the files available over HTTP if using Django. So generally you'd open the file (using the storage generally), `read` it in and serve via something like `FileResponse`. Another option is to serve via some kind of CDN like Cloudfront and just template out the link for the frontend.
> 
> Your question isn't really about this library so I'm going to close this issue but let me know if that was helpful or not.

Yep, You are right, my bad, sorry and thank you :)
