### ISSUE TITLE
AWS S3 "extra" has a confusing name

### ISSUE THREAD

**Issue by allanlewis** [jschneier/django-storages#1231]
This package defines an "extra" for each storage backend: https://github.com/jschneier/django-storages/blob/90e2e78ea358b8c77a1884d4c2c43dffb8066a60/setup.cfg#L38-L50

These don't seem to be documented; that's a separate issue.

This issue is about the naming of the extra for AWS S3. Most of the extras are (sensibly) named after the backend, e.g. Dropbox or Google, but the S3 one is named "boto3" after the library used to interact with AWS. In order to follow the naming pattern of the others, surely "aws" would be a better name?

In order to avoid a breaking change it might make sense to duplicate the "boto3" extra as "aws" rather than renaming it.

**Comment by jschneier** [comment]
The reason is legacy, in the (distant) past there was a backend based off of `boto` and I took possession of this library long long ago.

In general I’d like to do a rename passing on almost everything and switching this to AWS (or adding it) is fine.
