### ISSUE TITLE
GS_BUCKET_NAME incompatible if we have many buckets within STORAGES django 4.2

### ISSUE THREAD

**Issue by ayyoubelamrani4** [jschneier/django-storages#1232]
Hi there,

If we have two different storages in the settings.

Setting `GS_BUCKET_NAME` would overwrite those storages.

An option would be to detect GS_BUCKET_NAME from the OPTIONS provided in STORAGES.

**Comment by jschneier** [comment]
Probably all of the various settings should move into `OPTIONS` but we can start by including those values when we init.

The way this has been handled up to now is to subclass the backend and set it as a property.

**Comment by jschneier** [comment]
This should _just work_ actually if you set `bucket_name` in the `OPTIONS` dict because `**settings` overrides `get_default_settings`; I will document all of the names. We are going to end up deprecating all of the settings anyway given the new structure.
