### ISSUE TITLE
Unclosed SFTP connection

### ISSUE THREAD

**Issue by TimoGuenther** [jschneier/django-storages#1234]
Consider a one-off use of `SFTPStorage` as you might for example see in a Celery task:

```py
from storages.backends.sftpstorage import SFTPStorage

SFTPStorage(...).listdir("")
```

Unfortunately, the underlying SSH connection might stay open and continue using resources. [Paramiko's documentation of `close`](https://docs.paramiko.org/en/latest/api/client.html#paramiko.client.SSHClient.close) warns about this:

> Paramiko registers garbage collection hooks that will try to automatically close connections for you, but this is not presently reliable. Failure to explicitly close your client after use may lead to end-of-process hangs!

Workaround:

```py
from paramiko.util import ClosingContextManager
from storages.backends.sftpstorage import SFTPStorage

class ClosingSFTPStorage(SFTPStorage, ClosingContextManager):
    def close():
        self._ssh.close()

with ClosingSFTPStorage(...) as sftp:
    sftp.listdir("")
```

**Comment by jschneier** [comment]
Cool good fine. Can you open a PR that includes that change into the base `SFTPStorage` and then add that snippet to the docs with a warning.
