### ISSUE TITLE
S3Boto3Storage.exists() always returns False

### ISSUE THREAD

**Issue by bphariharan1301** [jschneier/django-storages#1243]
Hey guys, need a small help again

I'm having an issue with S3Boto3Storage.exists()

It always returns false even though I have that directory present in the bucket.

I need to know what is going wrong as I want to make sure that if a user uploads new file with same content but, with different file name I would want only the newly uploaded to be visible.

I'm attaching AWS configs, storages_backends.py, views.py

settings.py
```
# AWS Config
AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID '
AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY'
AWS_STORAGE_BUCKET_NAME = 'AWS_STORAGE_BUCKET_NAME'
AWS_S3_SIGNATURE_NAME = 's3v4',
AWS_S3_REGION_NAME = 'ap-south-1'
AWS_S3_FILE_OVERWRITE = True
AWS_DEFAULT_ACL = None
AWS_S3_VERITY = True
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
```
storages_backends.py
```
from storages.backends.s3boto3 import S3Boto3Storage
class MediaStorage(S3Boto3Storage):
     bucket_name = 'bucket-name'
```

views.py (where the logic is going wrong

```
if request.method == 'POST':
      print('INSIDE POST DOC UPLOAD')
      doc_storage = MediaStorage()
      team = Team.objects.filter(teamID=user.username).get()
      media_storage = MediaStorage()
      file_path_bucket = 'documents/{0}'.format(request.user.username)
      print('Path is: ', file_path_bucket)
      Below line always returns False
      print('Check Dir', media_storage.exists(file_path_bucket))
```

For example if I upload a file to documents/CSE-001 the directory present. So, when I pass this directory to exists() it should return True instead of False because, that directory exists inside the bucket. I'm attaching an screenshot of the directory which is created when a user uploads a file.

![AWS Bucket Structure](https://user-images.githubusercontent.com/56637724/234053911-b79cbd42-55d2-4301-a819-5048ccd4eecf.png)

Please help me with that...

I'm not sure where I have gone wrong 

Thank you

**Comment by jschneier** [comment]
Are you trying to check if the directory exists? For that you need to include the trailing "/".
