### ISSUE TITLE
Use Dropbox Refresh Token

### ISSUE THREAD

**Issue by Samiddha99** [jschneier/django-storages#1244]
I am using django-storages[dropbox] to serve media or user uploaded files.

I used below-mentioned settings in settings.py:
**DROPBOX_APP_KEY** = my_dropbox_key
**DROPBOX_CONSUMER_KEY** = my_dropbox_key
**DROPBOX_APP_SECRET** = my_app_secret
**DROPBOX_CONSUMER_SECRET** = my_app_secret
**DROPBOX_OAUTH2_TOKEN** = generated_oauth2_access_token (generated by clicking on Generate button in app console settings)
**DROPBOX_ACCESS_TOKEN** = generated_oauth2_access_token
**DROPBOX_APP_ACCESS_TOKEN** = generated_oauth2_access_token
**DROPBOX_AUTHORIZATION_KEY** = generated by using the link - https://www.dropbox.com/oauth2/authorize?client_id=APP_KEY&token_access_type=offline&response_type=code

**DEFAULT_FILE_STORAGE** = 'storages.backends.dropbox.DropBoxStorage'
**DROPBOX_ROOT_PATH** = 'path_to_my_root_folder'

But I am getting the error:-
     INFO:     Request to files/get_metadata
     INFO:     ExpiredCredentials status_code=401: Refreshing and Retrying
      WARNING:  Unable to refresh access token without  refresh token and app key

Since, Dropbox now don't provide never-expired token, hence how do I use _refresh token_ in django to serve media files?

**Comment by jschneier** [comment]
Can't you set `DROPBOX_OAUTH2_REFRESH_TOKEN`?
