### ISSUE TITLE
Cleanup after aborted connection can throw error

### ISSUE THREAD

**Issue by JackDunnNZ** [jschneier/django-storages#1256]
In the following code:

https://github.com/jschneier/django-storages/blob/a87dea670dc7a6a27cc2cb83f4c90b0129e9998b/storages/backends/s3boto3.py#L172-L176

If the connection is aborted after `self._is_dirty` is set to `True`, but before `self._multipart` is assigned, then `self._multipart` will remain `None`. Then during cleanup:

https://github.com/jschneier/django-storages/blob/a87dea670dc7a6a27cc2cb83f4c90b0129e9998b/storages/backends/s3boto3.py#L231-L234

we try to call `self._multipart.complete`, which will throw 

```
'NoneType' object has no attribute 'complete'
```

This path in the cleanup should have some check for `self._multipart is not None`. I would file a PR but I am not sure of the right logic for this case and what exactly should be guarded.

**Comment by jschneier** [comment]
I don't really get this one because `_flush_write_buffer` also refers to `self._multipart` before the `complete` method, do you have any ideas?

**Comment by jschneier** [comment]
I guess `buffer_file_size` is zero at that point, okay.
