### ISSUE TITLE
Unable to verify from ImageField that the image path exists in database without downloading the image 

### ISSUE THREAD

**Issue by gschurck** [jschneier/django-storages#1263]
I want to check if an ImageField contains a path, but with each time I want to access the field to check an attribute value it triggers a download of the image from S3 with django-storages, so performance is horrible.
```python
if instance.image : # triggers download

if instance.image.name # triggers download

if default_storage.exists(instance.image.name) # triggers download
```
Maybe I am missing something but I really don't succeed to access original Django field data from the image instance when using django-storages.
Can it be because I was running with DEBUG=True ?

Is it still possible by changing database query or with a boolean attribute in database but it's really not ideal...

**Comment by jschneier** [comment]
This seems like an upstream issue, please open a ticket with Django.
