### ISSUE TITLE
Lots of open PRs with no feedback or action

### ISSUE THREAD

**Issue by jasonzio** [jschneier/django-storages#1266]
Is there any help you need, @jschneier, to progress some of the PRs that have no feedback or no action?

Obviously I care most about #1178 but that's not the only one that's been hanging fire.

**Comment by jschneier** [comment]
Hi, yes, it's the peril of open source unfortunately :|

This library is also made worse by the fact that to test "live" I really need to have actual accounts and the like for many of these changes. The first version of https://github.com/jschneier/django-storages/pull/1286 would have broken reading files but I only discovered that by actually testing it which was more intuition than anything else.

For your change, for example, there are a few things at work:

1. I've never heard of `django-guid` and if I bless that library I will have to bless many others. It has 360 stars but that is obviously a very imperfect proxy for popularity, it'd be better if e.g it was from Microsoft. Or the library will rot and then it is a difficult position
2. The aforementioned lack of Azure account (the docs don't even show `headers` as a valid parameter in my cursory examination) and integration CI
3. It's fun to tell people yes and not fun to tell people no. On the other hand I've previously merged things I didn't think were a great idea e.g `DropboxStorage` and now I am the only person making bugfixes and updating the docs

**Comment by thibaudcolas** [comment]
Thought I’d mention we can always reach out to Azure folks (or Dropbox or any other) if there’s a need of test infrastructure. Not sure if those folks would use Django / django-storages themselves but it’s in their interest that it works well on their infra.

Happy to go hunt for contacts if it helps, let me know.
