### ISSUE TITLE
Different storage locations

### ISSUE THREAD

**Issue by sowinski** [jschneier/django-storages#1273]
Hi,

is it possible to use different s3 buckets for media and static files?

I also have some "secret" files, like bills which I also want to place to a different s3 bucket which is not public avaiable.

Thank you

**Comment by PetrDlouhy** [comment]
@sowinski Check out the new STORAGES settings introduced in Django 4.2: https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-STORAGES

Note: the support for this new setting is not yet very well covered in 3-rd party applications (not even in `django-storages`), so you can expect some hurdles if you switch to that now.

**Comment by jschneier** [comment]
Hi, yes, you can. If you use `STORAGES` with `OPTIONS` with the right key parameters this will work. I am adding documentation for this now.
