### ISSUE TITLE
support for object lifecycle for S3

### ISSUE THREAD

**Issue by VaZark** [jschneier/django-storages#1275]
Is there a way to define object expiry when using s3?  I'd like to setup a storage backend for a `temp` folder on S3 for files used in wizard form etc. While configuring as a rule directly on S3 is possible, it is easier to read and ensure such granular control on the application logic and let DevOps handle only provisioning and bucket-level ACL

**Comment by jschneier** [comment]
Sorry, I made the decision that bucket configuration should be handled outside of this library. Given that the bucket needs to be provisioned with an ACL anyway and the lifecycle is attached to the bucket, it makes more sense to centralize that in one place in my opinion.
