### ISSUE TITLE
The `AWS_*` settings are overriding STORAGES OPTIONS

### ISSUE THREAD

**Issue by PetrDlouhy** [jschneier/django-storages#1277]
This issue is very close to #1276 but is potentially different problem.

When I have settings like:

```python
AWS_ACCESS_KEY_ID = "key_general"
AWS_SECRET_ACCESS_KEY = "key_general"
AWS_STORAGE_BUCKET_NAME = ...

STORAGES = {
    "thumbnails": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": "key_thumbnails",
            "secret_key": "key_thumbnails",
        }
    },
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": "key_default",
            "secret_key": "key_default",
        }
}
```

The general `AWS_*` settings will be used primarily for the `default` and `thumbnails` storages and the `OPTIONS` will be ignored.

With issue #1276 present, this means, that it is not possible to use new STORAGES settings as long as there are any application accessing the default (staticfiles) storage by `DEFAULT_STATICFILES_STORAGE`.

**Comment by jschneier** [comment]
Sorry, I don't see this one. I think if you set `access_key` or `secret_key` we will take the value from `OPTIONS` over the one from `AWS_*` right?

**Comment by PetrDlouhy** [comment]
According to my testing/experience the value from `AWS_*` will be taken first, but I might have misinterpret something.
I could try write a test for this on monday if you are interested.

**Comment by jschneier** [comment]
Sure that would be helpful. I need to put out a new release and compat with Django 4.2 is the top priority.

**Comment by PetrDlouhy** [comment]
I am not sure what I was testing, but it seems, that it in fact work correctly. Sorry for this misinformation.

If you are still interested in the test, here it is:
```python
    @override_settings(
        STORAGES={
            'foo': {
                'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
                'OPTIONS': {
                    'access_key': 'foo',
                    'secret_key': 'bar',
                },
            },
        },
        AWS_ACCESS_KEY_ID='foo1',
        AWS_SECRET_ACCESS_KEY='bar2',
    )
    def test_options_preference(self):
            storage = storages['foo']
            self.assertEqual(storage.access_key, 'foo')
            self.assertEqual(storage.secret_key, 'bar')
```
It does pass only in Django 4.2.

I am closing this issue. I will reopen if I find that something is wrong with it anyway.
