### ISSUE TITLE
Cleanse references to this being a fork

### ISSUE THREAD

**Issue by derek-adair** [jschneier/django-storages#129]
I think now that this repository is being published via django-storages, its time to start cleaning up the documentation that references this as a fork.  It was very confusing to read that this is (was) a fork, and have the install instructions pointing to django-storages.

To avoid confusing new / returning users to this project I think a small paragraph explaining what happened and that we now have control over the namespace again would be a major improvement.  Preferably in really big bold letters.

**Comment by jschneier** [comment]
Yep, will do this now.

**Comment by jschneier** [comment]
Just did this, let me know if you think the README can be improved

**Comment by derek-adair** [comment]
Looks great!!!

cheers!
