### ISSUE TITLE
can't use bucket names with dots

### ISSUE THREAD

**Issue by jschneier** [jschneier/django-storages#13]
see boto/boto#2836

might need to switch the default calling format to be Original instead of Subdomain

**Comment by HiddenFox** [comment]
Check https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto.py line 228.
You can set AWS_S3_CALLING_FORMAT='boto.s3.connection.OrdinaryCallingFormat'. It works for me.

**Comment by pydolan** [comment]
+1 for this. Or at least add a note to your README file since the original documentation refers to an S3 module that your repo doesn't have.

**Comment by brianbaquiran** [comment]
The following settings worked for me. I'm in region ```ap-southeast-1``` (Singapore). 
```
AWS_STORAGE_BUCKET_NAME = 'bucket.with.dots'
AWS_S3_CALLING_FORMAT='boto.s3.connection.OrdinaryCallingFormat'
AWS_S3_HOST = 's3-ap-southeast-1.amazonaws.com'
```

Python 2.7.10
Django 1.9

**Comment by jleclanche** [comment]
@jschneier This issue is fixed in s3boto3 (we used a bucket with dots on it for a long time). I'd like to suggest closing it and recommend s3boto3 backend instead.

**Comment by jschneier** [comment]
@jleclanche thanks. Will do so in the future.
