### ISSUE TITLE
Files are upload to S3 when a database error occurs

### ISSUE THREAD

**Issue by samamorgan** [jschneier/django-storages#1301]
I suspect this may be outside the scope of this package, I'm not fully versed on Django storage backends.

I'm running tests for a model I've create that contains a constraint. The model looks something like this:

```python
def _upload_to(instance, filename):
    try:
        prefix = instance.user_1.id
    except AttributeError:
        try:
            public_key = instance.user_2.id
        except AttributeError:
            logger.error(f"Resource {instance.id} has no owner")
            prefix = "resource-no-owner"

    return str(Path(prefix, filename))


class Resource(BaseModel):
    file = models.FileField(upload_to=_upload_to)
    user_1 = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True
    )
    user_2 = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True
    )

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=(
                    models.Q(user_1__isnull=True, user_2__isnull=False)
                    | models.Q(user_1__isnull=False, user_2__isnull=True)
                    | models.Q(user_1__isnull=False, user_2__isnull=False)
                ),
                name="user1_or_user_2",
                violation_error_message="At least one user must be set.",
            )
        ]
```

When I save this model with no associated users, I get an `IntegrityError` as expected (constraint violation). However, the file still uploads to S3.

**Comment by jschneier** [comment]
Usual advice would be to use a different settings file for tests which I echo here.

**Comment by samamorgan** [comment]
> Usual advice would be to use a different settings file for tests which I echo here.

This doesn't address the issue. Sure, I'm encountering this issue in tests, but that isn't the problem at hand.

Files should not be saved to storage if a database error occurs when saving the record.

**Comment by jschneier** [comment]
Not sure I agree but would file a bug with upstream (Django).
