### ISSUE TITLE
AzureStorage fails with valid connection string using shared access signature

### ISSUE THREAD

**Issue by KristofBruyninckxOmina** [jschneier/django-storages#1307]
In version 4.2, additional checks have been added to the initialiser of `AzureStorage`

https://github.com/jschneier/django-storages/blob/d1cd2db41fd3bec01fe97d4b095159f974b91673/storages/backends/azure_storage.py#L132-L134

However, when using a connection string with shared access signature, the account name, and specifically, the account key should be omitted. 

From azure docs https://learn.microsoft.com/en-gb/rest/api/storageservices/delegate-access-with-shared-access-signature:

> A shared access signature (SAS) is a URI that grants restricted access rights to Azure Storage resources. You can provide a shared access signature to clients **who should not be trusted with your storage account key but whom you wish to delegate access to certain storage account resources**. By distributing a shared access signature URI to these clients, you grant them access to a resource for a specified period of time.

Because of the additional checks, a connection string that worked fine on v1.13.2 now fails on v1.14

**Comment by jschneier** [comment]
Thanks for the report, the fix is now going in.
