### ISSUE TITLE
`closed` is True right after opening a `S3File`

### ISSUE THREAD

**Issue by ahumeau** [jschneier/django-storages#1310]
Hey there!

### Description

After updating to 1.14 I encountered the following issue:

```python
storage = S3Storage(bucket_name="my-bucket")
file = storage.open("my-file")
file.closed
> True  # Should be False
```

### Analysis

I pinpointed the issue to commit https://github.com/jschneier/django-storages/commit/af91e2ca2d7f7f77541701a499fd4ef5065d0141.

The issue it fixes is perfectly legitimate but the way it fixes it introduces this bug.

`S3File` implements some kind of lazy opening by leveraging the `file` property (and its `_get_file` accessor). The file is not actually opened until the `file` property is first accessed, `self._file` remains `None` until then.
With the current `closed` implementation, `self._file` being `None` results in `closed` returning `False` even though in this case the file was never closed, it was never even read from.

### Proposed fixes

I see two approaches:
- keeping track of whether a `S3File` is opened of closed through a `_closed` attribute (for example), setting it to `True` in `S3File.__init__`, to `False` in `S3File.close` and reading it in `S3File.closed`
- forcing `_file` to be defined by calling `f.file` in `S3Storage._open`

I have no idea which is better (might be another approach altogether).

NB: might be related to https://github.com/jschneier/django-storages/issues/1308

**Comment by jschneier** [comment]
Thanks for the comprehensive report, will look into this

**Comment by ahumeau** [comment]
Thanks @jschneier !
