### ISSUE TITLE
django-storages generates invalid Google Cloud Storage URL

### ISSUE THREAD

**Issue by Symmetric** [jschneier/django-storages#132]
Using v1.3.2, if the URL of an object is `''`, then `apache_libcloud.py` 'fixes' it to `.`, which gives a 302 on Google's API.

Example:

```
container_name = 'monolith-staging'
object_name = '.'
object_path = '/monolith-staging/.'
```

The 302 from Google's API is to `/monolith-staging/`, and this is being changed in apache_libcloud.py:60:

```
    def _clean_name(self, name):
        """Clean name (windows directories)"""
        return os.path.normpath(name).replace('\\', '/')
```

I suspect the fix is to either need to stop cleaning URLs of this form, or to understand the 302 and follow it.

**Comment by jschneier** [comment]
Sorry, I'm having problems following your logic for what is happening where.

Are you saying the issue is that `clean_name(self, name)` takes a name of the form `/monolith-staging/.` and transforms it to `/monolith-staging`?

**Comment by Symmetric** [comment]
Sorry for the delay.

If you generate a URL using django's template method thusly: 

`{% static '' %}` 

then the generated Google Cloud Storage path is 

`/<bucket-name>/.`

This is because the path after the /<bucket-name>/ section is passed through `clean_name()`.

Google Cloud Storage does not accept the generated path; it returns  a 302 to `/<bucket-name>/`. I've verified that hacking the `clean_name` function to strip the trailing `.` fixes the problem.

**Comment by thongly** [comment]
Is there a pull request or release that closes this?
