### ISSUE TITLE
Custom storage backend in Django>=4.2?

### ISSUE THREAD

**Issue by TheGardenMan** [jschneier/django-storages#1327]
I want to create custom storage backends so that I can store media and static files in two different buckets.
[Doc](docs/backends/amazon-S3.rst) for S3 says,I should specify the backends in `OPTIONS` but I can't understand the example.
If I want to store media files in one bucket and static in another, how should I do it?
Any links to tutorial or an example is appreciated!
Thank you!

**Comment by jschneier** [comment]
Here's what you'd do inside of settings

```python
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
          ...your_options_here
        },
     },
     "staticfiles": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
          ...your_options_here
        },
     },
}
```

Where `default` handles the media files and you can set the options for each separately. Hope that helps, let me know if you have any further questions. 

This same info is also available in the [Django docs](https://docs.djangoproject.com/en/4.2/ref/settings/#storages).

**Comment by TheGardenMan** [comment]
Thank you for responding quickly!
Where should I specify the different bucket names?

**Comment by jschneier** [comment]
In `OPTIONS`, each setting is documented [in the docs](https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#settings).

So for the media file bucket you'd do

```
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": "$NAME_OF_MEDIABUCKET",
            ...other_options_here
        },
     },
```

etc.

**Comment by TheGardenMan** [comment]
Thank you that worked!
