### ISSUE TITLE
An error occurred (RequestTimeTooSkewed) when calling the PutObject operation: The difference between the request time and the current time is too large.

### ISSUE THREAD

**Issue by sowinski** [jschneier/django-storages#1332]
Hi,

any idea what I can do?

Getting this error after daylight saving time entered in Europe?

`An error occurred (RequestTimeTooSkewed) when calling the PutObject operation: The difference between the request time and the current time is too large.`

Thank you

**Comment by jschneier** [comment]
Yikes, sorry to hear. Are you setting any additional params that might cause this to manifest due to this library? At first glance it's hard for me to believe that this isn't an AWS problem but obviously we are adding a bunch of software in there as well.

**Comment by sowinski** [comment]
```
class BillFileStorage(S3Boto3Storage):
    access_key = settings.MY_AWS_S3_BILLS_STORAGE_ACCESS_KEY
    secret_key = settings.MY_AWS_S3_BILLS_STORAGE_SECRET_KEY
    bucket_name = settings.MY_AWS_S3_BILLS_STORAGE_BUCKET_NAME
    location = ''
```

```
TIME_ZONE = 'Europe/Berlin'

USE_I18N = True
USE_L10N = True

USE_TZ = True
```

I updated to the latest django-storages version and also updated to the latest boto3 version => same problem :(

**Comment by sowinski** [comment]
I found my bug ... I did not see that my class has @freeze_time("2022-03-30") annotated at the top ... Just weird that this error appeared yesterday and not earlier ...
