### ISSUE TITLE
collectstatic is not overriding changed files

### ISSUE THREAD

**Issue by matheusjardimb** [jschneier/django-storages#134]
collectstatic is not overriding changed files and it's related to changed date of files and timezone.
I found this issue https://bitbucket.org/david/django-storages/issues/167/collectstatic-is-not-overwriting-changed and someone recently complained about it too.

Files only get updated when I "touch" them in order to modify it's changed date to some day in the future.

I seems S3 is not sending proper changed date or the algorithm is not considering timezone

**Comment by dcloud** [comment]
This looks like a duplicate of #49 (which references pr #84, fwiw).

**Comment by jschneier** [comment]
Dupe #49, going to probably implement Django 1.10s logic for backward compat or else simply allow the new 1.10 api to take care of this,
