### ISSUE TITLE
Django 5 support

### ISSUE THREAD

**Issue by Mapiarz** [jschneier/django-storages#1350]
Does the latest django-storages support Django 5? If not, what needs to happen?

**Comment by santanu2310** [comment]
Yes it support Django 5.
But the django [STORAGES](https://docs.djangoproject.com/en/5.0/ref/settings/#storages) was not working properly(speacialy, I can't manage to make the collectstatic to copy the static files to awsS3).
Your can use is perfectly using the old way.

**Comment by TreyWW** [comment]
How come django's "STORAGES" variable no longer works? I've spent the last hour trying to set this up and it just doesn't work. But I need media and static to have different settings so it's kind of a pain. Any note when this will be fixed or any active issues on this?

**Comment by jschneier** [comment]
The project is active-ish but the nice part of `STORAGES` is that it doesn't actually require an update to this library. For certain settings yeah I guess I should do a release but broadly speaking, it should work.

**Comment by TreyWW** [comment]
Ah I see, thanks for clearing that up @jschneier!
I managed to solve my issue by using a subclass of s3storage rather than storages variable. Might be nice to update the docs with that too, took a while to figure out. I can make a PR if you wish. Let me know :)

**Comment by im-n1** [comment]
@TreyWW can you give us please an example how did you subclass?

**Comment by TreyWW** [comment]
Sure thing. Our settings our here: https://github.com/TreyWW/MyFinances/blob/main/settings/settings.py#L245
