### ISSUE TITLE
subdomain url dosent work with ftp method

### ISSUE THREAD

**Issue by hadibeiki** [jschneier/django-storages#1354]
i use django-storages for upload my file to download host domain.
the file uploaded correctly but the url of file in template is not coorect. 
my MEDIA_ROOT and MEDIA_URL is like this:

MEDIA_URL = 'dl.example.com/'
MEDIA_ROOT = 'dl.example.com'

my main domain is www.example.com and my download domain is dl.example.com
when i go to my website the src of the images is "https://example.com/en/dl.example.com/..."

how can i fixed with correct url!?

**Comment by jschneier** [comment]
In the docs you can adjust `BASE_URL` to make it work; how are you using `.url()`?
