### ISSUE TITLE
Django Admin static files with wrong URL (`None` value in URL) google-storage backend

### ISSUE THREAD

**Issue by AndreLobato** [jschneier/django-storages#1369]
I notice this only for the static files for the Django Admin site. All other static files and media URLs seems fine as they return the right URL.

After running `./manage.py collectstatic` (success) then `./manage runserver`...

Go to Admin site and all the Static files URLs will be as such:

`https://storage.googleapis.com/None/admin/css/base.css?X-Goog-Algorithm=...`

returning 400.

while the expected would be: `https://storage.googleapis.com/{bucket_name}[/{location}]/admin/css/base.css?X-Goog-Algorithm=...`

I have only tried with signed URLs as well.

Versions:
```
Django==5.0.1
django-storages==1.14.2
google-api-core==2.15.0
```

**Comment by varus17** [comment]
Facing the same issue with Django 4.2.
Migrated from the older `STATICFILES_STORAGE` to the updated `STORAGES`, and the `bucket_name` option does not seem to be passed to the storage backend.

**Comment by jschneier** [comment]
It sounds like there is maybe an upstream behavior change. Can people confirm they have `django.contrib.staticfiles` in `INSTALLED_APPS`?

https://github.com/django/django/blob/main/django/templatetags/static.py#L126-L129

**Comment by AndreLobato** [comment]
I confirm I do have `django.contrib.staticfiles` in `INSTALLED_APPS`

**Comment by jschneier** [comment]
Can you share a bit more details? I strongly suspect you are hitting the comment on this bug that was fixed. In short, are you on 4.2.5+ and also do you have another package that hasn't transitioned to the new STORAGES setting?

https://code.djangoproject.com/ticket/34773#comment:3

**Comment by AndreLobato** [comment]
Ok, thanks for the pointers. I will have another go at this issue and will fill with more details, it's very possible I am using another lib which has not transitioned to new settings.

**Comment by jschneier** [comment]
Please reopen when there is more data, I simply cannot reproduce this or related issues.

**Comment by AndreLobato** [comment]
For some reason this is no longer an issue here. Thanks!
