### ISSUE TITLE
New behaviour of S3 storage `exists()` breaks current workflow

### ISSUE THREAD

**Issue by saemideluxe** [jschneier/django-storages#1429]
In our application, we allow overwriting large files on S3 (so, having `file_overwrite=True`). We were relying on the existing behavior of `myfile.storage.exists(myfile.name)` to render urls or a null-character. With the new check introduced in #1422 this behaviour breaks. The file has been generated and uploaded, but our template will not render the link, as it thinks the file does not exist.

Are we doing the check for exists wrong? I am happy to fix my own code, but in case this is an unforeseen side effect of #1422 I would like to report it here.

Also, thanks for all your work on this library, it makes working with S3 very easy!

**Comment by violuke** [comment]
This will break things for anyone (like me) using [django-health-check](https://github.com/revsys/django-health-check/blob/b0e2c4c6157bd57b11c02b5f26e26ca3d2322fd4/health_check/storage/backends.py#L56).

**Comment by jschneier** [comment]
Let's centralize discussion on #1430. Thanks for opening and apologies. I've posted my reasoning there but am open to reverting.
