### ISSUE TITLE
Commit a531947 breaks ManifestFilesMixin storages

### ISSUE THREAD

**Issue by TheEnbyperor** [jschneier/django-storages#1436]
Storage backends that use `ManifestFilesMixin` (e.g. `S3ManifestStaticStorage`) break on the new behaviour of `exists()` introduced in commit a531947.

The `hashed_name` function on the mixin first calls `exists()`, but this is now always False when overriding files is enabled, thus breaking the mixin.

**Comment by jschneier** [comment]
Dupe #1430
