### ISSUE TITLE
Getting "The file  could not be found" when using S3ManifestStaticStorage

### ISSUE THREAD

**Issue by dalpii** [jschneier/django-storages#1440]
Hello guys, I hope someone can help me. I've implemented the default `storages.backends.s3.S3Storage` for uploads and static files, and it went just fine.

Now I'm trying to setup static files to use `storages.backends.s3.S3ManifestStaticStorage` and I'm getting an error when running with `DEBUG = False`, on production:

```
ValueError: The file 'admin/css/widgets.css' could not be found with <storages.backends.s3.S3ManifestStaticStorage object at 0x750f4d2ba750>.
```

As you can see, it doesn't seem to be able to find a CSS file from Django admin, but checking my bucket, the file is there:
 
<img width="1306" alt="Captura de Tela 2024-08-06 às 17 41 16" src="https://github.com/user-attachments/assets/27685983-6054-4d16-b190-d2c1d7a61040">

And my bucket policy, which was working just fine with S3Storage:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::bucket-name/*"
        }
    ]
}
```

I've tried some approaches/tests with no success, maybe it's some race condition?

Thanks!

**Comment by dalpii** [comment]
Maybe not a race condition because running the command again, without deleting any file from S3, gives the same error.

All files are inside `admin/css/`:

<img width="911" alt="Captura de Tela 2024-08-06 às 17 49 52" src="https://github.com/user-attachments/assets/b5cecfb6-5761-41b4-aa2f-2210bc5ad126">

**Comment by lchojnacki** [comment]
I encountered a very similar problem in my project (`ValueError: The file 'admin/img/sorting-icons.svg' could not be found with <my.custom.storage.Class(S3ManifestStaticStorage)>.`). Downgrading `django-storages` to version 1.14.2 helped.

**Comment by temi4** [comment]
Hello. 

Problem after the update, because the logic of the self.file_overwrite parameter in the function "exists" has changed

def exists(self, name):
 if self.file_overwrite: <!-- add this
 return False

And this function is used in HashedFilesMixin
https://github.com/django/django/blob/a57596e443ecb67140e1a9fc0f0e87446b2d0174/django/contrib/staticfiles/storage.py#L142

**Comment by dalpii** [comment]
I'm closing this issue because this error is caused by #1430.
As @lchojnacki  and @temi4 pointed out, downgrading or changing the `exists` function on storage works for now.

**Comment by chorvitz-medicircle** [comment]
+1, it is making S3ManifestStaticStorage unusable.
