### ISSUE TITLE
no matches found: django-storages[s3]

### ISSUE THREAD

**Issue by DataGreed** [jschneier/django-storages#1441]
When following the [installation guide for s3](https://github.com/jschneier/django-storages/blob/master/docs/backends/amazon-S3.rst), I try to install it and get an error saying th package does not exist:

```
% pip install django-storages[s3]
zsh: no matches found: django-storages[s3]
```

My env: 
- macos 14.3
- pip 24.2
- Python 3.9.6

**Comment by jschneier** [comment]
Can you try with quotes?

**Comment by DataGreed** [comment]
@jschneier 
```
pip install "django-storages[s3]"
```

this actually worked! Had no idea there might even be a difference.

Thanks, I think it's worth reflecting this in the docs

**Comment by jschneier** [comment]
Fascinating, this is a zsh problem. Works fine in both bash & fish.
