### ISSUE TITLE
Every ImageField.url() call ends up making unnecessary requests to S3 resulting in performance issues.

### ISSUE THREAD

**Issue by DataGreed** [jschneier/django-storages#1442]
When using S3 as media and/or static file backend on Django 4.2, and listing file urls to the end user, django-storages makes lots of requests to s3 which causes performance issues (and quota issues on AWS side). This happens even with `querystring_auth=False` (although I am not sure why it should make these requests even with this option set to true – cloudfront signing doesn't require this, why s3 does?)

My current workaround (not sure if it eliminates all of the additional requests): 
`I've set STORAGES.[backend].OPTIONS.custom_domainto[my_bycket].s3.amazonaws.com` and it stopped spamming with requests.

More info in this thread: https://github.com/jschneier/django-storages/issues/692#issuecomment-2283007198

**Comment by avilaton** [comment]
Also seeing this and being impacted by it, we have the impression that if querystring_auth is set to false then there should be an earlier exit from the method. Adding a sentry trace to have more data
![image](https://github.com/user-attachments/assets/aa19e701-1318-491e-b62a-9d7c33e89a6e)
<img width="701" alt="image" src="https://github.com/user-attachments/assets/6c65ed58-eaf9-45dd-bb59-57f0a9b4957b">

**Comment by jschneier** [comment]
The method `_strip_signing_parameters` is no longer in the code base.

**Comment by avilaton** [comment]
This is fixed thanks and sorry @jschneier , we got the update through dependabot while we looked for solutions elsewhere.
