### ISSUE TITLE
S3 credentials in links missing for private buckets after upgrade to Django 5.1

### ISSUE THREAD

**Issue by GitRon** [jschneier/django-storages#1443]
Hi @jschneier!

I found an issue with Django 5.1. After the upgrade (using django-storages 1.14.4), all GET-parameter credentials for private S3 buckets are not being added to the links in my templates anymore. This means that I don't have access to the files.

I have no idea and since I have little knowledge on how this amazing package works, I can't really contribute any suggestions. 😔 I just verified that it's really Django 5.1.

Here's my setup, it might help in reconstructing the case.

```python
from django.conf import settings
from storages.backends.s3boto3 import S3Boto3Storage


class PrivateMediaStorage(S3Boto3Storage):
    location = settings.AWS_PRIVATE_MEDIA_LOCATION
    querystring_expire = 3600  # seconds until the generated link expires
    default_acl = "bucket-owner-full-control"
    file_overwrite = False
    custom_domain = False
```

Thanks so much for looking into this!  
Ronny

PS: It seens unrelated to https://github.com/jschneier/django-storages/issues/1437 since there, Django 4.2 was used.

**Comment by christoph-teichmeister** [comment]
I've also run in this issue :/

**Comment by rory-ferguson** [comment]
Maybe this is related to https://docs.djangoproject.com/en/5.1/releases/5.1/#features-removed-in-5-1

```
The DEFAULT_FILE_STORAGE and STATICFILES_STORAGE settings is removed.
The django.core.files.storage.get_storage_class() function is removed.
```

**Comment by kylepollina** [comment]
5.1 has also caused issues with `AWS_S3_CUSTOM_DOMAIN`, not sure what the deal is. With django 5.0 + django rest, when desearializing a model with an image/file field, the key was prepended with whatever value was set for `AWS_S3_CUSTOM_DOMAIN`, however after the upgrade it seems to default to the hostname. 

For example, if I set `AWS_S3_CUSTOM_DOMAIN` in my `settings.py` file to be `www.test.com`

<img width="294" alt="Screenshot 2024-08-20 at 9 58 28 PM" src="https://github.com/user-attachments/assets/bbcd7bea-6491-4554-bcc1-9a3ae233fb2c">


on django==5.0 imagefield deserialization returns `http://www.test.com/organizations/0a72d97f-974c-4828-85b1-0276a6c6cf2e/images/m22_ms.png`

<img width="793" alt="Screenshot 2024-08-20 at 9 56 52 PM" src="https://github.com/user-attachments/assets/26563ef2-cb3d-48ca-9f18-6c1aae841e93">


But on django==5.1 imagefield deserialization returns `http://localhost:8000/organizations/0a72d97f-974c-4828-85b1-0276a6c6cf2e/images/m22_ms.png`

<img width="793" alt="Screenshot 2024-08-20 at 9 57 22 PM" src="https://github.com/user-attachments/assets/3688cf62-348c-4026-b2f9-c481352aa439">

**Comment by kylepollina** [comment]
Upon further inspection it looks like the newer version of django is totally overwriting the storage backend. I was debugging a bit and found that the variable stored here: 

https://github.com/django/django/blob/main/django/db/models/fields/files.py#L25

Used to be pointing to the s3 storage backend, but after upgrading it just pointed to the default django filestorage backend

**Comment by rory-ferguson** [comment]
Hi @kylepollina, You might of missed the django-storages config change

https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#configuration-settings

This changed for django 4.2

**Comment by GitRon** [comment]
@rory-ferguson Thanks for the investigation, we didn't use the new `STORAGE`. I'll try it out and report back.

**Comment by kylepollina** [comment]
@rory-ferguson  Thank you! I updated my configurations and this fixed my issue.

**Comment by GitRon** [comment]
Seems to work here, too. Should this be documented somewhere? 🤔

**Comment by kylepollina** [comment]
@GitRon  it is documented on the bottom of the Django 5.1 release notes. https://docs.djangoproject.com/en/5.1/releases/5.1/ 

> The DEFAULT_FILE_STORAGE and STATICFILES_STORAGE settings is removed.

**Comment by GitRon** [comment]
@kylepollina You are right! Still don't get it, why it works 😆 Well, maybe really not a storages-problem 🤷‍♂️ On the other side, explicit is better than implicit. I'll leave it to the maintainers to decide this.

Thanks for the support everyone ❤️

**Comment by Hassan-Butt4356** [comment]
@kylepollina The DEFAULT_FILE_STORAGE and STATICFILES_STORAGE settings have been removed. What alternative settings can we now use to configure an S3 bucket for handling image uploads?

**Comment by kylepollina** [comment]
@Hassan-Butt4356  you will have to set your `STORAGES` variable to something like

```python
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
```

**Comment by aldisjointed** [comment]
This could be your answer



https://github.com/angular/angular.js
