### ISSUE TITLE
Opinion on Django enhancement to add `encoding` arg to `Storage.open()`

### ISSUE THREAD

**Issue by jacobtylerwalls** [jschneier/django-storages#1447]
Over at the Django forum @whatisgalen [suggested](https://forum.djangoproject.com/t/enable-default-storage-to-pass-kwargs-to-python-open/34045/3) adding an `encoding` kwarg to `Storage.open()`, and there was at least one positive initial response paired with a recognition that it would be good to know if there would be buy-in from the major storage backends.

Would django-storages be likely to implement an encoding kwarg if it was added to the interface for `Storage.open()`?

Thanks.

**Comment by jschneier** [comment]
Would accept tested PRs implementing this, yes.
