### ISSUE TITLE
Any interest for Ceph, Swift, and Riak storage systems?

### ISSUE THREAD

**Issue by mbasaglia** [jschneier/django-storages#148]
I have a few storage back-ends to contribute, for the following storage systems:
* [Ceph](http://docs.ceph.com/docs/master/)
* [Swift](http://docs.openstack.org/developer/swift/)
* [Riak](http://basho.com/products/#riak)

If there is any interest on any of them I can start working on making sure they are suitable for merging and create pull requests.

**Comment by jschneier** [comment]
I am considering making a general django-storages org which we can use as the general clearinghouse of well-supported storage backends.

See [this issue](https://github.com/jschneier/django-storages/issues/202). Will re-ping when I have some time to get that off the ground. Thanks for your interest.

**Comment by einarf** [comment]
@mbasaglia https://github.com/blacktorn/django-storage-swift in case you missed it

**Comment by barseghyanartur** [comment]
@mbasaglia, @jschneier:

Four years later, are you aware of packages offering Ceph storage backend in Django? :)
