### ISSUE TITLE
Questionable s3boto call stack

### ISSUE THREAD

**Issue by cancan101** [jschneier/django-storages#150]
Does this look right that calls are being made (to S3) in both the `s3boto.py::_open` method and in  `s3boto.py::_get_file` method? Each is taking rough the same amount of time.
![image](https://cloud.githubusercontent.com/assets/51059/15400972/92d4f62c-1dbb-11e6-85d8-07d279458022.png)
It my code I am just calling `data.open(mode='rb')`.

Currently on `django-storages-redux==1.3.2`.

**Comment by cancan101** [comment]
This issue _might_ have been fixed in: https://github.com/django/django/commit/a52a531a8b34f049fba11c3ee7b010af7534bf90

**Comment by derek-adair** [comment]
You're using a deprecated project.  For a while this project was publishing to django-storages-redux, but the owner of this repository has taken over the django-storages namespace.

**Comment by derek-adair** [comment]
https://pypi.python.org/pypi/django-storages/1.4.1

**Comment by cancan101** [comment]
I upgraded to stages 1.4.1 and see the same issue.

**Comment by jschneier** [comment]
`_get_file` caches the file so this is fine.
