### ISSUE TITLE
Box Integration

### ISSUE THREAD

**Issue by AdrianCzebiniak** [jschneier/django-storages#156]
I am looking to integrate Box as a storage and would like to leverage your framework.  Are you interested in merging this and do you have any suggestions?

**Comment by jschneier** [comment]
Hey, the Django docs are a good place to start. The [documented api](https://docs.djangoproject.com/en/1.10/ref/files/storage/) is fairly self-explanatory. I'm thinking of making an organization or similar in the future to reduce maintenance burden/slim down the repository.

Not 100% certain if I'd take a Box implementation but I encourage you to give it a spin yourself, it's not too hard.
