### ISSUE TITLE
Exclude model to store media file to S3

### ISSUE THREAD

**Issue by Keda87** [jschneier/django-storages#157]
Hi, is it possible to exclude some models that contains media file? because I don't want to store some of my data on S3.

**Comment by jschneier** [comment]
Hey [in the docs](https://docs.djangoproject.com/en/1.10/ref/models/fields/) if you search for `.storage` you'll see that you can configure which storage is used on an individual field basis. The default will be to use whatever is configured in `DEFAULT_FILE_STORAGE`.
