### ISSUE TITLE
S3BotoStorage + 'a' mode: Consider either supporting or throwing NotImplementedError

### ISSUE THREAD

**Issue by rapilabs** [jschneier/django-storages#166]
It looks as though the file mode 'a' is not yet supported.  I'm assuming that boto/s3 doesn't support this?

It might be an idea to implement by reading & writing back to S3 manually, but possibly better to throw a NotImplementedError so that developers are aware of the limitation and can choose the best alternative.

**Comment by rapilabs** [comment]
Submitted PR #167

**Comment by jschneier** [comment]
I don't think append mode makes much sense in a remote file situation, especially one like S3. So I'm going to go ahead and say no, sorry.

**Comment by mrmachine** [comment]
@jschneier An exception would have been handy. I didn't realise S3 doesn't support append mode, and had to spend some time digging around trying to figure out why it wasn't working.
