### ISSUE TITLE
SFTP tutorial

### ISSUE THREAD

**Issue by albertolina** [jschneier/django-storages#168]
Could you please provide a tutorial or a much more deep documentation for the SFTP implementation ?

**Comment by albertolina** [comment]
How do I pass the sftp username and password ? Please respond

Thank you

Albert

**Comment by jschneier** [comment]
Hi - documentation has been a source of continual embarrassment for me, I hope to improve it when I get the chance.

To answer your second question you can define a settings variable `SFTP_STORAGE_PARAMS` which is a dictionary that are used as part of the connection. You can set them there.

So in `settings.py` you would do...
```python
SFTP_STORAGE_PARAMS = {'username': 'THE_USERNAME', 'password': 'THE_PASSWORD'}
```

Hope that helps. Going to close this for right now, let me know if I should reopen.

**Comment by jamalroger** [comment]
hi guys i have the same issue 
i can't upload file over sftp  how does exactly works ??
