### ISSUE TITLE
Azure Storage

### ISSUE THREAD

**Issue by MIKNOTAURO** [jschneier/django-storages#170]
azure-storage has a new release (0.32) and has many changes that makes incompatible with the latest version of django-storages

**Comment by k0nG** [comment]
Addressed in this PR: https://github.com/jschneier/django-storages/pull/211

While that hasn't been merged, just as a note for anyone like me who is having trouble getting the current azure storage backend to work with the Azure sdk. I've got it working with version 1.0.3: https://github.com/Azure/azure-sdk-for-python/tree/v1.0.3

**Comment by edevil** [comment]
I just came across this lib and ticket. So the current status on Django storage on Azure is that it's not working?

**Comment by jschneier** [comment]
Hello, would like to push the Azure support forward into modern times. The current library will break with the Azure sdk for Python in the next month because it will transition into 0.34 being on it. The other PR is close.

**Comment by sww314** [comment]
Fixed in #565
