### ISSUE TITLE
requests not being signed after switching to a cdn backed by an s3 bucket

### ISSUE THREAD

**Issue by dacrowlah** [jschneier/django-storages#18]
I had this working just fine when I used my-bucket-name.s3.amazonaws.com/ as the default storage for my site.  Last night I set up CloudFlare to proxy the requests through.  In doing this you do the following:
- create a bucket name that matches the CNAME you want to serve through (cdn.mysite.com) so that the url would be cdn.mysite.com.s3.amazonaws...... 
- in the CloudFlare DNS panel, you setup a CNAME for cdn.mysite.com to redirect to cdn.mysite.com.s3.amazonaws.com 
- presto, magic works.

however, when it was using my-bucket-name.s3, it django was automatically signing all of the requests for the content, which I want it to do... but when I switched to the cdn, it stopped, and I had to open the bucket up to public viewing, which I do not want.

**Comment by dacrowlah** [comment]
FYI: I'm using Python 3.4, django 1.7.1

**Comment by jschneier** [comment]
Hi @dacrowlah and thanks for the report! What version of 3.4 are you using and do you have a traceback? I'm wondering if this is related to #13 which references an upstream boto bug. Depending on the traceback switching your CallingFormat might fix this issue. More information would be great!

**Comment by dacrowlah** [comment]
I haven't seen any tracebacks/exceptions. Pardon, but this is my first
django app, and I haven't seen a log file anywhere (tho I imagine its there
somewhere). I'm running in debug mode, and dont see anything.

**Comment by jschneier** [comment]
Dupe #456 I did not understand the question at the time.
