### ISSUE TITLE
Consider joining the Jazzband for help maintaining project?

### ISSUE THREAD

**Issue by dcloud** [jschneier/django-storages#186]
I know it isn't my place to suggest, but there is a Github organization, @jazzband, organized around helping developers share responsibilities for development and maintenance of open source projects. They house other fine Django projects such as django-debug-toolbar and django-pipeline, so I thought django-storages might be a good fit.

**Comment by jschneier** [comment]
I am aware of jazzband. It's an interesting idea and one I will probably move towards eventually. Not yet though, thanks for brining it up!

**Comment by browniebroke** [comment]
Hi @jschneier, do you still have time to look after this project? Do you still use it? I wanted to offer help or suggest moving this to an organisation like @dcloud suggested.

Would now be a good time to re-evaluate this idea?
