### ISSUE TITLE
[Question] How to switch default_acl for a common image field?

### ISSUE THREAD

**Issue by jerinseba** [jschneier/django-storages#198]
Hi, Is it possible to switch default_acl during file upload for a common field? I would like to upload images as 'public-read' for public accounts and 'authenticated-read' for private accounts. I saw an option to override settings globally using AWS_DEFAULT_ACL. But, it didn't serve my purpose.

**Comment by coredumperror** [comment]
Try something like this:

```python
class S3PrivateFileField(models.FileField):
    """
    A FileField that gives the 'private' ACL to the files it uploads to S3, instead of the default ACL.
    """

    def __init__(self, verbose_name=None, name=None, upload_to='', storage=None, **kwargs):
        if storage is None:
            storage = S3Boto3Storage(acl='private')
        super(S3PrivateFileField, self).__init__(verbose_name=verbose_name,
                name=name, upload_to=upload_to, storage=storage, **kwargs)
```

This specific code won't work for your needs, but you should be able to modify it to get a different ACL depending on the currently logged-in User. Then, instead of putting a FileField in your model, use one of these.
