### ISSUE TITLE
Maintenance Plan Going Forward

### ISSUE THREAD

**Issue by jschneier** [jschneier/django-storages#202]
I'm going to deprecate and shortly remove the following backends:

[hashpath](https://github.com/jschneier/django-storages/blob/master/storages/backends/hashpath.py)
[image](https://github.com/jschneier/django-storages/blob/master/storages/backends/image.py)
[overwrite](https://github.com/jschneier/django-storages/blob/master/storages/backends/overwrite.py)
[symlinkorcopy](https://github.com/jschneier/django-storages/blob/master/storages/backends/symlinkorcopy.py)
[database](https://github.com/jschneier/django-storages/blob/master/storages/backends/database.py)
[mogile](https://github.com/jschneier/django-storages/blob/master/storages/backends/mogile.py)
[couchdb](https://github.com/jschneier/django-storages/blob/master/storages/backends/couchdb.py)

I just created a new organization and am considering various plans going forward. The azure backend for example needs a full rewrite and I don't have the time, need or expertise to do so.

If you'd be interested in maintaining a separate package for each individual backend underneath the organization or have a different plan I'd be open to hearing them.

**Comment by jibaku** [comment]
Why not using the jazz band organization ? https://jazzband.co

**Comment by ZuluPro** [comment]
@jibaku , I have been thought to JazzBand, but django-storage needs to be more stable before submission.

**Comment by jschneier** [comment]
Yes, too many lingering issues from the lack of maintenance for too long.

**Comment by ZuluPro** [comment]
@jschneier 
About split this project into several ones:
I thought about the following things: Keep django-storages as a core package for others, it could contains:
- Common code
- Documentation about all
- An enhanced base Storage class that allow overwrite or not for example
- A functional test suite checking all operations

What do you think about ?

**Comment by einarf** [comment]
For those who mentioned a swift backend I have been contributing to:
https://github.com/blacktorn/django-storage-swift

Writing that from scratch is not fun :)

**Comment by bittner** [comment]
Please, don't forget to update the entry of this package on [Django Packages](https://djangopackages.org/grids/g/storage-backends/). It still refers to [David Larlet's original repository](https://bitbucket.org/david/django-storages/src/).

Also, having David update the README of his repository and ideally [clean up issues](https://bitbucket.org/david/django-storages/issues/208/new-release) and pull requests would be nice, too. It's a bit hard to figure out what the state of this project really is, at first sight.

**Comment by srgrn** [comment]
Hi, 
As i just had some issues and fixed them (haven't created tests yet and that is why they aren't in a pull request)
I would like to help to revamp the azure backend 
and wondered if there is an organization yet or is it something to be done in the future?

**Comment by jschneier** [comment]
Okay, I'm going to merge in removing the deprecated ones. For the remaining I think of them in 2 groups, cloud & filesystem (ftp/sftp). For the cloud ones I am working on a unified base for all of them. Will reach out for help on the particular ones I need help with. Happy to finally pull the trigger on this one.
