### ISSUE TITLE
Checking my  credentials

### ISSUE THREAD

**Issue by MrJeric0** [jschneier/django-storages#207]
i get this exception

> boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials

im sure i put my credentials right, and the buckets are set up. Any recommendations?

**Comment by jschneier** [comment]
Can you double check your credentials and copy/paste an anonymized copy of your creds.

**Comment by MrJeric0** [comment]
i got it to work. Thanks for the reply
