### ISSUE TITLE
Anyone can help me ? I am not able to upload any file from Django Admin which is in media folder on aws

### ISSUE THREAD

**Issue by mynksngh** [jschneier/django-storages#209]
S3ResponseError: 400 Bad Request
Request Method: POST
Request URL:    http://127.0.0.1:9000/admin/xxx/pxxlxxxicy/23222/
Django Version: 1.8
Exception Type: S3ResponseError
Exception Value:  
S3ResponseError: 400 Bad Request
Exception Location: /home/devlp/mayank/dev/local/lib/python2.7/site-packages/boto/s3/bucket.py in _get_key_internal, line 231
Python Executable:  /home/devlp/mayank/dev/bin/python
Python Version: 2.7.6

**Comment by ZuluPro** [comment]
Could you give us the full traceback ?

**Comment by jschneier** [comment]
Closing without more information.
