### ISSUE TITLE
About 'get_available_name' signature

### ISSUE THREAD

**Issue by ihhcarus** [jschneier/django-storages#212]
Hello all,

As I was investigating how to avoid S3 Boto storage to reuse files with the same name (and keep default Django's name generation policy) I found the `file_overwite` parameter in the storage and imagined that was a good clue to solve this situation.

Setting that to `False` and running my tests I received a `TypeError` at `S3BotoStorage`'s `get_available_name` function that indicated a superclass call with 3 arguments instead of the 2 required.

Here's the end of the traceback:

```
[...]
File "/Users/buddles/projects/perestroika-site/env/lib/python2.7/site-packages/storages/backends/s3boto.py" in get_available_name
  522.         return super(S3BotoStorage, self).get_available_name(name, max_length)

Exception Type: TypeError at /aulas-online/1/arquivos/
Exception Value: get_available_name() takes exactly 2 arguments (3 given)
```

By looking at the source code, I found that this function has an argument called `max_length` that is not used in the function at all and is only passed to the superclass `Storage` that does not use it too (hence the exception).

So my question is:
- Is there something wrong with the function or that argument was left over and could be removed?

Thanks!

**Comment by ZuluPro** [comment]
Hello @iraupph,

`max_length` has been added in Django 1.8: https://docs.djangoproject.com/fr/1.9/ref/files/storage/#django.core.files.storage.Storage.get_available_name
So it is not yet used but will be.

What is your Django version ?

**Comment by iraupph** [comment]
I see, I'm using Django 1.7 in this project.

Any tips on how to proceed in this situation?

**Comment by jschneier** [comment]
Hey, sorry for the late responses. 1.5.0 was the last version to support Django 1.7 (I need to get better at this versioning game, so many changes in this library given all the different packages and its questionable code quality). So if you use that version you should be okay.

**Comment by Sovetnikov** [comment]
One can monkeypatch Storage.get_available_name method. Seems it's safe in most cases and work in my case with S3 backend.

_get_available_name_orig = None
def _get_available_name_18(self, name, max_length=None):
    return _get_available_name_orig(self, name)
from django.core.files.storage import Storage
_get_available_name_orig = Storage.get_available_name
Storage.get_available_name = _get_available_name_18
