### ISSUE TITLE
S3BotoStorage serializes S3 bucket name kwarg in Django 1.7

### ISSUE THREAD

**Issue by nlundquist** [jschneier/django-storages#22]
The bucket kwarg maybe be a settings variable that changes from deployment to deployment, but the value gets serialized into migrations, corrupting my deployment-agnostic migrations with deployment-specific configuration. 

The bucket argument isn't used during schema migrations, however it could be used during a data migration that affects the given S3BotoStorage FileField. Because of that we can't simply remove the bucket argument from the deconstructed / serialized arguments. 

Instead I propose modifying S3BotoStorage so that it uses a new bucket_alias kwarg instead of bucket, where the value of bucket_alias is a key in a settings dictionary of arbitrary keywords to actual S3 bucket names. This indirection will allow us to serialize bucket definitions in migrations but still independently define the exact buckets used for a given deployment.

This type of issue and solution are the reason databases have aliases in Django.

**Comment by jschneier** [comment]
Hi, that all sounds okay to me. Can you post a small example that demonstrates the issue you're talking about? Even just a snippet of models.py and settings.py should be enough. I don't personally use storages in the way you do so I'd like to be on the same page as you.

**Comment by nlundquist** [comment]
The easiest way to demonstrate the issue with bucket_name being serialized would be something like:

models.py
```python
class TestModel(Model):
    special_file = FileField(
        upload_to=settings.SPECIAL_FILE_PATH,
        storage=S3BotoStorage(
             bucket=settings.S3_BUCKETS['special_file']
        )        
    )
```
settings.py
```python
DEBUG = True
SPECIAL_FILE_PATH = '/whatever/'
S3_BUCKETS = {
    'special_file': 'test_bucket' if DEBUG else 'production_bucket'
}
```

Now in the initial migration for TestModel, the serialization of the special_file field will call S3BotoStorage with the explicit value of settings.S3_BUCKETS['special_file']. This is mixing the hardcoded settings values into the migrations, which wouldn't be a huge problem if this wasn't a setting commonly varied by deployment. In my example turning on debug and then running makemigrations would create a new migration with the hardcoded test bucket name in it.

Ideally the serialization would capture the variable definition "settings.S3_BUCKETS['special_file']" instead of the value it references, however I don't think it's possible to reflect on source like that in Python. 

So the next best solution is one where my example S3BotoStorage argument would be bucket_alias='special_file' and it would know to lookup the configured bucket name for 'special_file' in some S3BOTO_BUCKET_ALIASES settings dictionary.

**Comment by nlundquist** [comment]
Hmmm... feel free to change that issue title again if you wish. It isn't a bug at all that the bucket kwarg is serialized explicitly, thats just the way 1.7 migrations work I guess. It's more of an improvement on the bucket kwarg as its a bit of a shortcoming in the API if it's being hard coded into migrations (because it's commonly varied via configuration), and bucket aliasing would be one way to resolve it.

**Comment by nlundquist** [comment]
Any opinion on my pull request? Did my code example help us get on the same page?

**Comment by joerick** [comment]
I just got bitten by this, an automatic migration had hard-coded my development bucket into the field, which meant a subsequent data migration failed. But the bug was only visible when I ran the migration in production! I should have checked my automatic migrations more closely, but I'd like to find a way to stop this happening again.

**Comment by coulix** [comment]
One solution was to use a custom class with  @deconstructible decorator.

    @deconstructible
    class MyS3BotoStorage(S3BotoStorage):
        pass

However this does not work with 1.8 anymore and this page https://docs.djangoproject.com/fr/1.8/topics/migrations/#adding-a-deconstruct-method says we should add an __eq__ method. I have got not success on that so far.

**Comment by 7wonders** [comment]
Any solution to this? I like @nlundquist approach myself. Flexible.

**Comment by sww314** [comment]
#444 has a similiar solution: router for storages.

**Comment by Alexgmin** [comment]
Instead of #444, a better solution would be for the storage class to implement the deconstruct method instead of using the `@deconstructible` decorator.

This is what I'm using right now.

```python
foo = models.FileField(
    storage=foo_storage,
)
```

```python
foo_storage = get_storage_class(settings.FOO_STORAGE['storage']['class'])(
    bucket_name=settings.FOO_STORAGE['storage']['aws_storage_bucket_name'],
    access_key=settings.FOO_STORAGE['storage']['aws_access_key_id'],
    secret_key=settings.FOO_STORAGE['storage']['aws_secret_access_key'],
    location=settings.FOO_STORAGE['storage']['location'],
    querystring_auth=False,
    default_acl='public-read',
)
```
```python
from storages.backends.s3boto3 import S3Boto3Storage as BaseS3Boto3Storage


class S3Boto3Storage(BaseS3Boto3Storage):
    def deconstruct(self):
        return ('core.storages.s3boto3.S3Boto3Storage', [], {})
```

which means the migrations are like this
```python
migrations.AlterField(
    model_name='bar',
    name='foo',
    field=models.FileField(storage=core.storages.s3boto3.S3Boto3Storage(), upload_to=b''),
),
```
instead of 

```python
migrations.AlterField(
    model_name='bar',
    name='foo',
    field=models.FileField(
        storage=storages.backends.s3boto3.S3Boto3Storage(
            access_key=b'very_private_key',
            bucket_name=b'dev_bucket_name',
            default_acl=b'public-read',
            location=b'foo',
            secret_key=b'not_on_my_migrations_please',
        ),
        upload_to=b'',
    ),
),
```

Maybe `deconstruct()` could return some of the fields instead of an empty list.
Unless there's a problem with this approach, I don't see why this shouldn't be added to the library.

**Comment by Alexgmin** [comment]
Instead of #444, a better solution would be for the storage class to implement the deconstruct method instead of using the `@deconstructible` decorator.

This is what I'm using right now.

```python
foo = models.FileField(
    storage=foo_storage,
)
```

```python
foo_storage = get_storage_class(settings.FOO_STORAGE['storage']['class'])(
    bucket_name=settings.FOO_STORAGE['storage']['aws_storage_bucket_name'],
    access_key=settings.FOO_STORAGE['storage']['aws_access_key_id'],
    secret_key=settings.FOO_STORAGE['storage']['aws_secret_access_key'],
    location=settings.FOO_STORAGE['storage']['location'],
    querystring_auth=False,
    default_acl='public-read',
)
```
```python
from storages.backends.s3boto3 import S3Boto3Storage as BaseS3Boto3Storage


class S3Boto3Storage(BaseS3Boto3Storage):
    def deconstruct(self):
        return ('core.storages.s3boto3.S3Boto3Storage', [], {})
```

which means the migrations are like this
```python
migrations.AlterField(
    model_name='bar',
    name='foo',
    field=models.FileField(storage=core.storages.s3boto3.S3Boto3Storage(), upload_to=b''),
),
```
instead of 

```python
migrations.AlterField(
    model_name='bar',
    name='foo',
    field=models.FileField(
        storage=storages.backends.s3boto3.S3Boto3Storage(
            access_key=b'very_private_key',
            bucket_name=b'dev_bucket_name',
            default_acl=b'public-read',
            location=b'foo',
            secret_key=b'not_on_my_migrations_please',
        ),
        upload_to=b'',
    ),
),
```

Maybe `deconstruct()` could return some of the fields instead of an empty list.
Unless there's a problem with this approach, I don't see why this shouldn't be added to the library.
