### ISSUE TITLE
S3Boto3Storage is undocumented

### ISSUE THREAD

**Issue by karyon** [jschneier/django-storages#229]
this sentence here "Another [backend] for interacting via Boto3 was added in version 1.5"  on this page "http://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html?highlight=boto" seems to be the only mention of the `S3Boto3Storage` backend. It would be nice to have some more information on that.

noticed this when investigating https://github.com/django-compressor/django-compressor/issues/808. it would be cool if someone could have a look at that, it might be an issue of django-storages or the boto lib itself.

**Comment by kavdev** [comment]
See #222

**Comment by jschneier** [comment]
I merged in the extra line that mentions it and will now deploy a new docs version. Let me know if there is anything else I can look into.

**Comment by karyon** [comment]
I have about zero knowledge what these backends do, but i'd expect the differences betweens the two to be mentioned somewhere. otherwise, how would i choose between them? or is the difference between "boto" and "boto3" widely known among users of django-storages?

**Comment by jschneier** [comment]
From an api perspective there should be zero difference. It's all supposed to conform to the django file storage spec. I will put some stronger wording in that S3Boto3 is what everyone should use in the future. Boto itself is in maintenance mode/deprecated.

**Comment by karyon** [comment]
thanks, that sounds good.
