### ISSUE TITLE
Add customization callback for setting metadata attributes

### ISSUE THREAD

**Issue by lucasmg-dev** [jschneier/django-storages#231]
I need to be able to set AWS_HEADER for a separate file.

For example:

```
photos = models.ImageField(upload_to = 'photos') # max-age = 60
photos2 = models.ImageField(upload_to = 'photos') # max-age = 3600
```

**Comment by darkowic** [comment]
I had an idea for it. Even do some PR for it and we use it in our company. But it is not great. And do not cover all cases and all possible configurations. Check it it https://github.com/jschneier/django-storages/pull/152

**Comment by darkowic** [comment]
@jschneier what do you think to enhance `AWS_HEADER` setting by

1) additional keys with path to file
```
AWS_HEADERS = {
'*': { # or 'DEFAULT' etc
    'Expires': 'Thu, 15 Apr 2010 20:00:00 GMT',
    'Cache-Control': 'max-age=86400',
},
'admindata/pages': {
"Cache-Control": "max-age=86400" 
}
}
```

2)  implementation that detect setting based on model - like in http://easy-thumbnails.readthedocs.io/en/2.1/usage/#thumbnail-aliases

```
AWS_HEADERS = {
    <target>: {
       "Cache-Control": "max-age=86400" 
    },
    ...
}
```

> Use the target '' for project-wide aliases. Otherwise, the target should be a string which defines the scope of the contained aliases:
'sprocket.Widget.image' would make the aliases available to only the ‘image’ field of a ‘Widget’ model in an app named ‘sprocket’.
'sprocket.Widget' would apply to any field in the ‘Widget’ model.
'sprocket' would target any field in any model in the app.

**Comment by jschneier** [comment]
@darkowic what do you think of instead doing this as a callback? There are a number of projects that I use that allow you to specify a path to a function and we'll merge the results of that function into the parameters. I'm not sure how flexible the regex based solution is.

**Comment by darkowic** [comment]
Sorry for late reply @jschneier  I like the callback idea. But where do you want to place the callback? We need to check for header's setting in file's write and storage save method. What I remember that in the code we have two different logic for setting headers for saving and write. How do you imagine it?

So, what we could do in the function? only update headers or work on the whole bucket key?

**Comment by jschneier** [comment]
This was fixed for AWS
