### ISSUE TITLE
S3Boto3: Double localtime() call Exception on modified_time()  when settings.USE_TZ=False

### ISSUE THREAD

**Issue by piglei** [jschneier/django-storages#234]
Current implemention of S3Boto3 backend respect USE_TZ settings on Django>=1.10. But when  Django<1.10 users set USE_TZ to False, `modified_time()` will raise an ValueError:

> ValueError: astimezone() cannot be applied to a naive datetime

That's because `get_modified_time()` already returns a naive datetime object, `modified_time()` call localtime on this naive object again.

**Comment by jschneier** [comment]
Fixed in #235.
