### ISSUE TITLE
mime type issues

### ISSUE THREAD

**Issue by moh-moola** [jschneier/django-storages#24]
The S3BotoStorage lib doesn't set the correct mime type and defaults to 'application/octet-stream'

Hack: overide the _save method and replace: 
content_type = getattr(content, 'content_type',
            mimetypes.guess_type(name)[0] or self.key_class.DefaultContentType)
with: 
content_type = getattr(content._file, 'content_type',
            mimetypes.guess_type(name)[0] or self.key_class.DefaultContentType)

**Comment by jschneier** [comment]
Thanks for the report! You are correct, it's because we are wrapping what we `open` with `S3BotoStorageFile`.

**Comment by jschneier** [comment]
This was fixed a while ago in the S3 backend.
