### ISSUE TITLE
AWS_S3_HOST option for s3boto3 storage

### ISSUE THREAD

**Issue by AyumuKasuga** [jschneier/django-storages#249]
It would be great to have option `AWS_S3_HOST` in s3boto3 storage like in [s3boto](https://github.com/jschneier/django-storages/blob/ba497d4a535691f6bc23bd71c1655cfa3c23e7a1/storages/backends/s3boto.py#L237)

**Comment by vchrisb** [comment]
Had the same issue.
It is now called ```AWS_S3_ENDPOINT_URL```.

**Comment by AyumuKasuga** [comment]
@vchrisb Thank you a lot!
