### ISSUE TITLE
Common __init__ signature for all backends

### ISSUE THREAD

**Issue by skirsdeda** [jschneier/django-storages#25]
All backends should be compatible at least partly with the signature of django.core.files.storage.FileSystemStorage:

``` python
def __init__(self, location=None, base_url=None, file_permissions_mode=None, directory_permissions_mode=None):
```

Not sure about file and directory permission modes but location and base_url can surely be used in all backends. _location_ should be a path (e.g. '<dir>/<dir>/<dir>') while _base_url_ could provide the rest of URL for connection (protocol + hostname + port). For some backends even authentication credentials could be extracted from _base_url_.
Currently we have SFTP backend which has no __init__ args, then we have FTP backend which needs full URL in _location_ arg and the rest of backends are not very consistent as well, I guess.
The purpose of this would be to make all backends interchangable without having to fiddle with settings too much.

**Comment by jschneier** [comment]
Completely agree. I suspect quite a few of the backends were left to idle and received no love. I've begun deprecating the ones that are out of date and have just been waiting for people who use the ones that I don't to show up so we can start cleaning them up a bit. I'll look at standardizing FTP and SFTP soon.

**Comment by ZuluPro** [comment]
@skirsdeda @jschneier , I'm partially agree with the idea of follow `FileSystemStorage` signature.
Location may not be applicable to some storage
Base URL (MEDIA_URL) concerns file sharing which is not mandatory and some storage could provide its own mandatory URLs, so we can't base on it for guess authentication or more
And permissions arguments are really made for file system usage

**Comment by EvaSDK** [comment]
Since `DatabaseStorage` was removed in master, I had to write my own implementation here and I must say I found it to be pointless to try to match `__init__` signature of the `FilesystemStorage` class as of the 4 parameters, none were needed for my case. However, it think it would be a good idea to avoid the case of the previous `DatabaseStorage` class which used a `dict` as single parameter rather than explicit named parameters.

**Comment by jschneier** [comment]
@EvaSDK yes, agreed. I think that there is a fundamental difference between a FileSystem and other. I'm just going to have everything work by `kwargs`.

As a side note do you think it would be useful for me to restore `DatabaseStorage` to a separate repository? I created an organization for that purpose but wasn't sure if anyone was using the deprecated ones. I can see why DB might be useful though.

**Comment by EvaSDK** [comment]
It would be useful as a legacy package at least. pyodbc and references to Django 0.96 made me consider if I wanted to use it or not for a long time.

Maybe it can help in mutualizing efforts that went into https://pypi.python.org/pypi/django-db-file-storage, https://pypi.python.org/pypi/django-db-storage or https://pypi.python.org/pypi/django-database-storage or maybe it's just better to point one of these as the recommended replacement.

**Comment by EvaSDK** [comment]
My own work is pretty close in spirit to https://github.com/derekkwok/django-db-storage so I think I'll try to push patches there.
