### ISSUE TITLE
getting error on using azure storage with django-storages

### ISSUE THREAD

**Issue by aswincsekar** [jschneier/django-storages#250]
I use django-storages backend. While I upload files. I get this error

> Block blobs are not supported.
> <?xml version="1.0" encoding="utf-8"?>
> <Error><Code>BlobTypeNotSupported</Code><Message>Block blobs are not supported.
> RequestId:
> Time:2017-01-21T08:39:29.8209714Z</Message></Error>

I use premium storage account in azure. going through azure doc I found that azure premium storage doesn't support Block blobs.
django-storages documentation doesn't specify what type of azure storage to use. I Need some suggestions on what type of azure storage to use for video files and image files, which will work with django-storages.

**Comment by sww314** [comment]
Azure backend has been totally re-written. Please reopen if issues exist in the latest version (currently unreleased but no master).
