### ISSUE TITLE
AWS_QUERYSTRING_AUTH = False still requires credentials to generate static URLs

### ISSUE THREAD

**Issue by willplaehn** [jschneier/django-storages#254]
When using a public S3 bucket for static files and `AWS_QUERYSTRING_AUTH = False`, it would be advantageous to not require AWS access keys for django-storages to generate static urls.

As it stands, this setting only strips the URL after the credentials are created and added. If the credentials aren't present, we get a `NoCredentialsError` even though this particular function shouldn't need credentials to work if static files are public.

I'm not 100% on all the places Django calls `url()` or if I'm missing something where the credentials would be required anyway (I understand they're important for operations like uploads); does this make sense to implement?

[storages/backends/s3boto3.py line 576:](https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py#L576)
```
        url = self.bucket.meta.client.generate_presigned_url('get_object', Params=params,
                                                             ExpiresIn=expire)
        if self.querystring_auth:
            return url
        return self._strip_signing_parameters(url)
```

**Comment by mbarrien** [comment]
Note that the implementation of this basically requires someone to implement https://github.com/boto/boto3/issues/169 (which is the issue that I filed when I was forced to create the _strip_signing_parameters() method; see the comments inside _strip_signing_paremeters())

**Comment by john-parton** [comment]
Another thing I noticed is that generating the presigned urls takes a non-trivial amount of time.

As a hack, you can set `AWS_S3_CUSTOM_DOMAIN` to just be your bucket:

```python
AWS_S3_CUSTOM_DOMAIN = "mybucket.s3.amazonaws.com"
```

This will force the backend to completely skip the querystring auth generation.

If you use the class directly, you can subclass to get that behavior:

```python
from storages.backends.s3boto3 import S3Boto3Storage as StorageBase

class S3Boto3Storage(StorageBase):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.querystring_auth and not self.custom_domain:
            self.custom_domain = '%s.s3.amazonaws.com' % self.bucket_name
```

I've seen this technique shave as much as 200ms off some response times.

**Comment by getup8** [comment]
Looks like this fix was never merged. So is current "best practice" to define `AWS_S3_CUSTOM_DOMAIN` as your S3 bucket if you're serving public files and `AWS_QUERYSTRING_AUTH = False`?

Might be good to add (at least temporarily) to the docs if so.

**Comment by rfleschenberg** [comment]
This issue is definitely a performance problem if you need to output many URLs at once. The workaround with `AWS_S3_CUSTOM_DOMAIN` works for me.

**Comment by rfleschenberg** [comment]
https://github.com/boto/boto3/issues/169#issuecomment-315166425 this might be worth a try.
