### ISSUE TITLE
Timeout setting needed for S3 upload

### ISSUE THREAD

**Issue by KennyMonster** [jschneier/django-storages#279]
During the recent S3 outage with us-east-1, our own website because unavailable for what I believe is the following reason:

* The site is configured to use S3 for user uploaded media files
* The site used gunicorn w/ 3 processes for the app
* The S3 outage resulted in what appeared to be a long timeout while the app server tried to reach S3
* All 3 app server processes blocked, waiting on on the S3 connection resulting in nginx reporting on a bad gateway

I've looked around but have been unable to determine how to change the TCP timeout for S3 connections. Ideally it should be configurable so that it could be set to a low value, to keep all app processes from blocking.

**Comment by jschneier** [comment]
It seems that in `boto` this already exists and is something like 70 seconds by default and can be configured. You can also customize how your requests are made by passing in an `https_connection_factory` to the `S3Connection`.

While in `boto3` it is using a vendored version of `requests` which inherits all of the fine-grained control goodness of `urllib3`'s `Timeout`.

Regardless, not something I'm interested in bringing in to the library. I would like to add a new overridable hook to do customization of the endpoint connection.

**Comment by danlamanna** [comment]
> I would like to add a new overridable hook to do customization of the endpoint connection.

Does this exist? I would like to fine tune connection/read timeouts for my application. Is there another suggested way of doing this?

**Comment by KennyMonster** [comment]
@danlamanna I actually just figured this out on a new project not too long ago. In storages 1.7, the solution is to set the config via a custom storage that inherits from `S3Boto3Storage`.

storage_backends.py

```python
from botocore.config import Config
from django.conf import settings
from storages.backends.s3boto3 import S3Boto3Storage

class CustomS3Boto3Storage(S3Boto3Storage):
    """
    Override boto3 default timeout values
    """

    config = Config(
        connect_timeout=settings.S3_NETWORK_TIMEOUT,
        read_timeout=settings.S3_NETWORK_TIMEOUT,
        retries={
            'max_attempts': settings.S3_NETWORK_RETRY_COUNT,
        },
    )
```

Then in settings.py, set `DEFAULT_FILE_STORAGE = 'core.storage_backends.CustomS3Boto3Storage'`. You will obviously need to create the referenced settings variables as well. To see the config values you are overriding, checking out botocore/config.py.
