### ISSUE TITLE
Update django-storages to 1.11

### ISSUE THREAD

**Issue by Alex3917** [jschneier/django-storages#289]
Just wanted to create a ticket for updating django-storages to be compatible with / tested on Django 1.11, since right now there is no list of officially supported versions outside of the tox.ini file.

(This issue is mostly here for people looking to figure out if this package is 1.11 compatible yet.)

**Comment by jschneier** [comment]
Thanks. I'm aiming to push out a build by Friday and will update Trove classifiers then. I still need to add the last `get_modified_time` vs `modified_time`.

**Comment by jschneier** [comment]
Ugh the release is today, okay.
