### ISSUE TITLE
collectstatic with AWS_S3_FILE_OVERWRITE = False causes duplicate files

### ISSUE THREAD

**Issue by bofia** [jschneier/django-storages#291]
When using S3 as the static backend, and with AWS_S3_FILE_OVERWRITE = False. When collectstatic is run, it creates new files with random strings appended instead of overwriting the old one. This causes issues with files not being updated.

Are these 2 use cases incompatible with each other?

**Comment by 990px** [comment]
@bofia you can simply override `STATICFILES_STORAGE` pointing on your custom S3Boto3Storage subclass. Example:

```
# utils.py

from storages.backends.s3boto3 import S3Boto3Storage

MyStaticS3Boto3Storage = lambda: S3Boto3Storage(
    location="static",
    acl="public-read",
    querystring_auth=False,
    file_overwrite=True
)

# settings.py

STATICFILES_STORAGE = "path.to.MyStaticS3Boto3Storage"
```
