### ISSUE TITLE
Double slashes in staticfiles with CDN

### ISSUE THREAD

**Issue by ryanprater** [jschneier/django-storages#292]
Django requires a trailing slash on the `STATIC_URL`, (i.e. `STATIC_URL = 'https://mycdndomain.com/'`) but `S3Boto3Storage.url` appends a trailing slash after the `custom_domain` (specified by `AWS_S3_CUSTOM_DOMAIN`). 
Originally I had set `AWS_S3_CUSTOM_DOMAIN = STATIC_URL` and staticfiles was looking up resources such as `https://mycdndomain.com//less/style.less` (notice the double slash).
It was hours later after debugging that I realized a trailing slash can not be included in the `AWS_S3_CUSTOM_DOMAIN`.
i.e. `AWS_S3_CUSTOM_DOMAIN = 'https://mycdndomain.com'`

Not sure what the best fix is here - maybe just a bold note in the documentation?

**Comment by jschneier** [comment]
Maybe a system check? Django has `deploy` checks so that it only runs against production settings. Or we can just not bother with that until it becomes an issue.

**Comment by ryanprater** [comment]
Judging that no one else has complained about this, it's probably best not to over-build a fix. However, it's worth noting in the documentation. PR created here: https://github.com/jschneier/django-storages/pull/294

**Comment by jschneier** [comment]
Thanks for the documentation update, going to close now.
