### ISSUE TITLE
Add AWS_PRELOAD_METADATA to Documentation

### ISSUE THREAD

**Issue by ryanprater** [jschneier/django-storages#293]
I just dove into this option today and noticed it is fully functional but not (no longer?) documented.

I'm not sure I 100% comprehend the functionality. If someone can explain it in detail I'm very willing to update the docs and submit a PR!

**Comment by chachra** [comment]
It causes major perf. issues.

**Comment by jschneier** [comment]
I'm going to deprecate and remove it, it loads literally every entry in a bucket. It is from ~2011 (way before I was involved).

**Comment by jschneier** [comment]
Deprecated in #553
