### ISSUE TITLE
An error occurred (403) when calling the HeadObject operation: Forbidden Django==1.11

### ISSUE THREAD

**Issue by yamijuan** [jschneier/django-storages#296]
i upgraded django from 1.10.7 to 1.11 an i get the error in the title. i'm trying to open a saved image for crop, but the process dies in storage.open(image_name)
```python
if original.closed:
    original = storage.open(original.name)
```

**Comment by jschneier** [comment]
What version of this library are you using? And your backend, configuration etc.

**Comment by yamijuan** [comment]
i'm using django-storages==1.5.2
boto3==1.4.4 for amazon s3
using this backend 
`from storages.backends.s3boto3 import S3Boto3Storage`
i configured the credentials in ~/.aws/credentials

it works perfectly in django 1.10.7

**Comment by jschneier** [comment]
And the only difference is the Django version? Do you have the filename that you are trying to pass in? Forbidden reads like some sort of `SuspiciousOperation` that is getting translated by Django and might be getting triggered by `safe_join`?

**Comment by yamijuan** [comment]
The only difference is the Django version. I have a imagefieldfile, when django calls the save of the field i override it. First i call a super
```python
def save(self, name, content, save=True):
    super(ImageFieldFile, self).save(name, content, save)
```
then i try to generate a thumbnail
`self._generate_thumb(content, my_custom_size)`

```python
def _generate_thumb(self, image, size):
    _file_base, extension = self.name.rsplit('.', 1)
    thumb_name = get_thumb_name(self.name, size)
    thumbnail = generate_thumb(image, size, self.field.preserve_ratio, self.storage, extension)

def generate_thumb(original, size, preserve_ratio, storage, image_format='JPEG'):
    if original.closed:
        original = storage.open(original.name)
    original.seek(0)  # see http://code.djangoproject.com/ticket/8222 for details
```
it dies in storage.open(original.name), the original image exists because is in my amazon bucket

**Comment by jschneier** [comment]
Since it's a boto error I'm pretty confused by the difference in Django version. There [an issue](https://github.com/aws/aws-cli/issues/1689) that shows how a 404 is getting translated into 403 depending on permissions. `.save` returns the name of a file which can be different depending on `.get_available_name` so so I'm wondering if something changed there.

**Comment by yamijuan** [comment]
I got it. I don't know why, but in the previous version of django my original file has the new name of the file in `original.name`, so the `storage.open(original.name)` find it. But in the lastest version, the name isn't update in the original file, so i have to use the descriptor name with `self.name`.

That's all, thank you very much.
