### ISSUE TITLE
Error on collecstatic when item doesn't exist in S3 yet

### ISSUE THREAD

**Issue by cawjustin** [jschneier/django-storages#297]
I'm getting deployment errors to AWS with the latest version (using the Git egg) when there's a new static file not already in S3.

s3boto.py, line 447, _get_key

There's a KeyError seemingly because there's nothing there yet to reference.

**Comment by jschneier** [comment]
You have `AWS_PRELOAD_METADATA = True`. Yes I can see what changed. What is the function that calls `_get_key` above that in the traceback?

**Comment by jschneier** [comment]
It broke in [this PR](https://github.com/jschneier/django-storages/commit/ab574fd62adb8e2a9bf636d31896e0f88b6643b1).

**Comment by cawjustin** [comment]
s3boto.py line 462, in exists return self._get_key(name) is not None

**Comment by jschneier** [comment]
Just pushed a fix. Unfortunately the test suite was written using only mocking which I think is not sufficient. Rewriting it to use live data is on my TODO list but it's a big task. Let me know if that works for you.

**Comment by cawjustin** [comment]
Lovely. I'll try it out.
