### ISSUE TITLE
[gcloud] set the correct Content-Type for file

### ISSUE THREAD

**Issue by Sgiath** [jschneier/django-storages#303]
gcloud backend uploads the file with default Content-Type so it is set to `application/octet-stream` on Google Cloud Storage.
Use this API https://googlecloudplatform.github.io/google-cloud-python/stable/storage-blobs.html#google.cloud.storage.blob.Blob.content_type to set the correct type (at least for `.css` and `.js` files).

**Comment by faxioman** [comment]
@Sgiath I'll make a pull request for this in one/two days.

**Comment by Sgiath** [comment]
@faxioman how it looks like with the Pull Request?

**Comment by robinelvin** [comment]
This also looks to be a problem with the S3Boto storage backend. Should I open a new ticket for that or just mention it here?

**Comment by Sgiath** [comment]
I created Pull Request #320 with the fix and the function for getting the correct MIME type is in the `storages.utils` so it should be easy to implement also for S3Boto. It just requires someone who know the S3Boto backend. So I recommend to start the new issue since I am not able to fix S3Boto and I am planning to close this when my Pull Request will be merged.

**Comment by scjody** [comment]
@Sgiath I'm OK with the change in #320 but could you describe your rationale for the change here? In other words what problem does an incorrect MIME type cause for you that you're trying to fix?

**Comment by Sgiath** [comment]
The problem is that especially CSS and JS are not interpreted as Stylesheet respective JavaScript. The warning is thrown in console:
```
Resource interpreted as Stylesheet but transferred with MIME type application/json: "https://storage.googleapis.com/<bucket>/rest_framework/css/bootstrap.min.css".
```
And then the CSS or JS are not used:
![screenshot from 2017-07-01 14-10-31](https://user-images.githubusercontent.com/6009528/27761998-768ca8c2-5e68-11e7-9650-6ad591f43a4a.jpg)

For other file types it's just convenient and good practice to have the correct MIME type set.
