### ISSUE TITLE
[gcloud] add settings for making the files public automatically

### ISSUE THREAD

**Issue by Sgiath** [jschneier/django-storages#304]
The option to make files public automatically would be very nice. Something like `GS_DEFAULT_PUBLIC = True`
See the API https://googlecloudplatform.github.io/google-cloud-python/stable/storage-blobs.html#google.cloud.storage.blob.Blob.make_public

**Comment by svengt** [comment]
Don't you think it would be better to just set the object default permissions for `allUsers` on the bucket? This should be a better approach for performance.
<img width="457" alt="screen shot 2017-05-14 at 17 55 20" src="https://cloud.githubusercontent.com/assets/1049636/26035575/20ad5140-38cf-11e7-951e-e6bad41ab449.png">

**Comment by Sgiath** [comment]
That is good point I forgot about this option. Thanks
