### ISSUE TITLE
[gcloud] fix path generating for object

### ISSUE THREAD

**Issue by Sgiath** [jschneier/django-storages#306]
The backend generates paths like this: `<link rel="stylesheet" type="text/css" href="https://storage.googleapis.com/<bucket-name>/admin%2Fcss%2Fdashboard.css">`
instead of this: `<link rel="stylesheet" type="text/css" href="https://storage.googleapis.com/<bucket-name>/admin/css/dashboard.css">`

It is working but looks odd. Consider using this API https://googlecloudplatform.github.io/google-cloud-python/stable/storage-blobs.html#google.cloud.storage.blob.Blob.public_url

**Comment by jschneier** [comment]
Are you using the new `gcloud` backend (still in master, not yet released)? It is using `.public_url`.

**Comment by Sgiath** [comment]
Yes I am installing the `django-channels` from git and using the new `gcloud` backend.

**Comment by svengt** [comment]
I also ran into this problem.

**Comment by whoknowwhat** [comment]
So do I. Should I use `gs` instead of `gcloud`?

**Comment by whoknowwhat** [comment]
Still have same problem with 1.6.5

```
google-cloud-storage==1.3.1
django-storages==1.6.5
Django==1.11
```

**Comment by jschneier** [comment]
Sorry for the delay, this was fixed upstream.
