### ISSUE TITLE
Different parameters for different objects/files

### ISSUE THREAD

**Issue by erikkn** [jschneier/django-storages#308]
Hi guys,

Currently I am using the django-storages module (with boto3) to connect to my S3 bucket. Everything works fine, but I was wondering if you guys know an efficient way to set different object parameters for different objects. So for example:
 - Set a cache-control value of xx days for image files
 - Set a cache-control value of xx hours for css files

**Comment by jschneier** [comment]
Dupe #231. I had the idea (borrowed liberally from other good projects) of providing a callback setting for customization rather than making a headers only setting. Thoughts on this? I'd accept a PR, hoping to get to it sooner rather than later.
