### ISSUE TITLE
add expire on url for Azure

### ISSUE THREAD

**Issue by guydou** [jschneier/django-storages#312]
The S3Boto3Storage `url()` method has attrbiute expire, 

it will be really nice if we could have the same behavior for azure, 

It is feasible using `generate_shared_access_signature` method in `BlobService` 

(I might fix it myself soon)

**Comment by guydou** [comment]
This pull request fixes the problem https://github.com/jschneier/django-storages/pull/318

**Comment by sww314** [comment]
Closed via #565.
