### ISSUE TITLE
Azure support 'w' mode on open

### ISSUE THREAD

**Issue by guydou** [jschneier/django-storages#313]
Currently in the azure backed I can't do the following:
`f= default_storage.open("bla", "w")`

if the blob `bla` doesn't exist 

and also I can not update bla with new content, if I use: `default_storage.save("bla", content)` and bla already exists it will a new blob will be created with a random suffix 

for example:
bla
bla_MhgTcjK

**Comment by guydou** [comment]
this pull request fixes the problem https://github.com/jschneier/django-storages/pull/318

**Comment by sww314** [comment]
Azure backend was rewritten in #565. Please reopen if the issue still exists.
