### ISSUE TITLE
S3 boto3 object tagging

### ISSUE THREAD

**Issue by NerdsvilleCEO** [jschneier/django-storages#319]
With boto3 backend is it possible to do object tagging such as this:
https://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.put_object_tagging
https://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.get_object_tagging

**Comment by m6a-UdS** [comment]
It is also possible to do it using the Tagging parameter of Bucket.put_object():
http://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Bucket.put_object

This way the uploading+tagging of the objects is atomic, from what I understand.
