### ISSUE TITLE
Azure: Cache-Control ?!?

### ISSUE THREAD

**Issue by jedie** [jschneier/django-storages#323]
How can i manipulate the `Cache-Control` header for Azure backend?!?
e.g.: set `cache_control` in `connection.put_blob()` etc.

I found these only for `S3 Boto3 Storage` usage, isn't it?!?

**Comment by jedie** [comment]
ping

**Comment by jedie** [comment]
ping

**Comment by sww314** [comment]
Backend was re-written in #565. Please reopen this issue still exists.

**Comment by nitely** [comment]
This can be done for private storage when asking for a URL with expiration date (i.e: `generate_blob_shared_access_signature` function has a `cache_control`). It must be implemented in the new backend, 'cause I've learned about this just now :smile: 

For a public storage, I think the only way is through Azure's CDN.
