### ISSUE TITLE
S3 Buckets end up in wrong region?

### ISSUE THREAD

**Issue by GeoTob** [jschneier/django-storages#324]
Using the following settings, I'd expect django-storages to create buckets in the region I specify:

```python
AWS_AUTO_CREATE_BUCKET = True
AWS_S3_REGION_NAME = "us-west-2"
```

For no apparent reason however, all auto-created buckets end up in `us-east-1`. Is that expected behaviour (on v1.5.2 with `S3Boto3Storage`)?

**Comment by jschneier** [comment]
Fixed in master (https://github.com/jschneier/django-storages/pull/206),  sorry haven't released in a _long time_.
