### ISSUE TITLE
release 1.6.0

### ISSUE THREAD

**Issue by ryanpineo** [jschneier/django-storages#333]
I was wondering when you were planning on releasing 1.6.0.  The added support for Django 1.11 would be really useful for the projects I work on.

Thanks for the great work!

**Comment by arthurk** [comment]
I would really appreciate if 1.6.0 would be released as I'm looking into using the Google-Storage backend

**Comment by jschneier** [comment]
Yes, doing it today

**Comment by jschneier** [comment]
Yep.

**Comment by jschneier** [comment]
Done.
