### ISSUE TITLE
Add support for IAM role credentials to Boto S3 backend

### ISSUE THREAD

**Issue by hectcastro** [jschneier/django-storages#34]
If access key and secret key credentials are not provided via the Django settings, or the environment, it would be helpful if the Boto S3 backend automatically tried to retrieve authentication credentials from instance metadata.

**Comment by jschneier** [comment]
Sounds like a great feature request, want to open a pull request?

**Comment by mbarrien** [comment]
I believe the underlying Boto library already do this if the access key and secret key aren't passed in. It should just be a matter of getting Django storages to not pass something in or to pass in None for key/secret values. It might even do it now if you omit those settings.

**Comment by jschneier** [comment]
@mbarrien interesting, thanks for the input. I'll try that out.

**Comment by maurizi** [comment]
It looks like when the access key and secret key are not provided, Boto will try and query the instance metadata service automatically.

So the only change really needed in this library is documentation that providing an access key and secret key are not required for the Boto backend when using an EC2 instance with IAM roles set.

**Comment by hectcastro** [comment]
Good call, @mbarrien.

@jschneier, Let me know where the best place is to document this and I'll open a PR.

**Comment by ayeowch** [comment]
@hectcastro Have you got a chance to open a PR for this?

**Comment by hectcastro** [comment]
@ayeowch I have not because it is not clear where the documentation should live. The original `django-storages` documentation is still referenced in this fork's `README`.

As @maurizi said, we simply omit the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` settings to force Boto to [look them up](https://github.com/boto/boto/blob/develop/boto/provider.py#L379) in the instance metadata.

**Comment by ayeowch** [comment]
@hectcastro Thanks. Indeed this works for me:
AWS_ACCESS_KEY_ID = None  # Set to None to use IAM role
AWS_SECRET_ACCESS_KEY = None  # Set to None to use IAM role
All that is left to do is to ensure e.g. the host EC2 instance has the right IAM role attached to it with permission to write to S3.

**Comment by jackmurphy** [comment]
I'm going to pile on here.

It would be really helpful to have a complete listing of the S3 permissions required.

**Comment by hanleyhansen** [comment]
@hectcastro omitting or setting `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to `None` is not working for us.

It seems as though if those values aren't set we call `self._get_acccess_keys()`: https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto.py#L268

And `self.get_access_keys()` never goes out to boto to get the IAM profile from the metadata service. It just tries to do it's own lookup of the env vars: https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto.py#L305-L318

Am I missing something here?

**Comment by hanleyhansen** [comment]
Oh now I see that @lmorchard provided a solution in his linked PRs but that never made it back to master. What is the status of that?

**Comment by zheli** [comment]
@hanleyhansen you probably need to upgrade your pip package. I have tried 1.5.1 and it works without the PR.

**Comment by jschneier** [comment]
@zheli thanks for the confirmation of that. please reopen if you are still having issues.

**Comment by ranvijayj** [comment]
I am using boto 2. I am trying to upload/Download files from S3 into/out of the my django app. 
It still adds the amazon-sec-token at the end of the object URL.

**Comment by ervoiox** [comment]
@ranvijayj @jleclanche @jschneier I'm still running into issues where the amaz-sec-token is being appended at the end of the object URL. Were you able to find a fix @ranvijayj ?

Using Django 1.8.8, Boto 2.48.0 (patched with this commit: https://github.com/boto/boto/pull/3673), and Django Storages 1.6.3.

**Comment by ervoiox** [comment]
OK, upon looking at the patch (https://github.com/boto/boto/pull/3673), it does not handle `generate_url`, you need to also check for `query_auth` on the `headers` condition: https://github.com/boto/boto/blob/develop/boto/s3/connection.py#L422 - so it should look like `if query_auth and headers:`.

Hope this helps anyone else having the issue where `generate_url` is appending the headers and `query_auth` is set to false.

**Comment by elcolie** [comment]
Any progress on this so far?
