### ISSUE TITLE
Add some indication of the rename to django-storages-redux on PyPI

### ISSUE THREAD

**Issue by hobarrera** [jschneier/django-storages#351]
I'd been using django-storages-redux for some time, and didn't realized it had now replaced django-storages as the canonical fork.

It might be worthwhile to add a bit note on top of the PyPI docs pointing out this rename, so that all downstreams keep up to date. Visiting https://pypi.python.org/pypi/django-storages-redux provides no indication that development has moved to django-storages.

Thanks for maintaining this, BTW!

**Comment by jschneier** [comment]
Good idea

**Comment by jschneier** [comment]
Just released 1.3.3 of django-storages-redux with the language in the README at the top of PyPI and a warning printed whenever the library is imported indicating the new namespace. Thanks for the idea!

**Comment by hobarrera** [comment]
np. Thanks for this, and for maintaining this! 🎉

**Comment by mgan59** [comment]
Recently upgraded a list of python packages for a django app.  Now everytime I run a `python manage.py <commands>` I see this warning message.  Wanted to suggest to anyone looking to silence the message to add the following to your `settings.py`

```python
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module='storage')
```
