### ISSUE TITLE
Dropbox: "'GetTemporaryLinkResult' object is not subscriptable" 

### ISSUE THREAD

**Issue by seanw** [jschneier/django-storages#356]
I'm running release 1.6.3 with dropbox==8.0.0 and Django==1.11.1. The ['link'] access on line 140 of /storages/backends/dropbox.py is giving a "'GetTemporaryLinkResult' object is not subscriptable" exception:

    def url(self, name):
        media = self.client.files_get_temporary_link(self._full_path(name))
        return media['link'] 

I've found that this will work as intended:

    d.files_get_temporary_link(path).link

I'm assuming there's something wrong with my install but I've tried several different versions of this package and the Dropbox package and get the same issue.

**Comment by jschneier** [comment]
Unfortunately I don't have anyone who is willing to take on testing and the initial contributor of the Dropbox backend has gone quiet. I'd like to rewrite the tests altogether to make live API calls to prevent these sorts of breakages.

**Comment by jschneier** [comment]
Thanks for the report.
