### ISSUE TITLE
minio object storage support

### ISSUE THREAD

**Issue by royge** [jschneier/django-storages#362]
Does the S3 backend works with [minio](https://www.minio.io/)? Minio claims to be S3 compatible.

I have a project which uses minio instead of S3 and planning to use django-storages instead of my own crafted code.

**Comment by sww314** [comment]
@royge Did it work? Someone recently added documentation for Digital Ocean spaces which uses the S3 API.

**Comment by royge** [comment]
@sww314 This is quite an old question. We haven't actually tested it because we stop our self-hosted minio services and migrated to S3.

**Comment by graingert** [comment]
@sww314 I'm actually looking into using minio in development to ensure that we handle files correctly in production.

It looks like if you want to use pre-signed URLs https://github.com/jschneier/django-storages/issues/165#issuecomment-275344814 you have to use:
one of:
* django-minio
* django-minio-storage
