### ISSUE TITLE
support for azure sdk 2.0 - azure-storage 0.3x

### ISSUE THREAD

**Issue by tonynys** [jschneier/django-storages#372]
the python script django-storages/blob/master/storages/backends/azure_storage.py
does only support azure storage 0.2 (from azure sdk1.0)
When using sdk2.0 it will fail to load "BlobService" since now it is "BlockBlobService"

So I allways need to downgrade the azure sdk, since running "pip install azure" will install the latest.
When will there be support for the new azure sdk ? it has many nice features.

thanks

**Comment by lucaluca** [comment]
Looks like this would be solved by #318.

**Comment by Bernix01** [comment]
any update on this?

**Comment by sww314** [comment]
Closed via #565. Supports latest azure libraries.
