### ISSUE TITLE
Boto ACL public-read not working

### ISSUE THREAD

**Issue by jlariza** [jschneier/django-storages#377]
Good day, 
I have the following configuration for my storages.
```python
from storages.backends.s3boto import S3BotoStorage
StaticRootS3BotoStorage = lambda: S3BotoStorage(location='static')
MediaRootS3BotoStorage = lambda: S3BotoStorage(location='media')
DEFAULT_FILE_STORAGE = 'config.settings.production.MediaRootS3BotoStorage'
MEDIA_URL = 'https://s3.amazonaws.com/%s/media/' % AWS_STORAGE_BUCKET_NAME
STATIC_URL = 'https://s3.amazonaws.com/%s/static/' % AWS_STORAGE_BUCKET_NAME
STATICFILES_STORAGE = 'config.settings.production.StaticRootS3BotoStorage'
```
I also have a model with `logo = models.ImageField(blank=True, verbose_name=_('Logo'))`

The problem is that whenever I upload a logo, via admin, it is created as private at s3 and I need to set the public permission manually. I tried to set explicitly AWS_DEFAULT_ACL='public-read' but it did not work.

am I missing something?

Thank you,

**Comment by coredumperror** [comment]
I recently ran into a similarly baffling issue with my files all being 'private' even though I was setting `AWS_DEFAULT_ACL = 'public-read'`. What had happened was that a piece of code we had copied from a blog was unintentionally setting the `default_acl` attribute on the main django file storage singleton (`django.core.files.storage.default_storage`) to 'private'. This code ran at the start of every request, which would then cause all files uploaded during requests to have the 'private' act.

So I'd suggest looking through your code to see if anything is assigning to the `default_acl` attribute on an object.
