### ISSUE TITLE
TypeError when collectstatic using dropbox backends

### ISSUE THREAD

**Issue by ryuuzake** [jschneier/django-storages#384]
` remote:          File "/app/.heroku/python/lib/python3.6/site
packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 364, in copy_file`
`remote:            self.storage.save(prefixed_path, source_file)`
`remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/core/files/storage.py", line 54, in save`
`remote:            return self._save(name, content)`
`remote:          File "/app/.heroku/python/lib/python3.6/site-packages/storages/backends/dropbox.py",
line 111, in _save`
`remote:            self.client.files_upload(content, self._full_path(name))`
`remote:          File "/app/.heroku/python/lib/python3.6/site-packages/dropbox/base.py", line 1267, in files_upload`
`remote:            f,`
`remote:          File "/app/.heroku/python/lib/python3.6/site-packages/dropbox/dropbox.py", line 234, in request`
`remote:            timeout=timeout)`
`remote:          File "/app/.heroku/python/lib/python3.6/site-packages/dropbox/dropbox.py", line 325, in` `request_json_string_with_retry`
`remote:            timeout=timeout)`
`remote:          File "/app/.heroku/python/lib/python3.6/site-packages/dropbox/dropbox.py", line 369, in` `request_json_string`
`remote:            type(request_binary))`
`remote:        TypeError: expected request_binary as binary type, got <class 'django.core.files.base.File'>
`

Got this error when running collectstatic --noinput when pushing to heroku

**Comment by jschneier** [comment]
This is fixed in master, will release a new version in the next few days
