### ISSUE TITLE
Use CDN URL to show gcloud images

### ISSUE THREAD

**Issue by zisk0** [jschneier/django-storages#385]
Hello!

We are using storages.backends.gcloud.GoogleCloudStorage to handle our images. We are uploading to a Google Cloud segment, and so far so good: The images are uploaded fast and are shown with no issues. The problem is we want the images to be retrieved using our CDN URL, not the https://storage.googleapis.com/ URL that is used by default.

I have dived into the docs and code, but haven't seen a solution. Just the issue #309, but I'm not sure if it is about the same situation we have. Is there any option or workaround we can use?

Thanks for your time!

**Comment by martey** [comment]
I also ran into this issue, but was able to resolve it by patching django-storages (see #648).
