### ISSUE TITLE
Document extra dependancy when using Google Cloud Storage backend

### ISSUE THREAD

**Issue by driesdesmet** [jschneier/django-storages#389]
Nowhere in the docs is mentioned that when using the Google Cloud Storage backend, you actually need to install an extra dependancy: `google-cloud-storage`

When running, an exception is raised:
```
django.core.exceptions.ImproperlyConfigured: Could not load Google Cloud Storage bindings.
See https://github.com/GoogleCloudPlatform/gcloud-python
```

So when surfing to the mentioned url, I thought I had to install the all of google python client, but that install a whole suite of dependancies. `google-cloud-storaga` is enough it seems.

I believe there is a way to install extra's to a python package, something along the lines of `pip install django-storages[google-cloud]` but I'm not familiar if this still works or how involved that is.

**Comment by browniebroke** [comment]
Agreed, and we could do something similar for each back-end.
A starting point is being covered in PR https://github.com/jschneier/django-storages/pull/274
