### ISSUE TITLE
Digital Ocean Spaces support

### ISSUE THREAD

**Issue by paramono** [jschneier/django-storages#395]
Digital Ocean launched a new object storage service called Spaces. Are there any plans to support Spaces in this package?

**Comment by destos** [comment]
You can use the existing `S3BotoStorage` class as their API is "the same" or close.

**Comment by EdNutting** [comment]
Here's some example config for you - this works with current stable version of Django storages:

| Name                          | Description                                                                  | Example value                                                      |
|-------------------------------|------------------------------------------------------------------------------|--------------------------------------------------------------------|
| AWS\_STORAGE\_BUCKET\_NAME    | The name of the storage bucket.                                              | mysite                                                            |
| AWS\_S3\_ENDPOINT\_URL        | The endpoint url excluding the bucket name.                                  | https://nyc3.digitaloceanspaces.com                                |
| AWS\_S3\_OBJECT\_PARAMETERS   | Default params for objects.                                                  | { 'CacheControl': 'max-age=86400' }                                |
| AWS\_LOCATION                 | The folder within the space to store files.                                  | mysite                                                            |
| AWS\_S3\_SIGNATURE\_VERSION   | Signature version. DigitalOcean only support v2 for pre-signed urls.         | s3=s3v2 (Version 2), s3v4=s3v4 (Version 4)                         |
| AWS\_STATIC\_LOCATION         | The folder within the space to store static files.                           | '%s/static' % AWS_LOCATION                                         |
| STATICFILES\_STORAGE          | The storage backend to use for static files.                                 | 'op\_storage.storage\_backends.StaticStorage'                      |
| STATIC\_URL                   | The base URL for generating URLs to static files included in rendered pages. | "https://%s/%s/" % (AWS\_S3\_ENDPOINT\_URL, AWS\_STATIC\_LOCATION) |
| AWS\_PUBLIC\_MEDIA\_LOCATION  | The folder within the space to store public media files.                     | '%s/media/public' % AWS_LOCATION                                   |
| DEFAULT\_FILE\_STORAGE        | The storage backend to use for public media files.                           | 'op\_storage.storage\_backends.PublicMediaStorage'                 |
| AWS\_PRIVATE\_MEDIA\_LOCATION | The folder within the space to store private media files.                    | '%s/media/private' % AWS_LOCATION                                  |
| PRIVATE\_FILE\_STORAGE        | The storage backend to use for private media files.                          | 'op\_storage.storage_backends.PrivateMediaStorage'                 |

### Private Configuration

| Name                     | Description                                                                                                                                                                                                 |
|--------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| AWS\_ACCESS\_KEY\_ID     | The access key for the storage API. Although this can be public, it's useful to store it with the secret key to force the server admin to think about / change it, at the same time as changing the secret. |
| AWS\_SECRET\_ACCESS\_KEY | The secret key for the storage API. Never reveal this to anyone :)                                                                                                                                          |

You can use the models/storage backends/views/etc from the blog post below to create a test site (called mysite) to try this out. Testing locally using runserver works.

https://simpleisbetterthancomplex.com/tutorial/2017/08/01/how-to-setup-amazon-s3-in-a-django-project.html

See the folder "s3-example-public-and-private" from the GitHub repo for that blog post: https://github.com/sibtc/simple-s3-setup

To get the access key and secret key, follow the getting started guide from DigitalOcean: https://www.digitalocean.com/community/tutorials/managing-access-to-digitalocean-spaces#option-1-%E2%80%94-sharing-access-to-spaces-with-access-keys

Hope this helps!
Ed

**Comment by sww314** [comment]
@EdNutting Could you create a pull request to add this to the documentation? It would be very helpful.

**Comment by sixthgear** [comment]
Helped me immensely.

**Comment by EdNutting** [comment]
@sww314 Done 👍 (Good to hear people are finding this helpful.)

**Comment by sww314** [comment]
Closed by #521
