### ISSUE TITLE
is it possible to set object ACL before save ? ( google cloud storage )

### ISSUE THREAD

**Issue by myimages** [jschneier/django-storages#398]
Hello , I am trying to set the object ACL to public before saving the object to google cloud storage.

I am aware of the possibility of making the whole bucket readable , but this is not what I want to achieve.

what I am doing now is setting the object as public using `blob.make_public()` which require me to get the blob object first , then set its ACL.

is there away to specify object acl before save call in `GoogleCloudStorage.save` ?

**Comment by myimages** [comment]
The best approach IMHO would be to override `_get_or_create_bucket` in `GoogleCloudStorage` to use `bucket.default_object_acl.save_predefined('WANTED_DEFAULT_ACL')` instead of using `bucket.acl.save_predefined('wANTED_DEFAULT_ACL')` which effects the whole bucket.

in other words, if you set the bucket public , everybody will be able to list its contents at root, which is not a good idea, therefore , it is much better and safer to use `bucket.default_object_acl` not just `bucket.acl`


this could be done from gsutils or using python client like shown above ( I haven't found a way to set Default Object ACL from the web gui ).

**Comment by sww314** [comment]
Use GS_DEFAULT_ACL. Closed by #460
