### ISSUE TITLE
S3BotoStorage doesn't properly fallback to other Content-Type heuristics 

### ISSUE THREAD

**Issue by bxm156** [jschneier/django-storages#406]
Content Type is determined by the following:

1. a property called content-type
2. the filename
3. a default is used

If the `content-type` property doesn't exist, the logic falls back to 2 and 3. But the logic doesn't properly fallback if the content_type exists, but it set to None. 

I found that in django my InMemoryFileUpload had a content_type of None.  And so django-storages would try to make a s3 upload via boto3 with the following params {"Content-Type:": None}

This would cause boto to crash with 

```Invalid type for parameter ContentType, value: None, type: <class 'NoneType'>, valid types: <class 'str'>```

**Comment by alexhayes** [comment]
@bxm156 Are you using django-filer to upload the file in the admin?

**Comment by willplaehn** [comment]
I encountered this issue today using the s3boto3 backend when dealing with a certain .ico file and reached the same conclusion as the OP. I'm not using django-filer

[s3boto3.py 421](https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py#L421)
```
        _type, encoding = mimetypes.guess_type(name)
        content_type = getattr(content, 'content_type',
                               _type or self.default_content_type)
```

Could be changed to something like the following. Keeping the linebreaks for easier comparison:

```
        _type, encoding = mimetypes.guess_type(name)
        content_type = getattr(content, 'content_type',
                               None) or _type or self.default_content_type
```

What do you think?

**Comment by bxm156** [comment]
@alexhayes  Yes, I was using django-filer. However it seems like @willplaehn is not.

**Comment by Alir3z4** [comment]
I'm using Django Filler as well, and this is happening for me as well
