### ISSUE TITLE
Tests failing on master due to paramiko requiring enum in python3.3

### ISSUE THREAD

**Issue by bxm156** [jschneier/django-storages#409]
Tests are failing on master due to paramiko's depedency on the stdlib enum. Technically paramiko doesn't support python3.3, but django-storages tests paramiko in that env. enum wasn't added to the stdlib until python 3.4

In order to compensate, I added a line in tox.ini that instructions tox to install enum34 into the python3.3 env. I added it to my existing pull request at https://github.com/jschneier/django-storages/pull/407

**Comment by browniebroke** [comment]
Given that Python 3.3 [has now reached end of life](https://docs.python.org/devguide/#status-of-python-branches), I would argue that it's expected to have libraries stop supporting it as well (which might be why paramiko has dropped it). Probably it's time for django-storages to drop it as well?

**Comment by bxm156** [comment]
I think its reasonable for django-storages to drop support of py3.3

**Comment by timgraham** [comment]
Python 3.3 testing is removed in https://github.com/jschneier/django-storages/pull/415.
