### ISSUE TITLE
Google Cloud Storage: Cache Control

### ISSUE THREAD

**Issue by ezarowny** [jschneier/django-storages#411]
It'd be nice to be able set the cache control header at the time of object upload. The docs for this can be found here:  https://googlecloudplatform.github.io/google-cloud-python/latest/storage/blobs.html#google.cloud.storage.blob.Blob.cache_control

**Comment by gfhuseyinyilmaz** [comment]
Hello, actually this is very important to use google cloud as storage backend. Because google-cdn requires cache-control headers to cache google-cloud-storage files.

**Comment by gfhuseyinyilmaz** [comment]
In case anybody else ends up here, to solve this issue I made a custom storage backend with updated _save method like this:

```
class GoogleCloudStorage(OriginalStorage):

    def _save(self, name, content):
        cleaned_name = clean_name(name)
        name = self._normalize_name(cleaned_name)

        content.name = cleaned_name
        encoded_name = self._encode_name(name)
        file = GoogleCloudFile(encoded_name, 'rw', self)
        # Modification start
        file.blob.cache_control = 'public, max-age=31622400'
        # Modification end
        file.blob.upload_from_file(content, size=content.size,
                                   content_type=file.mime_type)
        return cleaned_name

```

@ezarowny, thanks for sharing api for this.

**Comment by zamai** [comment]
Thanks for sharing, @gfhuseyinyilmaz   wouldn't it be nice to have it as a setting? The same way it is for S3?
http://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html?highlight=CacheControl

**Comment by cerny-jan** [comment]
Hi, I've opened a PR for this https://github.com/jschneier/django-storages/pull/459

**Comment by erikkn** [comment]
@zamai It would be nice to have it as a setting, but most of the time you want different headers for different type of files, this would be a really nice feature imho.

**Comment by nbau21** [comment]
Is this project still active? This setting seems like a necessity as not everyone wants `no-cache`. There seems to be a PR for this with tests failing for some reason.

**Comment by nbau21** [comment]
Thanks for the response. It's the beauty of open source, anyone can chime in, fork, etc.

Also thanks for merging this to master. I didn't mean to sound entitled in my previous post- I guess I was a bit frustrated at the lack of support for Google Cloud Storage in Django,  compared to AWS.

**Comment by afhaider** [comment]
Original storage not defined
