### ISSUE TITLE
Add support for AWS_S3_HOST to the boto3 backend

### ISSUE THREAD

**Issue by hhowe29** [jschneier/django-storages#418]
Issue is a TODO in the code at this line: https://github.com/jschneier/django-storages/blob/aa0cd4455e5f76f83f55b0265d8c21168e91921c/storages/backends/s3boto3.py#L255

The host can be overridden by passing `endpoint_url` to `session.resource`

```
s3 = session.resource(
    service_name='s3',
    endpoint_url='http://localhost:8088'
)
```

**Note** working on a PR for this

**Comment by jschneier** [comment]
Yep. I don't think we needed that part of the comment.
