### ISSUE TITLE
Why not rename this repository to django-storages-redux?

### ISSUE THREAD

**Issue by luzfcb** [jschneier/django-storages#42]
Hello, I think it would make sense to change the repository name to the same name of the package in pypi, other words, change name to `django-storages-redux` and publish django-storages-redux documentation on ReadTheDocs.

If you are interested, I can send a pull-request changing any reference of `django-storages` to `django-storages-redux`, except the name of the app to continue compatible without changes. (I think they will change only in the documentation)

ok, also think it would make sense to change too the app name to `storage_redux` , to avoid mistakes (example: confuse the names and install the original version and not this fork).

If you have no interest, no problems, everything remains as it is.

**Comment by afs2015** [comment]
I agree with luzfcb, less confusion.

**Comment by powdahound** [comment]
:+1:

**Comment by NejcZupec** [comment]
:+1:

**Comment by paulshannon** [comment]
++1 For the docs getting pushed to rtfd... Happy to help set it up if need be.

**Comment by jschneier** [comment]
Definitely agree with the docs bit, that has been something I have been dragging my feet on some.

This repository was initially named `django-storages-redux` but I changed it...for a few reasons I guess, chief among them being that I wanted to make it easier for you all (users) to integrate with as little pain as possible. I copied the 'redux' bit from the fork of [another well known project](https://github.com/macropin/django-registration).

**Comment by matheusjardimb** [comment]
+1

**Comment by nym** [comment]
:+1:

**Comment by ZuluPro** [comment]
This issue can be closed I think ;)

**Comment by jschneier** [comment]
I can now release as `django-storages` so I think this can be closed.

**Comment by derek-adair** [comment]
@jschneier -  FANTASTIC NEWS.  you should make this VERY clear in the README.  this has pretty major repercussions and is quite confusing if you've not stayed up on this repository.  I've been developing against django-storages-redux 1.2.3 since I started a new project about 2 weeks ago because I missed this.
