### ISSUE TITLE
Does a backend for Google Drive / OneDrive make sense?

### ISSUE THREAD

**Issue by jorgeas80** [jschneier/django-storages#421]
Hello,

I was thinking about implementing a backend for Google Drive and/or OneDrive. And I was wondering why it doesn't exist yet. Is just lack of hands / interest / time or is there any other technical constraint I am missing?

Sorry if this is not the place to ask this type of questions. Don't hesitate to close the issue, given the case.

**Comment by stinky2nine** [comment]
Google Drive and Microsoft OneDrive aren't meant for CDN (content delivery network) even though their storage systems are most likely being replicated in multiple locations for availability. Google Cloud Storage, Amazon CloudFront and a few others are designed for CDN.

**Comment by jorgeas80** [comment]
And Dropbox? There is a Dropbox backend. What's the difference?

**Comment by stinky2nine** [comment]
I am not a django-storages maintainer so just giving my two cents here. Dropbox is not CDN, but I can understand why developers might want to upload media and user files to Dropbox in Django. [This article](https://codient.blogspot.com/2016/12/dont-use-dropbox-as-cdn.html) is a good read, for not using Dropbox as CDN.

**Comment by stinky2nine** [comment]
I definitely will not put static files on Google Drive/Microsoft OneDrive/Dropbox. For user upload files, sure, I think there are use cases for using Drive/OneDrive.

**Comment by slrsoft** [comment]
For me Google Drive & Onedrive make perfect sense, not as CDN but very useful for other purposes - if you implement this it would be a great addition!

**Comment by jorgeas80** [comment]
@stinky2nine thanks for the link. 

I'm not planning to use OneDrive/Google Drive for static files, but for other purposes, like @slrsoft said (user content, Word files to allow online editing...). So, I think I'll try it :-)

**Comment by ZuluPro** [comment]
It totally makes sense to have Google Drive/OneDrive in django-storages.
The requirements could be:
- To be an object storage
- Allow to list
- Allow to download/upload
- Allow to share an URL to this file

We are very opened to pull requests ;)

**Comment by calvin** [comment]
In the meantime, there is an alternative implementation for Google Drive: http://django-googledrive-storage.readthedocs.io

**Comment by jschneier** [comment]
I'm going to say please go ahead use that already existing implementation!
