### ISSUE TITLE
Google Cloud Storage urls getting expired

### ISSUE THREAD

**Issue by gbrennon** [jschneier/django-storages#425]
How to prevent ExpiredToken for files url?

My files are public and I can visit them only with the name of the file, but django-storages continues to generate urls that expire...

How can I do this? I want to be able to send uploaded files url to people

**Comment by helloagain-dev** [comment]
I have the same issue.
The S3 Storage has an option to disable this.

It would be great to have an option for the url call to get a signed URL or the public URL as some of my files are public and some are private.

**Comment by ThunderTrent** [comment]
I have the same issues -- and would desire that option as well.

**Comment by jschneier** [comment]
This has been fixed in #570.
