### ISSUE TITLE
Move file on S3

### ISSUE THREAD

**Issue by JulianSchneider** [jschneier/django-storages#428]
Is there a built in way to move a file on the bucket from the backend?

**Comment by sww314** [comment]
There is no "move" Django API https://docs.djangoproject.com/en/2.0/ref/files/storage/
So, it is not included, but you could easily create on to use the underlying library. 
Not sure about S3, but for Google Cloud, you just need rename_blob
https://googlecloudplatform.github.io/google-cloud-python/latest/storage/buckets.html#google.cloud.storage.bucket.Bucket.rename_blob

**Comment by ambientlight** [comment]
they opted against doing this(https://code.djangoproject.com/ticket/20488) because of https://github.com/django/django/pull/4244#discussion_r28963656

**Comment by Madalosso** [comment]
Wouldn't make sense though, to implement a `copy` method on top of the default storage since as @sww314 pointed, google cloud storage has it? (And boto3 as well for S3).
