### ISSUE TITLE
Handle Blob setup in Azure DE

### ISSUE THREAD

**Issue by nfpp** [jschneier/django-storages#439]
Probably because of using scheme http://azure_account_name.blob.core.windows.net/, we are not able to use Blob setup on DE infrastructure with endpoint: https://xxx.blob.core.cloudapi.de/, is there already an option to overwrite this default url?

**Comment by go-bin** [comment]
yeah, We also need to use Blob setup on China infrastructure with endpoint: https://xxx.blob.core.chinacloudapi.cn

**Comment by sww314** [comment]
The azure backend was rewritten in #565. Please reopen or comment if this is still an issue. (New version is on master and in pip release).
