### ISSUE TITLE
Set public-read ACL for collectstatic, everything else private

### ISSUE THREAD

**Issue by brycefisher** [jschneier/django-storages#440]
I want to allow admin users to upload private files, but make the static assets for django admin public-read. What's the best way to achieve this?

I'm imagining I can probably achieve what I want to do by fiddling with IAM permissions, but I'm trying to understand if there's another way to do this inside my application.

**Comment by sww314** [comment]
Storages does not support this. There have been some suggestions about how to handle, but no concrete work.
