### ISSUE TITLE
Add support for the 'Infrequent Access' S3 Storage Class

### ISSUE THREAD

**Issue by tveastman** [jschneier/django-storages#447]
Currently, django-storages supports the STANDARD storage class and the REDUCED_REDUNDANCY storage class.

Amazon appear to be phasing out REDUCED_REDUNDANCY, and in fact, it's more expensive now than STANDARD.

There's a new class, "infrequent access" (`STANDARD_IA`) for which we should add support.

This'll be easy in `s3boto3.py`, but it might be trickier with `s3boto.py`

**Comment by jschneier** [comment]
Closing in favor of #549. Thanks for the suggestion.
