### ISSUE TITLE
Public and private objects on S3 via Cloudfront?

### ISSUE THREAD

**Issue by mrmachine** [jschneier/django-storages#456]
The django-storages docs just say I should set the `AWS_S3_CUSTOM_DOMAIN` setting and configure Cloudfront. The Cloudfront docs say I can restrict access and require signed URLs.

I already use signed S3 URLs with django-storages, and these URLs have `Expires`, `Signature` and `AWSAccessKeyId` querystring params. The Cloudfront docs say signed cloudfront URLs need `Expires`, `Signature` and `Key-Pair-Id` querystring params.

How can I get `django-storages` to generate a signed Cloudfront URL? Is it even possible?

**Comment by terencehonles** [comment]
@mrmachine if you use the branch that is #587 you can specify one or more RSA keys and the signing function will use the first key or the key by the ID you specify.

**Comment by DataGreed** [comment]
Is there an existing solution for this problem?

**Comment by DataGreed** [comment]
@jschneier @terencehonles  it's great the django-storages supports Cloudfront URL Signing, but there seems to be no documentation at all. How do I make it work?

**Comment by terencehonles** [comment]
@DataGreed it looks like you figured it out and posted an example on #587, I commented there, but any chance you want to expand the documentation? :slightly_smiling_face:

**Comment by shawnngtq** [comment]
@DataGreed 

It will be great if you can include an example regarding cloudfront settings. I am new to cloudfront and this library 😁

**Comment by terencehonles** [comment]
@shawnngtq you can use @DataGreed and my comments starting here https://github.com/jschneier/django-storages/pull/587#issuecomment-628681209 to probably get yourself set up :slightly_smiling_face:
