### ISSUE TITLE
AWS removing support for SSLv3

### ISSUE THREAD

**Issue by k4ml** [jschneier/django-storages#46]
I guess this also will affect this project, although all it need probably just picking up the latest boto release but just some heads up - https://github.com/boto/boto/issues/3103

**Comment by jschneier** [comment]
Thanks for the heads up, will double check nothing breaks here.

**Comment by jschneier** [comment]
Upstream indicates that (basically) no one has an OpenSSL version that doesn't support TLS > 1.0 which is what is needed and the fix is to upgrade OpenSSL given that.
