### ISSUE TITLE
Method 'get_created_time' is abstract in class 'Storage' but is not overridden

### ISSUE THREAD

**Issue by mikekeda** [jschneier/django-storages#465]
I noticed that few abstract method aren't implemented for GoogleCloudStorage: get_accessed_time, get_created_time and path.

I debuged a response from Google storage and as I see we have an info about created_time.
https://googlecloudplatform.github.io/google-cloud-python/latest/storage/blobs.html#google.cloud.storage.blob.Blob.time_created
Maybe it's not so useful, but I don't like pylint warning :)

I created a PR with a fix - #464

P.S. There was a plink error in ftp.py that failed the build, so I fixed it, hope it's correct fix.

**Comment by jschneier** [comment]
Resolved in #464.
