### ISSUE TITLE
Using str in AWS_HEADERS causes spaces to be escaped!

### ISSUE THREAD

**Issue by ka7eh** [jschneier/django-storages#47]
See: https://github.com/boto/boto/issues/2536

If I set <code>AWS_HEADERS</code> as
<code>{'Cache-Control':  'max-age=%d, s-maxage=%d, must-revalidate' % (AWS_EXPIRY, AWS_EXPIRY)}</code> (notice spaces), it will render to <code>'max-age=604800,%20s-maxage=604800,%20must-revalidate'</code>.
Encoding the string as bytestring solved my problem on Django 1.7.7 and python3, but I didn't do any thorough testing.

<pre>
AWS_HEADERS = {
    'Cache-Control': str.encode(
        'max-age=%d, s-maxage=%d, must-revalidate' % (
        AWS_EXPIREY, AWS_EXPIREY))
}
</pre>

**Comment by jschneier** [comment]
Hi and thanks for the report. Seems like this might be a boto issue so I'm going to do a little digging there before I patch anything in this library.

**Comment by jschneier** [comment]
The only okay idea I have for fixing this is to turn everything into a byte string when I first read it out of the settings file. Thoughts on that?

**Comment by ka7eh** [comment]
Hi @jschneier 
Is it only `AWS_HEADRES` which needs conversion or there are other settings that needs to be fixed?

**Comment by busla** [comment]
subscribing

**Comment by jschneier** [comment]
This is a ``boto`` issue and that backend has been deprecated.

**Comment by jschneier** [comment]
This is a ``boto`` issue and that backend has been deprecated.
