### ISSUE TITLE
Confusion between AWS_S3_SECURE_URLS, AWS_S3_USE_SSL, AWS_S3_URL_PROTOCOL

### ISSUE THREAD

**Issue by siyu6974** [jschneier/django-storages#472]
I found it very confusing and not very well documented for these 3 settings.
```
AWS_S3_SECURE_URLS
AWS_S3_USE_SSL
AWS_S3_URL_PROTOCOL
```

**Comment by jschneier** [comment]
Yeah that is fair. `AWS_USE_SSL` is about the connection to S3 (like your server to S3). It was introduced here 6071ac3410ee6ecd498b5691f1b45d376374bffc and was in the codebase before the fork. I'm not really sure if it should be around anymore.

The other two are about constructing urls. In the legacy backend you could specify for boto to give you an http link but the api changed between boto and boto3 so right now it (`AWS_S3_SECURE_URLS`) doesn't do too much in boto3 although for backwards-compat and safety reasons it sets `url_protocol` to `https:` when it is `True` (the default). `AWS_S3_URL_PROTOCOL` is for setting the protocol if you are using a custom domain (Cloudfront or similar) and want to force http.

The settings need to be cleaned up and the documentation updated. Removing the boto backend will really help.

**Comment by jschneier** [comment]
Resolved by #1164.
