### ISSUE TITLE
Project Release Versioning

### ISSUE THREAD

**Issue by dsanders11** [jschneier/django-storages#474]
The most recent release, 1.6.6, "dropped support" for Django 1.8 and 1.10 even though it was a (micro, patch, whatever you prefer to call it) version point release. Support for Django 1.7 was dropped in version 1.5.1.

I'm going to politely ask that a bit more care be put into version numbers. It's standard practice that the smallest number in the version string (the micro, or patch number) contain only backwards-compatible changes, and usually just fixes. Dropping support for entire versions of Django is a big no-no.

It makes life a lot more complicated when major breaking changes like that get snuck into otherwise seemingly harmless (going by the version number) updates, especially when that version also contains fixes.

**Comment by jschneier** [comment]
It should have gone to 1.7, agreed.
