### ISSUE TITLE
Documentation 1.6.5 Incomplete

### ISSUE THREAD

**Issue by jaradc** [jschneier/django-storages#475]
https://django-storages.readthedocs.io/en/1.3.2/backends/amazon-S3.html shows:

```
>>> from django.core.files.storage import default_storage
>>> from django.core.files.base import ContentFile
>>> from django.core.cache import cache
>>> from models import MyStorage
```

[Documentation 1.6.5](https://django-storages.readthedocs.io/en/1.6.5/backends/amazon-S3.html) is missing this critical piece. I was totally clueless what `MyStorage` meant.

I think a lot more examples on how to retrieve files from Django would be extremely helpful. I've literally been doing dir(default_storage) and trying to figure out how to actually apply this easily in my Django project. I don't know what I'm doing but more examples would go a long way.

**Comment by f3n1Xx** [comment]
#493 i was just reading this issue, is it implemented already?

**Comment by sww314** [comment]
@jaradc Could you provide something more specific in terms of documentation? 
If you are just starting to use the library you have the best perspective of what is missing.

**Comment by jaradc** [comment]
Use CTRL + F in your browser. Search for "MyStorage". It's not defined anywhere in 1.6.5 documentation but it's used in several places. Now look at documentation 1.3.2 and do the same thing. It IS defined (imported). Hence, documentation in 1.6.5 is very confusing if a new user tries to use the examples without knowing what the object "MyStorage" actually is.
