### ISSUE TITLE
Update API Azure

### ISSUE THREAD

**Issue by Yyandrakk** [jschneier/django-storages#476]
The Azure API version is 0.36.0, but django-storages is 0.2

**Comment by jedie** [comment]
Is azure-storage v0.20.0 the latest supported version?!? I din't find information about that :(

**Comment by jedie** [comment]
Any news here?

**Comment by hcjdavids** [comment]
This is still an issue. The Azure API has been updated and split into different packages now with lots of breaking changes: https://github.com/Azure/azure-storage-python

**Comment by sww314** [comment]
Closed in favor of #565

**Comment by sww314** [comment]
Closed in favor of #565
