### ISSUE TITLE
New logo for Django-storages

### ISSUE THREAD

**Issue by reallinfo** [jschneier/django-storages#483]
I wanted to contribute to django-storages. I designed a logo for it. If you like it, I'll send you files and pr.
is there anything you want ?

![djangostorages](https://user-images.githubusercontent.com/36298335/39788037-1926a9ee-5331-11e8-9073-9c32f3f06f45.jpg)

**Comment by jschneier** [comment]
Thanks, looks great! Feel free to email it to me if you prefer (email is public on Github). I’ll add it to the README and will give you attribution/a link to your site if you’d like.

**Comment by reallinfo** [comment]
sure, all the files are here.

https://drive.google.com/drive/folders/1R9tSxkl4fnF1tUS9rdqyT-kGlPAXBn1l

Thank you :)

2018-04-15 8:58 GMT+03:00 Josh Schneier <notifications@github.com>:

> Thanks, looks great! Feel free to email it to me if you prefer (email is
> public on Github). I’ll add it to the README and will give you
> attribution/a link to your site if you’d like.
>

**Comment by jschneier** [comment]
Added to the README in 977cc390b83743f27ca69d3315b30167d712d84a. When I redo the documentation for 2.0 I'll be sure to use it there as well. Thanks so much again!
