### ISSUE TITLE
sftp.SFTPStorageFile doesn't properly call it's parent __init__

### ISSUE THREAD

**Issue by lakinwecker** [jschneier/django-storages#487]
Django's file object assumes it has a `.name` attribute, like in the `__bool__` method here: https://github.com/django/django/blob/1.11.12/django/core/files/base.py#L31-L32

It does so, because it sets this attribute in its constructor here: https://github.com/django/django/blob/1.11.12/django/core/files/base.py#L19-L21

However, the `sftp.SFTPStorageFile` object does not call that constructor:  https://github.com/django/django/blob/1.11.12/django/core/files/base.py#L19-L21

Simply adding in `super(SFTPStorageFile, self).__init__(file=self.file, name=self._name)` at the end of that method solves the issue. I'm not setup to make a PR at the moment, or this would also include a PR. I'm happy to make one later today.

**Comment by abeelen** [comment]
I came across the same issue, and found basically the same solution fiddling around the `__init__`. It seems that you fixed much more with #489 ! Any chance to get it passing the unit tests ?

**Comment by lakinwecker** [comment]
I would love to, but I haven't had the time to get them setup and running locally. :(

**Comment by jschneier** [comment]
I have opened the rebased version at #558 to play with the tests, sorry for the delay.

**Comment by jschneier** [comment]
Sorry inadvertently closed this one.
