### ISSUE TITLE
Collectstatic creates multiple files, some empty

### ISSUE THREAD

**Issue by apiljic** [jschneier/django-storages#488]
Not sure if this is a django-storages issue, but maybe someone has an idea. 
I am upgrading an app...

Current versions:
```
django 1.8.17 
django-storages 1.5.1
```

Goal:
```
django 1.11.12
django-storages 1.6.6
```

Storage:
```
class StaticS3BotoStorage(ManifestFilesMixin, S3BotoStorage):
    location = 'static'
    file_overwrite = True
    preload_metadata = True
```
or
```
class StaticS3BotoStorage(CachedFilesMixin, S3BotoStorage):
    location = 'static'
    file_overwrite = True
    preload_metadata = True
```

With the initial setup, collectstatic worked fine, including collectstatic --clear.

After the upgrade, collectstatic --clear fails (no files are deleted).
collectstatic does copy files, however, sometimes it creates two versions of the same file. In this particular example, I get base.hash1.css and base.hash2.css. base.hash2.css is empty, so pages open, but do not render correctly.

If I don't use CachedFilesMixin or ManifestFilesMixin, collectstatic works fine, but clear still fails.

I tested different combinations of django 1.11 and all version of django-storages 1.6.0 to 1.6.6. They all seem to behave the same.

**Comment by philipplaeubli** [comment]
We've encountered the same issue here, as described in https://stackoverflow.com/questions/49999582/collectstatic-creates-empty-files/51270732#51270732

The same ContentFile instance is being saved multiple times by `ManifestFilesMixin`.

For the time being, we've worked around it by overriding the `_save` method like this 

```python3
class PatchedS3StaticStorage(S3StaticStorage):
    def _save(self, name, content):
        if hasattr(content, 'seek') and hasattr(content, 'seekable') and content.seekable():
            content.seek(0)
        return super()._save(name, content)
```

Be aware, that we haven't yet tested this in a production like environment and we are not sure if this has a negative implications on media/FileFields. 

We're currently not sure if this is a issue of the django-storages, boto or the ManifestFilesMixin of django 1.11.

**Comment by philipplaeubli** [comment]
@apiljic: About the multiple files - in my tests, these were generated no matter which storage backend I've used. For me, this seems to be an issue of django 1.11 and is not related to django-storages.

**Comment by apiljic** [comment]
Thanks Philipp for your feedback. I was struggling with this. With boto3 collectstatic worked fine, but media upload not. So the intermediary solution was to use boto3 for static, boto for media. 

However, due to memory issues (described here: https://github.com/jschneier/django-storages/issues/95), we had to stop using django-storages in the end. We have many thumbnails and it was eating too much memory.

**Comment by jonnyscholes** [comment]
I had the same issue. Thanks for the help @philipplaeubli and @apiljic it made all the difference! 

If anyone else is having the same issue my full solution is [in this SO question](https://stackoverflow.com/questions/52309821/collectstatic-incorrectly-creates-multiple-css-files-in-s3/52323409#52323409). I'm using boto3 for both media and static files - although only my static files are using `ManifestFilesMixin` (or `ManifestStaticFilesStorage` to help Googlers find this).

**Comment by jschneier** [comment]
This was resolved a little while ago.
