### ISSUE TITLE
Files not overwritten when "collectstatic" run multiple times

### ISSUE THREAD

**Issue by mvanderlinde** [jschneier/django-storages#49]
I believe this is the same issue that was reported in the original django-storages here: https://bitbucket.org/david/django-storages/issue/167

When I run "collectstatic" more than once within a few hours, no files are recognized as modified.

**Comment by jaylett** [comment]
It almost certainly is. There's a [PR against the upstream](https://bitbucket.org/david/django-storages/pull-request/102/fixing-timezone-comparison-in-s3/diff) that looks credible to me.

**Comment by CarlosBorroto** [comment]
+1, please look into the existing PR, we also got hit by this issue.

Thanks!

**Comment by jaylett** [comment]
Note that Django's API for this is changing from 1.10 (with a deprecation path). The previous fix is still a good idea, but there's a new set of methods to implement that provide full timezone support (and so consistency with the rest of Django).

**Comment by jschneier** [comment]
Fixed by #290
