### ISSUE TITLE
Google Cloud backend not a very good replacement for Django's Media or Static handling

### ISSUE THREAD

**Issue by elnygren** [jschneier/django-storages#491]
The Google cloud backend isn't a very good candidate for Django's Media or Static files storage backend without some additional configuration and studying the sources. Ideally, the docs would talk a little bit about issues such as #463 #413 

Here's my solution:

```python
"""
GoogleCloudStorage extensions suitable for handing Django's
Static and Media files.

Requires following settings:
MEDIA_URL, GS_MEDIA_BUCKET_NAME
STATIC_URL, GS_STATIC_BUCKET_NAME

In addition to
https://django-storages.readthedocs.io/en/latest/backends/gcloud.html
"""
from django.conf import settings
from storages.backends.gcloud import GoogleCloudStorage
from storages.utils import setting
from urllib.parse import urljoin


class GoogleCloudMediaStorage(GoogleCloudStorage):
    """GoogleCloudStorage suitable for Django's Media files."""

    def __init__(self, *args, **kwargs):
        if not settings.MEDIA_URL:
            raise Exception('MEDIA_URL has not been configured')
        kwargs['bucket_name'] = setting('GS_MEDIA_BUCKET_NAME', strict=True)
        super(GoogleCloudMediaStorage, self).__init__(*args, **kwargs)

    def url(self, name):
        """.url that doesn't call Google."""
        return urljoin(settings.MEDIA_URL, name)


class GoogleCloudStaticStorage(GoogleCloudStorage):
    """GoogleCloudStorage suitable for Django's Static files"""

    def __init__(self, *args, **kwargs):
        if not settings.STATIC_URL:
            raise Exception('STATIC_URL has not been configured')
        kwargs['bucket_name'] = setting('GS_STATIC_BUCKET_NAME', strict=True)
        super(GoogleCloudStaticStorage, self).__init__(*args, **kwargs)

    def url(self, name):
        """.url that doesn't call Google."""
        return urljoin(settings.STATIC_URL, name)
```

**Comment by nbau21** [comment]
Thanks for doing the legwork. I tried implementing this snippet but I keep getting nulls. Am I missing something?

in settings.py:
```
DEFAULT_FILE_STORAGE = 'api.storage.backends.GoogleCloudStaticStorage',      // I put the above code inside api/storage/backends.py, where api is the app name                                                               
GS_BUCKET_NAME = my-bucket-name,                                                                                      
GS_STATIC_BUCKET_NAME = my-bucket-name 

STATIC_URL  = ''                                                                 
```

And my images are in `gs://my-bucket-name/images` and `gs://my-bucket-name/thumbnail`

**Comment by edevil** [comment]
Maybe a PR to the docs would move this along? Thanks for your work.

**Comment by chrishiestand** [comment]
@elnygren And where does your file get stored?

**Comment by chrishiestand** [comment]
n/m - I realized you reference these from

```python
STATICFILES_STORAGE = 'googlecloudstorage.GoogleCloudStaticStorage'
DEFAULT_FILE_STORAGE = 'googlecloudstorage.GoogleCloudMediaStorage'
```

So you just need to store them in such a way as python can find them.

**Comment by jschneier** [comment]
Okay, so as currently written we hit Google every time `.url` is called. This is obviously substandard for performance reasons. This is really easy to update this is taken from the Google Cloud library, PR anyone?

```    @property
    def public_url(self):
        """The public URL for this blob's object.

        :rtype: `string`
        :returns: The public URL for this blob.
        """
        return '{storage_base_url}/{bucket_name}/{quoted_name}'.format(
            storage_base_url=_API_ACCESS_ENDPOINT,
            bucket_name=self.bucket.name,
            quoted_name=quote(self.name.encode('utf-8')))
```

No one has asked for signed urls yet but we'll need them eventually I think. Amazon is nice because it's on the bucket whereas for this we need to fetch the blob.

**Comment by sheepeatingtaz** [comment]
Not sure if this is the place, as it seems like I'm hijacking another issue, but..

> No one has asked for signed urls yet but we'll need them eventually I think.

I'd like signed URLs, please! See My PR https://github.com/jschneier/django-storages/pull/326 or the one that extends it further https://github.com/jschneier/django-storages/pull/399

I know for mine, I've just not had the time or experience to see how to fit it in with the tests, but could help add documentation, if it would help

**Comment by xtechgamer735** [comment]
As someone looking to implement this in a django project, is it really the way forward with these issues that have been raised? The lack of documentation made me uneasy in the first place as I am new to Django but I can find anything else.

Im struggling to see at first how I implement this but I can get my head around it if its worth it.

**Comment by sww314** [comment]
@xtechgamer735 I use this project in production on with Google Cloud Storage. There are some issues that are being worked, but the project is actively maintained.
 
Personally, I do not use GCS for static file storage (try this instead: http://whitenoise.evans.io/en/stable/) is simplier without the fragile deployment to a 3rd party network storage solution. Instead, I use it for media storage and it works fine with only a few configuration settings.

**Comment by xtechgamer735** [comment]
@sww314 Ah thanks for the link! That looks great.

I think GCS is the best way forward for me, it was the comment regarding inefficient url usage that got me most worried. Is that nothing really to be concerned about?

If you don't mind me asking what type of data are you storing?

**Comment by jschneier** [comment]
Okay so I think what we want is essentially what we have in the boto backends:

if Custom URL: Return that
if Signed URL: Fetch the blob and return the generated signed url
Otherwise: 
```python
name = self._encode_name(self._normalize_name(clean_name(name)))
return 'https://storage.googleapis.com/{}/{}'.format(self.bucket_name, quote(name, safe=''))
``` 

I ripped that out of the Google Cloud storage library, can someone try that out and confirm it at least passes a sanity check?

**Comment by jschneier** [comment]
Yep, you are right.
