### ISSUE TITLE
Help Support for Google Cloud Storage

### ISSUE THREAD

**Issue by sww314** [jschneier/django-storages#492]
@jschneier There are quite a few issues with the with Google Cloud Storage support. I have several projects supporting this environment. 

Are you open to more help on the project? I would be happy to help.

**Comment by aronasorman** [comment]
@sww314 Hey! Any progress on this? I'm currently encountering a couple issues myself and I'm wondering if you want to share notes.

I'm having trouble with files greater than 5 MB, basically anything using the `_do_multipart_upload` path seems to be erroring out. I first tried to find a combo of `django-storages` and `google-cloud-storage` that would work, but that didn't pan out.

**Comment by sww314** [comment]
@aronasorman I am using a personal branch right now, but have not addressed all the issues yet because of other issues in my projects. If there is interest I can publish mine.

**Comment by sww314** [comment]
@jschneier - hey just checking on this. I am using the Google Cloud Storage for a couple of projects and I am about to do some upgrades. I would like to do in the context of the project instead as a branch.

**Comment by jschneier** [comment]
@sww314 just invited you as a collaborator, thanks for the offer.
