### ISSUE TITLE
implement backend for storing files in DB?

### ISSUE THREAD

**Issue by danner** [jschneier/django-storages#493]
Testing environments often need to create files, but managing them can get annoying. 

Would a PR that implemented this have a chance of being accepted? The functionality would be like 

- https://github.com/tyrelsouza/django-dbfilestorage
- https://github.com/mmueller/django-database-storage
- https://github.com/victor-o-silva/db_file_storage
- https://github.com/bfirsh/django-database-files
- https://github.com/derekkwok/django-db-storage

There seems to be a need for this, but no consistent way of creating it. The difference is that db file storage requires a url and get view, which other storages in django-storages do not need, so there'd be an adjustment to the pattern found here.

**Comment by ZuluPro** [comment]
I don't think it's a good idea to include test storages in this project.
Otherwise for tests, I would use a dict in-memory storage, in cache or on temporary file.
(Like here: https://github.com/ZuluPro/django-dbbackup/blob/master/dbbackup/tests/utils.py#L40)

**Comment by fquinner** [comment]
It would be useful in my current project where the django runtime environment is in docker (and is only a rest backend), the database is external, and the command line management interface is on the docker host. It means you could store new files in a meaningful way for django without having to access any files inside the django container and without requiring access keys for third party storage.

**Comment by sww314** [comment]
There are multiple other options available as listed in the request. I would suggest using one of them.
