### ISSUE TITLE
Can't upload a file of 100MB with Azure blob

### ISSUE THREAD

**Issue by bmoe872** [jschneier/django-storages#494]
I'm trying to upload a file thats ~133MB in size, but I am getting errors like:
`MemoryError`
or
`The request body is too large and exceeds the maximum permissable limit`

This is using a Django FileField. 

Do I need to change the file-field to something else?

Other Specs:
Django 1.11
Django Storages 1.6.5
Azure storage 0.20.0

**Comment by sww314** [comment]
Azure backend was rewritten in #565. Please reopen if the issue still exists.
