### ISSUE TITLE
cannot import name SpooledTemporaryFile

### ISSUE THREAD

**Issue by learner-01** [jschneier/django-storages#495]
I have a django project which is going to be hosted in AppEngine.
I tried using Django-Storages to save file to GCS.
When I run the app locally via manager.py, I dont get any error. My file is being uploaded to bucket as well.
But If I run the app either via dev_appserver or deployed version in GAE, I get the below error:
```python
cannot import name SpooledTemporaryFile
```

The page containing the form wont open and keeps on giving this error.
I even tried the suggestion to use monkey patch, I changed the appengine_comfig.py to.
```python
from google.appengine.ext import vendor

vendor.add('lib')
import tempfile
tempfile.SpooledTemporaryFile = tempfile.TemporaryFile
```
But after this I get another error:
```python
ImproperlyConfigured: Could not load Google Cloud Storage bindings.
```

kindly help..

**Comment by sww314** [comment]
Please request support on StackOverflow or in chat.
