### ISSUE TITLE
S3 Storage - delay in serving the page

### ISSUE THREAD

**Issue by caliph007** [jschneier/django-storages#496]
I migrated the static files of a large website to S3 using django-storages.

When I open a large page, django creates network traffic for 5-60 seconds to AWS until it starts serving the page and the client browser then downloads the static assets from S3 (very fast).

What is django-storages doing after requesting a url from the server?
Why the delay in serving the html?

**Comment by kitsunde** [comment]
Make sure your files are public and set `AWS_QUERYSTRING_AUTH = False`, it should stop the backend from generating an auth signature for each file.

**Comment by lemuelf** [comment]
> Make sure your files are public and set AWS_QUERYSTRING_AUTH = False, it should stop the backend from generating an auth signature for each file.

That doesn't seem to be the case.  If you check https://github.com/jschneier/django-storages/blob/1.7.1/storages/backends/s3boto3.py#L622-L626 `S3Boto3Storage` generates a URL with a signature regardless of `AWS_QUERYSTRING_AUTH` setting _and then_ strip out the signing parameters if `AWS_QUERYSTRING_AUTH = False`.

It seems the only way to prevent `S3Boto3Storage` from generating presigned URLs, and make Django respond without much delay, is to set the `AWS_S3_CUSTOM_DOMAIN` setting as can be seen in https://github.com/jschneier/django-storages/blob/1.7.1/storages/backends/s3boto3.py#L613-L615.
