### ISSUE TITLE
Second file upload override first one, if have same name

### ISSUE THREAD

**Issue by matheusjardimb** [jschneier/django-storages#50]
Here is the scenario:
- Model Product has a image field;
- User uploads an image to its product
- Another user uploads another image to another product 
- First image gets overriden.

Is it a problem that django-storages should fix or should I rename the file to make it unique by user?

**Comment by matheusjardimb** [comment]
At this time, I'll solve by creating folders by users:
````
import os
def get_upload_path(instance, filename):
    return os.path.join(
      "user_%d" % instance.owner.id, "car_%s" % instance.slug, filename)
````
then:

````photo = models.ImageField(upload_to=get_upload_path)````

**Comment by agriffis** [comment]
What backend are you using? If s3boto, the problem might be that the default is `AWS_S3_FILE_OVERWRITE = True`. This makes sense for static files but not for media files.

You probably want a separate storage class for media, something like this:

```python
class MediaS3BotoStorage(S3BotoStorage):
     location = 'media'
     file_overwrite = False  # override default AWS_S3_FILE_OVERWRITE=True
```

**Comment by tarkatronic** [comment]
If you are only using storages for user media and not for static media, then you can simply add the setting: `AWS_S3_FILE_OVERWRITE = False`

**Comment by galuszkak** [comment]
That saved my skin! Thanks @agriffis . Maybe we should include that in documentation?

**Comment by camilonova** [comment]
Where would be the best place to document this? I can to that.

**Comment by scripterkaran** [comment]
+1 In my case it does not override it just uses the old file. 

example: I have an image.jpeg at bucket. If I upload another image with same name "image.jpeg", it just uses the older file. 

Any Solution?

**Comment by glassresistor** [comment]
+ 1 please document this early on people on heroku will hit this and be confused(helping friend on heroku)

**Comment by jschneier** [comment]
This is documented.
