### ISSUE TITLE
Overriding the default AWS ACL for specific fields

### ISSUE THREAD

**Issue by pieterdd** [jschneier/django-storages#501]
I use `S3Boto3StorageBackend` with an implicit `AWS_DEFAULT_ACL` of `public-read`. That is the desired value for 90% of my uploads. However, I want one FileField in one model to upload with an ACL of `bucket-owner-read`.

What would be the best way to achieve this? Is there an option to override the default ACL on field level?

**Comment by jschneier** [comment]
You should be able to pass `storage=s3boto3.S3Boto3Storage(default_acl='bucket-owner-read')` to your model field. Does that not work?

**Comment by pieterdd** [comment]
I ended up going with a similar solution. I wrote a class inheriting from `S3Boto3Storage` that overrides the `default_acl` attribute and passing that as the `storage=` argument.

**Comment by jschneier** [comment]
Sorry but why did you need to override at all?

**Comment by pieterdd** [comment]
To make reuse slightly easier. This way I can apply the same class to other fields.
