### ISSUE TITLE
No way to upload files with headers using Google Cloud Storage

### ISSUE THREAD

**Issue by ReconCubed** [jschneier/django-storages#510]
I'm using Google Cloud Storage and currently have to either manually or script the setting of my Content-Disposition headers. The amazon module supports this but GCS does not?
I believe it should be implemented in a similar way, 
```python
GS_HEADERS = {
    'Expires': 'Thu, 15 Apr 2010 20:00:00 GMT',
    'Cache-Control': 'max-age=86400',
    'Content-Disposition': 'attachment',
}
```

**Comment by jschneier** [comment]
I think a setting with a dotted path to a function that receives…something…is useful for nearly every backend.

**Comment by JeffreyCA** [comment]
There's no way to set headers using Azure Storage either.

**Comment by JeffreyCA** [comment]
This is now possible as of v1.11 (see #898). Just add the following to your Django configuration:
```py
AZURE_OBJECT_PARAMETERS = {
    'content_disposition': 'attachment'
}
```
