### ISSUE TITLE
Release Django 1.8 support

### ISSUE THREAD

**Issue by stianjensen** [jschneier/django-storages#53]
Hi! I see that the currently unreleased v1.3 includes fixes for Django 1.8

When will it be released on pypi?

**Comment by ALenfant** [comment]
Hi, also interested, I'd like a true release.
1.8 is a LTS release, so this would be very appreciated!

**Comment by jschneier** [comment]
Hi I'm going to work on this now. There are a couple pull requests that reorder the mixin classes for 1.8 support that I'd like to look at/write a test. Expect a release tonight.

**Comment by jschneier** [comment]
Hi just released to PyPI, thanks for your interest!

**Comment by ALenfant** [comment]
Thanks, I really appreciate it!
