### ISSUE TITLE
Help with Azure pull and Issues management

### ISSUE THREAD

**Issue by sww314** [jschneier/django-storages#532]
There are currently 11 open pull requests (and 14 open issues) to fix the Azure backend. We need some help from Azure users to collaborate to get the backend upgraded and working. None of them are ready to be merged right now. 

#318 is close but is missing some dependencies for the tests to work in TravisCI. 
#531 is new today. It does not fix the old storage, but adds new azure1
#502 recent, but also failing build
[and more...](https://github.com/jschneier/django-storages/pulls?q=is%3Apr+is%3Aopen+label%3Aazure)

Calling Azure devs, please comment review the pull requests. Is there a consensus on which one is the best to start with the we can get merged soon?

@Peter-Slump
@edwin254  
@mheinze 
@guydou 
@jezdez 
@exploreshaifali

**Comment by akshaybabloo** [comment]
@Peter-Slump How different is your implementation from #318? One difference I noticed is that you upload the data without saving it to a temporary file. Any other difference?

**Comment by akshaybabloo** [comment]
For people who are looking to use Azure - https://github.com/satellogic/django-storages/tree/nitely_azure - works.

**Comment by nitely** [comment]
@akshaybabloo I'll make a PR next week. That branch includes a complete rework of the azure backend, unit and integration tests, docs. It should work pretty well. We are trying it out at @satellogic.

**Comment by nitely** [comment]
Adding it into v1.7 (or even 2.0) sounds like a good idea :smile_cat:

**Comment by nitely** [comment]
I've just created a PR -> https://github.com/jschneier/django-storages/pull/565

**Comment by sww314** [comment]
Closing this for #565. Thanks @nitely!!
