### ISSUE TITLE
[gcloud] Use credentials from variable/environment variable

### ISSUE THREAD

**Issue by jlugao** [jschneier/django-storages#539]
I am currently using heroku, I use environment variables and python-decouple to set the credentials, this works great with the now unsuported 'GSBotoStorage'.

I don't have many options to upload the secret json file without commiting it to git (and I don't want that), it would be great if I could just pass the contents of this json file as variables to some functions and get the credentials from it.

**Comment by sww314** [comment]
Check out the new documentation (not released yet). It shows some more examples of how to set up the authentication. You may have to check the underlying Google library for options on passing the JSON in. 

https://github.com/jschneier/django-storages/blob/master/docs/backends/gcloud.rst#settings

#455 also has a discussion on how the GS_CREDENTIALS works.

**Comment by jlugao** [comment]
great, thanks. Will look into it
