### ISSUE TITLE
[gcloud/gs] set already uploaded file

### ISSUE THREAD

**Issue by jlugao** [jschneier/django-storages#540]
I am currently facing some issues with large files as heroku sets a limit of 30s for the server to respond. So what I am doing is uploading directly to the bucket using firebase from javascript. 
How can I store a reference to this file? I tryed passing a string with the path inside the bucket, but no luck. Also tried to fiddle with different values and explore the fileField in the interactive shell, but couldn't manage to find out how to properly form the url

I am currently using gs, but will move to gcloud as soon as I manage some configuration problems

**Comment by sww314** [comment]
@jlugao This is bit tricky with the API. Django's FileField calls storage.save. 
https://github.com/django/django/blob/master/django/db/models/fields/files.py#L87

The storage.save() takes the content, saves it and returns the name. 
You could make a new storage and override _save() that skips the upload. 
https://github.com/jschneier/django-storages/blob/master/storages/backends/gcloud.py#L172
