### ISSUE TITLE
Any plans for Alibaba Cloud Object Storage Service (OSS) backend?

### ISSUE THREAD

**Issue by hussaintamboli** [jschneier/django-storages#541]
https://github.com/aliyun/aliyun-oss-python-sdk

**Comment by yywing** [comment]
https://help.aliyun.com/apsara/agile-data/v_2_5_0_20200506/oss/insight-developer-guide/s3-api-compatibility-instructions.html

**Comment by anyidea** [comment]
@sww314 i have added usage docs in my PR #1101 .

**Comment by jschneier** [comment]
See comment in #1101
