### ISSUE TITLE
django-storages, boto3, and django-progressbarupload

### ISSUE THREAD

**Issue by kidconcept** [jschneier/django-storages#544]
I'm building a small app that stores whalesong. I've got my forms uploading to an S3 via boto3 and django-storages. I've also installed the development version of django-progressbarupload and am running django 2.0.6

django-progressbarupload gets it's progress data via
```
      $.getJSON(upload_progress_url, {'X-Progress-ID': uuid}, function(data, status){
```
upload_progress_url is 'progressbarupload/upload_progress'. but the progress data just returns success / the full file size right away, even though the file is still uploading to S3. I'm not sure how these two components interact but thought perhaps django-storages isn't reporting upload progress in a way that django-progressbarupload expects. 

Project Here:
https://github.com/kidconcept/whalejams

Video Here
https://tinytake.s3.amazonaws.com/pulse/elpulpo/attachments/8400940/TinyTake29-07-2018-11-47-06.mp4

**Comment by sww314** [comment]
@kidconcept Short answer: these tools are not connected and no simple way to connect them.

The progressbarupload uses specific uploader that will load the file from the client to the Django server as tempfile or in memory. Then the file is handed off to django-storages to be saved on to the network storage. 

There are 2 distinct stages - the progressbarupload tries to capture the initial upload but does not know about the second save to network storage. django-storages does not generate any progress updates. You would need to create a custom storage to generate progress updates to a Redis cache (or something). 

Then you would need to update the progress URL with a new view that checks the progress variable you save in the cache.
