### ISSUE TITLE
New configuration: BUCKET name for Static files

### ISSUE THREAD

**Issue by paulocheque** [jschneier/django-storages#56]
I think would be a good idea to split Media flies and Static files in two distinct buckets.

Instead of only one `AWS_STORAGE_BUCKET_NAME`:

We could have two:

`AWS_STORAGE_BUCKET_NAME_DATA_FILES`
`AWS_STORAGE_BUCKET_NAME_STATIC_FILES`

**Comment by browniebroke** [comment]
:+1: for this. 

The way I've done it in my project is by creating 2 subclasses of `S3BotoStorage`, called something along the lines of `S3DefaultFileStorage`and `S3StaticFilesStorage` which both override the `__init__()` method and replace `kwargs['bucket']` by the value from these 2 settings.
If the setting is missing, raise an `ImproperlyConfigured` exception with a meaningful message.

The documentation needs to be updated to explain how to set the Django settings [here](https://docs.djangoproject.com/en/1.9/ref/settings/#default-file-storage) and [here](https://docs.djangoproject.com/en/1.9/ref/settings/#staticfiles-storage):

    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3DefaultFileStorage'
    STATICFILES_STORAGE = 'storages.backends.s3boto.S3StaticFilesStorage'

Ideally would be good to add some tests too. Anything else?

**Comment by browniebroke** [comment]
There is another package that does the job: https://github.com/jamstooks/django-s3-folder-storage

**Comment by ivanvenosdel** [comment]
@browniebroke Is that project just for separate folders though? I believe the ticket is about separate buckets. Which I would like to see as well.

**Comment by browniebroke** [comment]
Looks like I've posted my previous update too quickly, you're right @ivanvenosdel
