### ISSUE TITLE
Media files not deleted from Amazon S3

### ISSUE THREAD

**Issue by cmdelatorre** [jschneier/django-storages#58]
Hello, in a Django 1.7 project we are using the Amazon S3 storage (with boto).

The [documentations](http://django-storages.readthedocs.org/en/latest/backends/amazon-S3.html#model) says:

> Deleting an object deletes the file it uses, if there are no other objects still using that file

But, as I delete my model instance the corresponding file is not deleted from S3.

The model is really simple and we don have _other objects still using that file_.

¿Is it a bug or a problem with the documentation?

**Comment by hobarrera** [comment]
Django's default FileField doesn't delete the physical file either (see [here](https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.fields.files.FieldFile.delete)). I guess it's a documentation error, since one wouldn't expect the behaviour to diverge.
