### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by matheusjardimb** [jschneier/django-storages#6]
Great project!

I've been following django-storages for a while facing the same python3 incompatibility problem. Good to see someone is taking care of the project!

I'm quite new to django, so the answer may be simple: what should I use as requirement? I mean, I need to point to this github repo?

Maybe this is a commom question that may be answered in the README file ;)

Thanks a lot!!

**Comment by santhu221633** [comment]
@meshy thanks for the work. Its a clear cut explanation. I think there is a typo when you mention
```python
MEDIA_URL = os.environ.get('MEDIA_URL', S3_URL + 'media/')
```
I think it should be
```python
MEDIA_URL = os.environ.get('MEDIA_URL', S3_URL + 'client/')
```

**Comment by meshy** [comment]
@santhu221633 I think that's just a personal preference for the location of the client media.

**Comment by meshy** [comment]
You#re right though, it's not very consistent!

**Comment by bgarcial** [comment]
@meshy I am trying replicate your configuration, and I have the following question if you let me please:

In the 
`DEFAULT_FILE_STORAGE = os.environ.get(
    'DEFAULT_FILE_STORAGE',
    'core.storage.MediaRootS3BotoStorage',
)`

and

`STATICFILES_STORAGE = os.environ.get(
    'STATICFILES_STORAGE',
    'core.storage.StaticRootS3BotoStorage',
)`

What is the value of the  `'STATICFILES_STORAGE'` in your os?
core is your name application?

I have the following scheme based in your schema configuration:

`STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)`
`STATIC_ROOT = os.path.join(BASE_DIR, 'static_media')`
`AWS_ACCESS_KEY_ID = get_env_variable('AWS_ACCESS_KEY_ID')`
`AWS_SECRET_ACCESS_KEY =  get_env_variable('AWS_SECRET_ACCESS_KEY')`
`AWS_STORAGE_BUCKET_NAME = get_env_variable('AWS_STORAGE_BUCKET_NAME')`

`S3_URL = 'http://{0}.s3.amazonaws.com/'.format(AWS_STORAGE_BUCKET_NAME)`
`STATIC_URL = os.environ.get('STATIC_URL', S3_URL + 'static/')`

`DEFAULT_FILE_STORAGE = os.environ.get(
    'DEFAULT_FILE_STORAGE',
    'neurorehabilitation.storage.MediaRootS3BotoStorage',
)`
`STATICFILES_STORAGE = os.environ.get(
    'STATICFILES_STORAGE',
    'neurorehabilitation.storage.StaticRootS3BotoStorage',
)`

`MEDIA_URL = os.environ.get('MEDIA_URL', S3_URL + 'media/')`

But, when I run collectstatics, my files always go to STATIC_ROOT value (static_media)

**Comment by algiraldohe** [comment]
I managed to resolve the same issue just using the following parameters:
```
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

# AWS S3 Configuration
AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
AWS_STORAGE_BUCKET_NAME = os.environ['AWS_STORAGE_BUCKET_NAME']
AWS_S3_REGION_NAME = 'eu-west-2'


# Only public read for now
AWS_QUERYSTRING_AUTH = False
```
I changed `DEFAULT_FILE_STORAGE` from 'storages.backends.s3.S3Storage' >>> "storages.backends.s3boto3.S3Boto3Storage" and it worked for me. This change does not appear on the official documentation.

https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html
