### ISSUE TITLE
S3Boto3 listdir can no longer create buckets

### ISSUE THREAD

**Issue by baldychristophe** [jschneier/django-storages#603]
Hi,

With the recent update of `listdir` in S3Boto3Backend, an undocumented behavior has also changed, I am not sure if this is a bug or if it is intended. 

Formerly, when performing a `listdir` on a non-existing bucket, the function would call a `_get_or_create_bucket` which would create the bucket if `AWS_AUTO_CREATE_BUCKET` was set to True and then listdir would return that the bucket is empty.

After this commit, https://github.com/jschneier/django-storages/commit/b606a5129bc4d0f9189145c80382ba74b63350ef
this is no longer the case. An error is raised "NoSuchBucket" if the bucket does not already exist.

I am not sure what is the best, but if we follow the principles of a CRUD api, listdir is performing a GET request and I would not expect it to modify the state of the remote resource and create a bucket. But raising an error is also annoying as always checking if a bucket exists before a call to listdir is not very practical.

A third option would be:
- When `AWS_AUTO_CREATE_BUCKET` is set to True, return that the bucket is empty `return ([], [])` even if the bucket does not exist, because the bucket will be created anyway at the first occasion and this setting is mainly used in test environments
- When `AWS_AUTO_CREATE_BUCKET` is set to False, raise the error to warn the user about creating the bucket first.

Please, let me know what you think about this or close the issue if the current behavior is intended

Thanks

**Comment by jschneier** [comment]
Not intentional, no.

I intend to deprecate auto bucket creation shortly but should probably restore this functionality for now. Simply referencing `self.bucket` will do that.
