### ISSUE TITLE
Don't upload files if there isn't any change

### ISSUE THREAD

**Issue by ebsaral** [jschneier/django-storages#605]
I don't know if this is how storages works right now but on Heroku, whenever I deploy, collectstatic uploads files who are not changed as well. Is there any way to prevent this from happening?

**Comment by sww314** [comment]
The behavior is set by `collectstatic` script. `django-storages` is lower level it only manages the filesystem abstraction. 

You could try something: like https://github.com/antonagestam/collectfast
