### ISSUE TITLE
In django-storages library why safe_join function is not imported in s3boto3.py file from storages.utils.py file

### ISSUE THREAD

**Issue by rahul6612** [jschneier/django-storages#608]
**Currently i am using Django(version=1.8.4), django-storages(version=1.6.5) and boto3(version=1.5.35). while running the command heroku run python manage.py collectstatic i am getting this error:**

from storages.utils import safe_join, setting

ImportError: cannot import name 'safe_join'

**here is our safe_join function is defined in utils.py file**
    
  `def safe_join(base, *paths):
    """
    A version of django.utils._os.safe_join for S3 paths.

    Joins one or more path components to the base path component
    intelligently. Returns a normalized version of the final path.

    The final path must be located inside of the base path component
    (otherwise a ValueError is raised).

    Paths outside the base path indicate a possible security
    sensitive operation.
    """
    base_path = force_text(base)
    base_path = base_path.rstrip('/')
    paths = [force_text(p) for p in paths]

    final_path = posixpath.normpath(posixpath.join(base_path + '/', *paths))
    # posixpath.normpath() strips the trailing /. Add it back.
    if paths[-1].endswith('/'):
        final_path += '/'

    # Ensure final_path starts with base_path and that the next character after
    # the final path is /.
    base_path_len = len(base_path)
    if (not final_path.startswith(base_path) or final_path[base_path_len] != '/'):
        raise ValueError('the joined path is located outside of the base path'
                         ' component')

    return final_path.lstrip('/')`
**and here we imported safe_join function in s3boto3.py file**
`from storages.utils import setting, safe_join`

**Comment by jschneier** [comment]
That function was moved to that file in version 1.6

Are you sure you don't have a legacy copy of django-storages hanging around somehow?

**Comment by jschneier** [comment]
Can you post the full traceback?

**Comment by sww314** [comment]
@rahul6612 did you figure this out?

**Comment by rahul6612** [comment]
ya i got that

**Comment by therightmandev** [comment]
I had a similar error and solved it by removing "location" from my STORAGES OPTIONS
