### ISSUE TITLE
Azure backend strips some non-alphabetic characters from the file name

### ISSUE THREAD

**Issue by moriyoshi** [jschneier/django-storages#609]
https://github.com/jschneier/django-storages/blame/master/storages/backends/azure_storage.py#L109

Is there any reason for stripping characters other than:
* `a`-`z` `A`-`Z` `0`-`9`
* `_`
* `-`
* `.`
* `/`

?

As much as I learn from the comment, url-escaping will do for special characters that occur inbetween .

**Comment by davidfischer** [comment]
This bug causes a problem if AzureStorage is used with the Django's [ManifestFilesMixin](https://docs.djangoproject.com/en/2.1/ref/contrib/staticfiles/#manifestfilesmixin). For example, the contents of my CSS files are being post processed from `url('../fonts/fontawesome-webfont.eot?v=4.4.0')` to `url("../fonts/fontawesome-webfont.674f50d287a8.eotv4.4.0")` (note the missing `?` and `=`).

**Comment by nitely** [comment]
It's not a bug, Django's default storage does not allow this either. What happens when someone uploads a file with a special character that is not allowed by all OS filesystems? can those files be downloaded later? (i.e interrogation mark is not allowed in Windows)

**Comment by nitely** [comment]
^ After some testing I've found Django will sanitize the file name when saving into the DB, doing basically the same as the Azure storage. This can be bypassed by calling `default_storage.save(...)` and passing a callable to `models.FileField(upload_to=callable)`. So I believe we should make the Azure storage behave like the rest of `django-storages`'s storages. I've a PR fixing this underway.

**Comment by akshaybabloo** [comment]
Any update on merging the pull request?
