### ISSUE TITLE
Is support for WebDAV on the roadmap?

### ISSUE THREAD

**Issue by LaundroMat** [jschneier/django-storages#614]
It seems that the packages that allow Django to store static files on a WebDAV server are no longer maintained. (See https://github.com/sirmmo/django-webdav and https://github.com/marazmiki/django-webdav-storage)

Is support for WebDAV on the roadmap  of django-storages?

**Comment by sww314** [comment]
@LaundroMat - WebDav is not on the roadmap. 

If there is sufficient interest and a pull request, I am sure it would be considered. It may have similar utility as the SFTP backend if you are not using a commercial cloud provider.

At glance, https://github.com/marazmiki/django-webdav-storage this project seems mostly complete -- if stale. The other one is just a shell.

**Comment by LaundroMat** [comment]
I might have a go at it in the coming weeks to scratch a personal itch. Before I do however, do you think WebDAV as a technology is suited for high-volume storage of static (including user-submitted) assets? 

I ask because I'm trying to understand why no-one really seems to care about the technology.

**Comment by sww314** [comment]
WebDAV really only solves part of the problem. Commercial solutions like Google Cloud Storage and AWS S3 provide an API like WebDAV (file CRUD over HTTP) but also handle the backend file system scaling across machines and regions. WebDAV also delegates the security to the web server. In most cases, Basic AUTH and a password do not hack it for security. 

As far as effectiveness goes, WebDAV is transferring the files over HTTP just like the other solutions. All the current cloud solutions are not great for collect static- it is inefficient to copy all the little files over. The speed will depend on the implementation of the WebDAV provider -- I think. 

The general question would be why would you use WebDAV vs a commercially supported solution that is very cost effective?

**Comment by LaundroMat** [comment]
Thanks!

I happen to have been grandfathered in a plan where I have access to 1 terrabyte of free storage. It's only accessible via WebDAB though. So from the perspective of cost-effectiveness, that's alright :) 

I'll dabble a bit with it to see whether I'll really use it and if so will try and create a PR.
