### ISSUE TITLE
Help wanted: Use dropbox storage with my django admin.

### ISSUE THREAD

**Issue by JoabMendes** [jschneier/django-storages#617]
I followed the docs for [dropbox storage](https://django-storages.readthedocs.io/en/latest/backends/dropbox.html#settings) with the following config:

My current settings.py file has:

```py
# Dropbox media file storage

DEFAULT_FILE_STORAGE = 'storages.backends.dropbox.DropBoxStorage'
DROPBOX_OAUTH2_TOKEN = '<my_access_key>'
DROPBOX_ROOT_PATH = 'ygks_media_files' # Folder I defined on my dropbox app
```

I kept the old configuration for media files I had before, that are:

```py
# settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media").replace('\\', '/')
```

```py
# urls.py
urlpatterns = [# ... my urls
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

And the models classes I have, that need file upload are set like:

```
    photo = models.FileField(
        storage=FileSystemStorage(location=settings.MEDIA_ROOT),
        upload_to='member_photo',
        blank=False,
        null=False,
        default='',
        verbose_name='Banner image (1800 x 1200)'
    )
```
I deployed those settings (I'm using heroku) and after creating an instance of that model, the file wasn't in the dropbox or anything after.

Is there any configuration I have to set up on my models or settings to make this package work with the default django admin site? Should I change the `FileSystemStorage` class to something else?

**Comment by JoabMendes** [comment]
Found the solution on [stackoverflow](https://stackoverflow.com/questions/49715802/how-to-use-django-storages-for-media-storage-on-dropbox)!!!

**Comment by jhondoedo** [comment]
hi @JoabMendes  is it still functioning with the django 2 and recent dropbox api. exactly followed django storages and your settings. but still there is problem. #689

**Comment by JoabMendes** [comment]
Hey @jhondoedo I believe the versions are compatible still, but I don't what is happening in your case. Did you check that stackoverflow link posted here?

I dropped the dropbox integration to use amazon storage, it made my application way faster because they have image caching and there're direct links for the files too.

**Comment by jhondoedo** [comment]
> Hey @jhondoedo I believe the versions are compatible still, but I don't what is happening in your case. Did you check that stackoverflow link posted here?
The issue is with windows os. Instead of getting dropbox link i was getting absolute path of windows. with the same settings in Ubuntu( in my case version 18.04) working fine.

**Comment by AliPolat** [comment]
Help please : 

**https://github.com/jschneier/django-storages/issues/617#issuecomment-485719528**

I have the exact same configuration and the same problem. Is there any way to bypass  the windows path issue other than migrating to linux?


My environment
python 3.6
django 2.1
dropbox for media files
azure for deployment
windows for iis
