### ISSUE TITLE
Apps python warnings settings interfere with those in my project

### ISSUE THREAD

**Issue by jackmurphy** [jschneier/django-storages#62]
Setting warnings.simplefilter('always') in the module's init overrides the settings in my project and are resulting in annoying log spam.

Is there a known workaround this? Barring that, can you give me some background on why you've chosen this configuration?

**Comment by jschneier** [comment]
Yeah, sorry about that. This was fixed in by [this commit](https://github.com/jschneier/django-storages/commit/ba7e1f8b41f4bb98f967f162295093c861502dd8) which was released as 1.2.2
