### ISSUE TITLE
django-storage with dropbox breaks browser cache

### ISSUE THREAD

**Issue by JoabMendes** [jschneier/django-storages#621]
I'm facing the same issue decribed [here](https://stackoverflow.com/questions/15668443/django-storage-with-s3-boto-break-browser-cache) but instead of amazon storage, I'm using the dropbox option. The current configuration works for a while with my cache configuration (cache_page), but after a while all the media files return 404 till I clear the cache again.

Is there any specific configuration for Dropbox or using `AWS_QUERYSTRING_AUTH = False` will also work?

**Comment by sww314** [comment]
The dropbox storage does not currently support public files. All the files are using a temporary link. 

The AWS_* settings have no impact on the Dropbox backend.

**Comment by JoabMendes** [comment]
Alright, Thanks @sww314 !!
