### ISSUE TITLE
S3Boto3Storage: Getting rid of orphaned files when not overwriting

### ISSUE THREAD

**Issue by sushifan** [jschneier/django-storages#633]
Has anyone come up with a good solution (when AWS_S3_FILE_OVERWRITE = False) to automatically get rid of the otherwise orphaned previous files?  I like the random char appending feature (this way the client knows when a file has changed), but can't afford to have my S3 bucket full of old, unused images.  Thanks in advance!

**Comment by jschneier** [comment]
This is very much a domain specific and business logic question. Some people want to keep old variants around and others not.
