### ISSUE TITLE
boto3 settings can't be configured when using django-storages settings

### ISSUE THREAD

**Issue by danielsailes** [jschneier/django-storages#637]
Hi,

Recently had an issue where i had to rebuild my local environment. in doing so, for some reason django-storages and boto3 aren't working anymore. Any ideas as to why?

(I had custom locations for the Media and Static following these instructions: https://www.caktusgroup.com/blog/2014/11/10/Using-Amazon-S3-to-store-your-Django-sites-static-and-media-files/ - yet i can't find any documentation to find out why these may or may not work any more)

```
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com:443' % AWS_STORAGE_BUCKET_NAME


AWS_S3_OBJECT_PARAMETERS = {  # see http://developer.yahoo.com/performance/rules.html#expires
    'Expires': 'Thu, 31 Dec 2099 20:00:00 GMT',
    'Cache-Control': 'max-age=94608000',
}

MEDIAFILES_LOCATION = 'media'
MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

STATICFILES_LOCATION = 'static'
STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, STATICFILES_LOCATION)
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
```

getting out this error consistently and not sure why. Am i missing some kind of dependency to work with these plugins?

```  File "/Users/daniel/Library/Python/2.7/lib/python/site-packages/storages/backends/s3boto3.py", line 22, in <module>
    raise ImproperlyConfigured("Could not load Boto3's S3 bindings.\n"
django.core.exceptions.ImproperlyConfigured: Could not load Boto3's S3 bindings.
See https://github.com/boto/boto3```

Any help appreciated!

**Comment by jschneier** [comment]
You likely need to do `pip install boto3`. `pip install django-storages[boto3]` also works.
