### ISSUE TITLE
AWS_DEFAULT_ACL will be 'private' if set to None

### ISSUE THREAD

**Issue by kokinomura** [jschneier/django-storages#638]
[Document](https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html?highlight=aws_default_acl) says "If set to None then all files will inherit the bucket’s ACL.", but objects' ACL are set to 'private'. 

As far as I know, django-storages has no code to inherit the bucket's ACL and the default ACL of S3 is 'private'.
https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl

**Comment by tisdall** [comment]
I"m also in the middle of trying to figure this out, but essentially it is doing what it says.  If you set `AWS_DEFAULT_ACL` to 'None` then django-storages just doesn't send any ACL setting when uploading the file and allows it to use the bucket default.  However, I haven't been able to figure out how to make a bucket default to "public-read" as the default default is "private".

**Comment by tisdall** [comment]
Here's what I did to solve the problem, but I think the docs need some updating to help guide people.

I set `AWS_DEFAULT_ACL = None` as recommended and the wrote my own storage class by inheriting `S3Boto3Storage`:
```python
class StaticS3Storage(S3Boto3Storage):
    location = settings.AWS_STATIC_LOCATION
    default_acl = 'public-read'
```

Then my settings also has:
```python
AWS_STATIC_LOCATION = 'static'
STATICFILES_STORAGE = 'myproject.filestorage.StaticS3Storage'
```

There doesn't appear to be any easy way to set the bucket to default to giving public access to the files.  The only way I could find to do this was creating a policy and that seemed rather confusing.

**Comment by jschneier** [comment]
I think the documentation is wrong. To make each file readable you would need to set `AWS_DEFAULT_ACL` to `public-read`.

In truth I think it's better to drive people away from ACL but it's certainly the most convenient and straightforward. I'll update the docs to say the default is `private`.

**Comment by jschneier** [comment]
You can add a bucket policy that grants `s3:GetObject` to everyone (`*`) and that seems to _just work_.

**Comment by awais786** [comment]
Hi folks, I am also facing same issue. I am trying to upgrade enterprise level app from `1.9.1` to `1.10.1`. But since AWS_DEFAULT_ACL is none now so all files uploading become private. But documentation says clearly It will pick buckets acls and thats not happening.
