### ISSUE TITLE
Wagtail tests failing when using django-storages (S3BotoStorage)

### ISSUE THREAD

**Issue by salvadormrf** [jschneier/django-storages#64]
Related
https://github.com/torchbox/wagtail/issues/1542
#### result

```
python runtests.py wagtail.wagtailimages --failfast

======================================================================
FAIL: test_closes_image (wagtail.wagtailimages.tests.test_models.TestGetWillowImage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/wagtail-1.0/wagtail/wagtailimages/tests/test_models.py", line 239, in test_closes_image
    self.assertTrue(self.image.file.closed)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 4 tests in 2.563s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

Got  a reply from a wagtail core developer.
I wonder what can be done to fix this issue.

```
This looks like a bug in django-storages to me.

When you call file.close() the file.closed property should return True.

django-storages doesn't override djangos default definition of this property: https://github.com/django/django/blob/master/django/core/files/base.py#L67-L69

This tells if the file is closed by simply accessing the .file attribute. But in django-storages, this reopens the file: https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto.py#L120-L138

So .closed returns True
```

**Comment by jschneier** [comment]
Thanks for the report. 2 things:

I suppose this is why #42 exists. I forked the original django-storages (it's completely unmaintained) and don't have access to its pypi name. Thus the relevant package is django-storages-redux.

Second of all, yes, this is definitely a bug that needs to be fixed. Funny, I just had to pick up wagtail today for a client project.

**Comment by aptwebapps** [comment]
There's a much bigger bug here, isn't there? Even if self.closed return False there when it should it would proceed to the underlying Django file's open method which would try to open it on the file system. Is conventional open(), close() behavior actually supported here when coming from a FileField?

**Comment by vstoykov** [comment]
Here is a fix for similar problem in `django-s3-storage` https://github.com/etianen/django-s3-storage/commit/0286570e5afbfa6909fa65d95d0fb49ed1e45ebc

Every custom storage need to implement reopening of the file (`open()` method)
