### ISSUE TITLE
issue auto creating a bucket that previously existed?

### ISSUE THREAD

**Issue by tisdall** [jschneier/django-storages#642]
I set `AWS_DEFAULT_ACL` to `None` as recommended and am trying to figure out how to set the default ACL on the bucket to 'public-read'.  I can't seem to figure it out in the UI so I tried having django-storages make the bucket for me by setting `AWS_AUTO_CREATE_BUCKET = True` and `AWS_BUCKET_ACL = 'public-read'`.  Instead of success I got a "bad request" error.

I tried again by changing the bucket name slightly and then it worked...  Is it not possible to recreate a deleted bucket through the API?

**Comment by jschneier** [comment]
The auto creation feature is now deprecated.
