### ISSUE TITLE
Using Javascript to upload to Google Cloud Storage

### ISSUE THREAD

**Issue by log-wood** [jschneier/django-storages#647]
I'm using django-storages as my default file storage. I have a script that uploads videos directly from the client to google cloud storage. Is there any way to associate this file to a FileField without downloading and reuploading the file. Thank you for any help!

**Comment by sww314** [comment]
@log-wood No off the shelf solution. You would need to hack FileField to set the name value without the upload. 
https://docs.djangoproject.com/en/2.1/_modules/django/db/models/fields/files/#FieldFile

The save is passed the content and hands it off to storage which in this case would upload to GCS. 
You want to skip that portion. 

Maybe as a hack, make a ReadOnlyFIleField that does not upload the file to storage.

**Comment by log-wood** [comment]
@sww314 Thank you for the quick reply.

Solved it by creating the model object then changing the Model.file.name to the blob path from GCS. Works with django-storages signing the url as well.
