### ISSUE TITLE
How do I send compressed images to Google Cloud Storage?

### ISSUE THREAD

**Issue by YuyaNishimaki** [jschneier/django-storages#654]
Hello, 

I'm using GCS as cloud storage and want to compress  images using gzip.
I read the document, but I could not find how to compress the image for GCS.
Is there a setting to compress images like AWS_IS_GZIPPED for Amazon S3?
What kind of code should I write to compress?

My environment:
macOS 10.14.1, Docker 18.06.1-ce, python 3.7.2, django 2.1.5, django-storages 1.7.1

Thank you.

**Comment by sww314** [comment]
@YuyaNishimaki  Did you figure this out?

It seems like you just have to gzip the file, but set the headers correctly.
https://cloud.google.com/storage/docs/transcoding

Right now, you would have to customize the storages to add support for the headers.
