### ISSUE TITLE
Google storages encodes slashes by default - breaks relative urls in static assets

### ISSUE THREAD

**Issue by NDevox** [jschneier/django-storages#655]
Currently the default behaviour when getting URLs from the google-cloud-storage library is to encode the URL, including slashes.

This is documented by google here: https://cloud.google.com/storage/docs/json_api/#encoding

As far as I know the reasoning is because buckets in google are actually flat structures and directories don't really exist - it's just naming conventions.

However your browser still interprets it as using directories and behaves accordingly.

As a result, specifically with static files - this creates a bug.

In a CSS file I will often have relative urls pointing at things such as images or fonts.

They will look like:

```css
// static/css/main.css
@font-face {
  font-family: "my-font";
  src: url(../font/my-font.ttf);
}
```

As the file I'm in is currently at `https://storage.googleapis.com/my-bucket/static/css/main.css` I would expect the resultant relative url to point to `https://storage.googleapis.com/my-bucket/static/font/my-font.ttf`.

But GCS encodes the url to `https://storage.googleapis.com/my-bucket/static%2fcss%2fmain.css` so the resultant relative url actually points to `https://storage.googleapis.com/static/font/my-font.ttf` which is clearly wrong.

I'd like to propose a setting which triggers URLs to stop encoding slashes. This could be done with a simple:

```python
if not settings.GS_ENCODE_SLASHES:
    url = url.replace('%2F', '/')
```

around [here](https://github.com/jschneier/django-storages/blob/master/storages/backends/gcloud.py#L266).

**Comment by jschneier** [comment]
I believe this was fixed upstream.
