### ISSUE TITLE
Setting metadata for Google Storage

### ISSUE THREAD

**Issue by RRaideRR** [jschneier/django-storages#660]
Hey there,

is there a possibility to set certain metadata for uploading a file (e.g. Content-Disposition)?

Could anyone give me a hint in which direction I should look here?

**Comment by bd** [comment]
Did you find an answer? I was wondering about this, too.

**Comment by RRaideRR** [comment]
I don't think that this is possibe with django-storages right now.
However, it is a feature request: https://github.com/jschneier/django-storages/issues/510
