### ISSUE TITLE
django-storages s3 storage not working with Django ImageField

### ISSUE THREAD

**Issue by IronnMaiden** [jschneier/django-storages#667]
I'm using django storages for maintaining uploads in S3 and using django-rest-framework along side it.
Here is the issue that is coming when is try handling multipart upload -

> [12/Feb/2019 14:22:46] ERROR [kyros.error_handler:74] File was not opened in read mode.
Traceback (most recent call last):
  File "/Users/tamoghnabiswas/.virtualenvs/kyros/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/tamoghnabiswas/workspace/kyros_server/users/views.py", line 526, in patch
    return generics.RetrieveUpdateAPIView.patch(self, request, *args, **kwargs)
  File "/Users/tamoghnabiswas/.virtualenvs/kyros/lib/python3.6/site-packages/rest_framework/generics.py", line 260, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/Users/tamoghnabiswas/.virtualenvs/kyros/lib/python3.6/site-packages/rest_framework/mixins.py", line 84, in partial_update
    return self.update(request, *args, **kwargs)
  File "/Users/tamoghnabiswas/.virtualenvs/kyros/lib/python3.6/site-packages/rest_framework/mixins.py", line 69, in update
    serializer.is_valid(raise_exception=True)
  File "/Users/tamoghnabiswas/.virtualenvs/kyros/lib/python3.6/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/Users/tamoghnabiswas/.virtualenvs/kyros/lib/python3.6/site-packages/rest_framework/serializers.py", line 434, in run_validation
    value = self.to_internal_value(data)
  File "/Users/tamoghnabiswas/.virtualenvs/kyros/lib/python3.6/site-packages/rest_framework/serializers.py", line 491, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "/Users/tamoghnabiswas/.virtualenvs/kyros/lib/python3.6/site-packages/rest_framework/fields.py", line 536, in run_validation
    value = self.to_internal_value(data)
  File "/Users/tamoghnabiswas/.virtualenvs/kyros/lib/python3.6/site-packages/rest_framework/fields.py", line 1594, in to_internal_value
    return django_field.clean(file_object)
  File "/Users/tamoghnabiswas/.virtualenvs/kyros/lib/python3.6/site-packages/django/forms/fields.py", line 584, in clean
    return super().clean(data)
  File "/Users/tamoghnabiswas/.virtualenvs/kyros/lib/python3.6/site-packages/django/forms/fields.py", line 147, in clean
    value = self.to_python(value)
  File "/Users/tamoghnabiswas/.virtualenvs/kyros/lib/python3.6/site-packages/django/forms/fields.py", line 621, in to_python
    file = BytesIO(data.read())
  File "/Users/tamoghnabiswas/.virtualenvs/kyros/lib/python3.6/site-packages/storages/backends/s3boto3.py", line 111, in read
    raise AttributeError("File was not opened in read mode.")

The code and settings are as follows -
views.py

`from rest_framework.parsers import MultiPartParser, JSONParser, FileUploadParser
from utils.cache.mixins import NoCacheMixin, PrivateCacheMixin, PublicCacheMixin

class UserProfileDetail(PublicCacheMixin, generics.RetrieveUpdateAPIView):
    queryset = UserProfile.objects.all()
    parser_classes = (JSONParser, MultiPartParser,)
    serializer_class = UserProfileSerializer
    permission_classes = [
        # permissions.IsAuthenticated,
        # kh_permissions.IsOwnerAdminOrReadOnly
    ]
    cache_timeout = 30

    def is_self(self):
        return self.kwargs['pk'] in [e.user_id for e in self.request.user.profiles.all()]

    def post(self, request, *args, **kwargs):
        if 'user_img_full' in request.data and request.user.is_doctor:
            response = generics.RetrieveUpdateAPIView.patch(self, request, *args, **kwargs)
            if response.data['is_default'] and self.is_self():
                user_img_full = response.data['user_img_full']
                user_img_thumb = response.data['user_img_thumb']
                request.user.doctor.user_img_full = user_img_full
                request.user.doctor.user_img_thumb = user_img_thumb
                request.user.doctor.save()
            return response
        if 'user_img_full' in request.data:
            return generics.RetrieveUpdateAPIView.patch(self, request, *args, **kwargs)
        return Response({"status" : "Work"}, status=status.HTTP_200_OK)

    def patch(self, request, *args, **kwargs):
        # if image is being uploaded, copy the image url to doctor profile
        if 'user_img' in request.data and request.user.is_doctor:
            response = generics.RetrieveUpdateAPIView.patch(self, request, *args, **kwargs)
            if response.data['is_default'] and self.is_self():
                user_img = response.data['user_img']
                request.user.doctor.user_img = user_img
                request.user.doctor.save()
            return response
        if 'user_img_full' in request.data and request.user.is_doctor:
            response = generics.RetrieveUpdateAPIView.patch(self, request, *args, **kwargs)
            if response.data['is_default'] and self.is_self():
                user_img_full = response.data['user_img_full']
                user_img_thumb = response.data['user_img_thumb']
                request.user.doctor.user_img_full = user_img_full
                request.user.doctor.user_img_thumb = user_img_thumb
                request.user.doctor.save()
            return response
        elif 'first_name' in request.data:
            response = generics.RetrieveUpdateAPIView.patch(self, request, *args, **kwargs)
            # if response['user_id'] in request.user.profiles
            if self.is_self():
                name = [e for e in request.data.get('first_name', '').split(' ') if e]
                f_name = request.user.first_name
                l_name = request.user.last_name
                if name:
                    f_name = name[0]
                    l_name = (' '.join(name[1:])+request.data.get('last_name', ' ')).strip() if len(name)>1 else \
                        request.data.get('last_name', ' ')
                    if response.data['is_default']:
                        normalize_user_name(request.user, f_name, l_name)
                response.data['first_name'] = f_name
                response.data['last_name'] = l_name
            return response
        else:
            return generics.RetrieveUpdateAPIView.patch(self, request, *args, **kwargs)`

models.py -
`class UserProfile(models.Model):
    user_id = models.CharField(max_length=100,
                               primary_key=True, editable=False)
    first_name = models.CharField(max_length=100, null=True, blank=True, default=' ')
    last_name = models.CharField(max_length=100, null=True, blank=True, default=' ')
    sex = models.CharField(max_length=2, null=True, blank=True,
                           choices=(("M", "MALE"), ("F", "FEMALE"), ("O", "OTHER")))
    dob = models.DateField("Date of Birth",
                           null=True, blank=True)
    blood_group = models.CharField(max_length=5, default="",
                                   null=True, blank=True,
                                   choices=(("O+", "O+"), ("O-", "O-"),
                                            ("B+", "B+"), ("B-", "B-"),
                                            ("AB+", "AB+"), ("AB-", "AB-"),
                                            ("A+", "A+"), ("A-", "A-")))

    address_line1 = models.CharField(max_length=100, blank=True, null=True)
    address_line2 = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=20, blank=True, null=True)
    country = models.CharField(max_length=20, blank=True, null=True)
    pin_code = models.CharField(max_length=6, blank=True, null=True)
    marital_status = models.CharField(max_length=10, null=True, blank=True,
                                      choices=(("Married", "Married"),
                                               ("Unmarried", "Unmarried")))

    is_default = models.BooleanField(default=False)

    alternate_contact_name_1 = models.CharField(max_length=50, null=True, blank=True)
    alternate_contact_type_1 = models.CharField(max_length=50, null=True, blank=True)
    alternate_contact_number_1 = models.CharField(max_length=15, null=True, blank=True)

    alternate_contact_name_2 = models.CharField(max_length=50, null=True, blank=True)
    alternate_contact_type_2 = models.CharField(max_length=50, null=True, blank=True)
    alternate_contact_number_2 = models.CharField(max_length=15, null=True, blank=True)

    created_date = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    user_img = ProcessedImageField(upload_to=user_directory_path,
                                   processors=[SmartResize(100, 100)],
                                   format='PNG',
                                   options={'quality': 60}, blank=True, null=True)
    user_img_full = ProcessedImageField(upload_to=user_directory_path_full_image,
                                        processors=[SmartResize(960, 1280)],
                                        format='PNG',
                                        options={'quality': 99}, blank=True, null=True)
    user_img_thumb = ImageSpecField(source='user_img_full',
                                    format='PNG',
                                    options={'quality': 70},
                                    processors=[SmartResize(100, 100)])

    height_ft = models.IntegerField(default=0)
    height_inch = models.IntegerField(default=0)
    allergies = models.CharField(max_length=100,
                                 blank=True, null=True)
    weight = models.IntegerField(default=0)
    misc_data = pg_fields.HStoreField(null=True, blank=True)

    def display_name(self):
        return "%s %s" % (safe_str(self.first_name), safe_str(self.last_name))

    def __unicode__(self):
        return self.display_name()

    def __str__(self):
        return self.display_name()

    def save(self, *args, **kwargs):
        if not self.pk:
            self.pk = generate_user_id()
        super(UserProfile, self).save(*args, **kwargs)`

**Comment by sww314** [comment]
You are not setting the ImageField correctly. You are just copying the data from the response to the ImageField (I think). 
Personally, I would handle this in the serializer not in the views.
