### ISSUE TITLE
AWS credentials only work in base settings module

### ISSUE THREAD

**Issue by Alex3917** [jschneier/django-storages#67]
As per the recommendations in Two Scoops of Django, I've got two settings modules: base.py, and dev.py. Dev.py imports everything from base.py, and then adds whatever settings I need for the development environment.

For some reason my AWS credentials work fine in base.py, but Boto doesn't seem to be able to find them when they're in dev.py. No idea why, because Django itself has no issue seeing the variables in that file. (E.g. my DJANGO_SETTINGS_MODULE is set correctly.)

**Comment by mbarrien** [comment]
Is this still an issue? It's really difficult to debug this without seeing more of your settings file, and the way this is described, it's likely to not be a django-storages issue but more with something specific to how you wrote the file.

**Comment by Alex3917** [comment]
The issue was basically just that I had to define the AWS variables before doing:

from storages.backends.s3boto import S3BotoStorage

I worked around it but that's what was happening.

**Comment by jschneier** [comment]
Yes, this is due to the way that the settings are declared at the class level variable. This is unfortunately inherited legacy. It's a larger cleanup but basically my biggest desire from a maintenance perspective, should make testing easier.

**Comment by jschneier** [comment]
#524 is aiming to fix this.

**Comment by jschneier** [comment]
Fixed in #524.
