### ISSUE TITLE
Cache Control in Azure

### ISSUE THREAD

**Issue by davidfischer** [jschneier/django-storages#674]
It would be nice to be able to set the cache control for a file going to Azure. Normally this would [happen here](https://github.com/jschneier/django-storages/blob/efcad7f6b39b79ef2ef5810c38e48065d04b1c8f/storages/backends/azure_storage.py#L240-L242).

I haven't thought through whether it should be overridable on a per file basis or a setting for the storage class. The latter is more similar to how things work for S3, I believe (`AWS_HEADERS`, `AWS_S3_OBJECT_PARAMETERS`)

There's some prior discussion in #323.

**Comment by jschneier** [comment]
Resolved by #780.
