### ISSUE TITLE
SSLError: [SSL] malloc failure (_ssl.c:2990)     /    AWS S3

### ISSUE THREAD

**Issue by gotexis** [jschneier/django-storages#677]
My rig:

Python 3.7.2
Django 2.1.7
BOTO3 1.9.106
botocore 1.12.106
dj-storages 1.7.1

Hmmmm
What to do...
I have turned off use_ssl for now just to make it work...
Let's see what happens....
Hopefully it can work without SSL
otherwise my site is fucked...

**Comment by sww314** [comment]
Did you figure this out? this is probably a misconfigured library at the OS level.

**Comment by stchris** [comment]
@gotexis have you figured out the circumstances? Are you maybe running in a Docker container with an alpine-based image?

**Comment by gotexis** [comment]
@stchris Yes I am running in a Docker container with an alpine-based image.

Think it had something to do with certifi, after I updated it, right now the problem seem to have gone away.

Maybe have to keep an eye in the future.

@sww314
