### ISSUE TITLE
Document AWS S3 IAM Permissions

### ISSUE THREAD

**Issue by irasnyd** [jschneier/django-storages#685]
Which AWS IAM permissions are needed for Django Storages to work with an AWS S3 Bucket? This isn't documented anywhere that I can find. This is where I expected to find a list of the necessary permissions: https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html

**Comment by sww314** [comment]
@irasnyd if you figured this out a documentation pull request would be appreciated? (I do not use the S3 package so can't answer your question).
