### ISSUE TITLE
S3Boto3Storage url method is undocumented

### ISSUE THREAD

**Issue by szpsz** [jschneier/django-storages#686]
S3Boto3Storage url method used for generating presigned urls is not documented either in docs nor in code. It is quite hard to get information that generating presigned urls through this library is possible. I think that this information might be very helpful for developers using this library because it is probably one of few functions which they will intend to use manually.

**Comment by malderete** [comment]
@szpsz Hello! How is it going?

IMO, this is not a *django-storages* issues. I will try to give my argument below :).

The method you mentioned, `url`, is not a private method of the `S3Boto3Storage` class. Actually, `url` is part of the *Django Storage Interface*, you can found the doc [here](https://docs.djangoproject.com/en/2.2/ref/files/storage/#django.core.files.storage.Storage.url). It means, sometimes when creating a *custom storage* there is a need to provide an `url` method in our implementation.
Django internally, for example in `FileField`, needs to call `storage.url(...)`.

For example, when we have a `FileField` in a model and we want to create a link to download the file associated with that field, we could do something like:
```django
<a href="{model.thefileattribute.url}" title="Download">Download</a>
```
Behind the scenes, accessing the `url` method (its a property) will perform a call to the `url` method of the Storage instance being used.
There are other method in Storage class that are called by Django itself such as: `size`, `open`, `path`.

I think we do not have to add that kind of documentation to django-storages docs, it is already included in Django docs.

I hope, this reply helped you! Feel free to ask or comment.
