### ISSUE TITLE
ImportError: cannot import name 'check_location'

### ISSUE THREAD

**Issue by dezmaeth** [jschneier/django-storages#690]
Im having an issue on import the library

**ImportError: cannot import name 'check_location'**

Ref. https://github.com/jschneier/django-storages/blob/a8764ff58501e15b8dc08941cb8c7cb4a607022c/storages/backends/gcloud.py#L13

Stacktrace
> ImportError: cannot import name 'check_location'
>   File "django/core/handlers/exception.py", line 34, in inner
>     response = get_response(request)
>   File "django/core/handlers/base.py", line 156, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "django/core/handlers/base.py", line 154, in _get_response
>     response = response.render()
>   File "django/template/response.py", line 106, in render
>     self.content = self.rendered_content
>   File "django/template/response.py", line 83, in rendered_content
>     content = template.render(context, self._request)
>   File "django/template/backends/django.py", line 61, in render
>     return self.template.render(context)
>   File "django/template/base.py", line 171, in render
>     return self._render(context)
>   File "django/template/base.py", line 163, in _render
>     return self.nodelist.render(context)
>   File "django/template/base.py", line 937, in render
>     bit = node.render_annotated(context)
>   File "django/template/base.py", line 904, in render_annotated
>     return self.render(context)
>   File "django/template/loader_tags.py", line 150, in render
>     return compiled_parent._render(context)
>   File "django/template/base.py", line 163, in _render
>     return self.nodelist.render(context)
>   File "django/template/base.py", line 937, in render
>     bit = node.render_annotated(context)
>   File "django/template/base.py", line 904, in render_annotated
>     return self.render(context)
>   File "django/template/loader_tags.py", line 150, in render
>     return compiled_parent._render(context)
>   File "django/template/base.py", line 163, in _render
>     return self.nodelist.render(context)
>   File "django/template/base.py", line 937, in render
>     bit = node.render_annotated(context)
>   File "django/template/base.py", line 904, in render_annotated
>     return self.render(context)
>   File "django/template/loader_tags.py", line 62, in render
>     result = block.nodelist.render(context)
>   File "django/template/base.py", line 937, in render
>     bit = node.render_annotated(context)
>   File "django/template/base.py", line 904, in render_annotated
>     return self.render(context)
>   File "django/template/loader_tags.py", line 62, in render
>     result = block.nodelist.render(context)
>   File "django/template/base.py", line 937, in render
>     bit = node.render_annotated(context)
>   File "django/template/base.py", line 904, in render_annotated
>     return self.render(context)
>   File "django/template/defaulttags.py", line 209, in render
>     nodelist.append(node.render_annotated(context))
>   File "django/template/base.py", line 904, in render_annotated
>     return self.render(context)
>   File "django/template/loader_tags.py", line 188, in render
>     return template.render(context)
>   File "django/template/base.py", line 173, in render
>     return self._render(context)
>   File "django/template/base.py", line 163, in _render
>     return self.nodelist.render(context)
>   File "django/template/base.py", line 937, in render
>     bit = node.render_annotated(context)
>   File "django/template/base.py", line 904, in render_annotated
>     return self.render(context)
>   File "django/template/defaulttags.py", line 209, in render
>     nodelist.append(node.render_annotated(context))
>   File "django/template/base.py", line 904, in render_annotated
>     return self.render(context)
>   File "django/template/defaulttags.py", line 209, in render
>     nodelist.append(node.render_annotated(context))
>   File "django/template/base.py", line 904, in render_annotated
>     return self.render(context)
>   File "django/template/defaulttags.py", line 309, in render
>     return nodelist.render(context)
>   File "django/template/base.py", line 937, in render
>     bit = node.render_annotated(context)
>   File "django/template/base.py", line 904, in render_annotated
>     return self.render(context)
>   File "django/template/defaulttags.py", line 309, in render
>     return nodelist.render(context)
>   File "django/template/base.py", line 937, in render
>     bit = node.render_annotated(context)
>   File "django/template/base.py", line 904, in render_annotated
>     return self.render(context)
>   File "django/template/base.py", line 993, in render
>     return render_value_in_context(output, context)
>   File "django/template/base.py", line 972, in render_value_in_context
>     value = str(value)
>   File "django/utils/html.py", line 397, in <lambda>
>     klass.__str__ = lambda self: mark_safe(klass_str(self))
>   File "django/forms/boundfield.py", line 33, in __str__
>     return self.as_widget()
>   File "django/forms/boundfield.py", line 93, in as_widget
>     renderer=self.form.renderer,
>   File "django/forms/widgets.py", line 229, in render
>     context = self.get_context(name, value, attrs)
>   File "django/forms/widgets.py", line 415, in get_context
>     context = super().get_context(name, value, attrs)
>   File "django/forms/widgets.py", line 281, in get_context
>     context = super().get_context(name, value, attrs)
>   File "django/forms/widgets.py", line 221, in get_context
>     'value': self.format_value(value),
>   File "django/forms/widgets.py", line 411, in format_value
>     if self.is_initial(value):
>   File "django/forms/widgets.py", line 405, in is_initial
>     return bool(value and getattr(value, 'url', False))
>   File "django/db/models/fields/files.py", line 62, in url
>     return self.storage.url(self.name)
>   File "django/utils/functional.py", line 213, in inner
>     self._setup()
>   File "django/core/files/storage.py", line 361, in _setup
>     self._wrapped = get_storage_class()()
>   File "django/core/files/storage.py", line 356, in get_storage_class
>     return import_string(import_path or settings.DEFAULT_FILE_STORAGE)
>   File "django/utils/module_loading.py", line 17, in import_string
>     module = import_module(module_path)
>   File "importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "config/backend/storage.py", line 13, in <module>
>     from storages.backends.gcloud import GoogleCloudStorage
>   File "storages/backends/gcloud.py", line 12, in <module>
>     from storages.utils import (

**Comment by sww314** [comment]
How did you install?
What version are you using of relevant tooling: Python, Django, Django-storages?
What environment: local, app engine, etc?

**Comment by dezmaeth** [comment]
Google Compute Engine instance

env
```
python3.6
django-storages[google]==1.7.1
django==2.1.1

```

**Comment by sww314** [comment]
What about your settings.py? (The relevant parts to storage.)
I run two projects on Google right now - one of GKE and the other on GCE and I have not seen this.

I have not upgraded to Django 2.1 yet.
