### ISSUE TITLE
Is there any way to use multiple instances of one storage class with different settings without subclassing?

### ISSUE THREAD

**Issue by lampslave** [jschneier/django-storages#691]
For example, if I want to use multiple s3-compatible storages in one project, I need to add subclass for all of them, because every storage uses own settings:

```python
class WasabiStorage(S3Boto3Storage):
    access_key_names = ['WASABI_S3_ACCESS_KEY_ID', 'WASABI_ACCESS_KEY_ID']
    secret_key_names = ['WASABI_S3_SECRET_ACCESS_KEY', 'WASABI_SECRET_ACCESS_KEY']
    security_token_names = ['WASABI_SESSION_TOKEN', 'WASABI_SECURITY_TOKEN']

    access_key = setting('WASABI_S3_ACCESS_KEY_ID', setting('WASABI_ACCESS_KEY_ID'))
    secret_key = setting('WASABI_S3_SECRET_ACCESS_KEY', setting('WASABI_SECRET_ACCESS_KEY'))
    file_overwrite = setting('WASABI_S3_FILE_OVERWRITE', True)
    object_parameters = setting('WASABI_S3_OBJECT_PARAMETERS', {})
    bucket_name = setting('WASABI_STORAGE_BUCKET_NAME')
    ...
```

```python
class YandexStorage(S3Boto3Storage):
    access_key_names = ['YANDEX_S3_ACCESS_KEY_ID', 'YANDEX_ACCESS_KEY_ID']
    secret_key_names = ['YANDEX_S3_SECRET_ACCESS_KEY', 'YANDEX_SECRET_ACCESS_KEY']
    security_token_names = ['YANDEX_SESSION_TOKEN', 'YANDEX_SECURITY_TOKEN']

    access_key = setting('YANDEX_S3_ACCESS_KEY_ID', setting('YANDEX_ACCESS_KEY_ID'))
    secret_key = setting('YANDEX_S3_SECRET_ACCESS_KEY', setting('YANDEX_SECRET_ACCESS_KEY'))
    file_overwrite = setting('YANDEX_S3_FILE_OVERWRITE', True)
    object_parameters = setting('YANDEX_S3_OBJECT_PARAMETERS', {})
    bucket_name = setting('YANDEX_STORAGE_BUCKET_NAME')
    ...
```

Is there another way to do same without code duplication?

**Comment by sww314** [comment]
No. How would you implement? You should only have to set the settings that are different, right?

**Comment by lampslave** [comment]
>You should only have to set the settings that are different, right?

Yes, all code is the same, but settings are different: access keys, endpoints, bucket names, etc.

>How would you implement?

I don't know, need to think.

Today I initialize storages in this way:

`my_project/storage.py`:

```python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.core.files.storage import get_storage_class
from django.utils.functional import LazyObject


class ColdFileStorage(LazyObject):
    def _setup(self):
        cold_file_storage_path = getattr(settings, 'COLD_FILE_STORAGE',
                                         settings.DEFAULT_FILE_STORAGE)
        self._wrapped = get_storage_class(cold_file_storage_path)()


cold_file_storage = ColdFileStorage()


class HotFileStorage(LazyObject):
    def _setup(self):
        hot_file_storage_path = getattr(settings, 'HOT_FILE_STORAGE',
                                        settings.DEFAULT_FILE_STORAGE)
        self._wrapped = get_storage_class(hot_file_storage_path)()


hot_file_storage = HotFileStorage()
```

`my_app/models.py`

```python
from my_project.storage import hot_file_storage


class MyModel(models.Model):
    file = models.FileField(storage=hot_file_storage)
```

`my_project/production_settings.py`:

```
HOT_FILE_STORAGE = 'path_to.WasabiStorage'
WASABI_ACCESS_KEY_ID = 'wasabi access key'
WASABI_SECRET_ACCESS_KEY = 'wasabi secret access key'
WASABI_STORAGE_BUCKET_NAME = 'wasabi bucket'
WASABI_S3_CUSTOM_DOMAIN = 'wasabi domain'
WASABI_QUERYSTRING_AUTH = False
WASABI_S3_SECURE_URLS = True
WASABI_S3_ENDPOINT_URL = 'https://s3.wasabisys.com'
WASABI_S3_MAX_MEMORY_SIZE = 50 * 1024 ** 2  # 50 MB
WASABI_S3_FILE_OVERWRITE = False
```

**Comment by sww314** [comment]
Looks similar to #433

I think one blocker that makes it difficult is each storage uses different configuration settings.

**Comment by nielslerches** [comment]
This would be rather nice to have.
Based on the code for the S3 I think the easiest solution would be to replace the class attributes with setting instance variables in the beginning of the `__init__` on the Storage subclass.

This would also not be a breaking change (atleast not when I immediately think about it.)

Moreover, consumers of this library can supply their own configuration setup to fit their needs (although something like function that returns a Storage instance based on a key from `STORAGES` in settings is an obvious addition.)

**Comment by pjxiao** [comment]
The storage constructor seems to accept settings via parameters, so it seems that we don't have to subclass to use multiple storages. However, the names of theses parameters are slightly different from settings.py. For instance, `AWS_STORAGE_BUCKET_NAME` in `settings.py` is `buckets_name` in the constructor parameter. This differences aren't documented. Isn't it expected to be passed theses parameters?

**Comment by SpencerPinegar** [comment]
# read type keys
PUBLIC_READ_TYPE = 'public-read'
PRIVATE_READ_TYPE = 'private'
DEFAULT_CONTENT_TYPE = 'application/octet-stream'

# backend
BACKEND_NAME_CLASS_KEY = '_backend_class_name'
BACKEND_NAME_KWARG_KEY = 'backend_name'
TARDIGRADE = 'TRD'
WASABI = 'WSB'
VALID_BACKENDS = [TARDIGRADE, WASABI]


#s3 keys

ACCESS_KEY_SUFFIX = '_ACCESS_KEY_ID'
SECRET_KEY_SUFFIX = '_SECRET_ACCESS_KEY'
FILE_OVERWRITE_SUFFIX, FILE_OVERWRITE_DEFAULT = '_S3_FILE_OVERWRITE', True
OBJECT_PARAMETERS_SUFFIX, OBJECT_PARAMETERS_DEFAULT = '_S3_OBJECT_PARAMETERS', {}
BUCKET_NAME_SUFFIX = '_STORAGE_BUCKET_NAME'
AUTO_CREATE_BUCKET_SUFFIX, AUTO_CREATE_BUCKET_DEFAULT = '_AUTO_CREATE_BUCKET', False
DEFAULT_ACL_SUFFIX, DEFAULT_ACL_DEFAULT = '_DEFAULT_ACL', PUBLIC_READ_TYPE
BUCKET_ACL_SUFFIX, BUCKET_ACL_DEFAULT = '_BUCKET_ACL', PUBLIC_READ_TYPE
QUERYSTRING_AUTH_SUFFIX, QUERYSTRING_AUTH_DEFAULT = '_QUERYSTRING_AUTH', True
QUERYSTRING_EXPIRE_SUFFIX, QUERYSTRING_EXPIRE_DEFAULT = '_QUERYSTRING_EXPIRE', 3600
SIGNATURE_VERSION_SUFFIX = '_S3_SIGNATURE_VERSION'
REDUCED_REDUNDANCY_SUFFIX, REDUCED_REDUNDANCY_DEFAULT = '_REDUCED_REDUNDANCY', False
LOCATION_SUFFIX, LOCATION_DEFAULT = '_LOCATION', ''
ENCRYPTION_SUFFIX, ENCRYPTION_DEFAULT = '_S3_ENCRYPTION', False
CUSTOM_DOMAIN_SUFFIX = '_S3_CUSTOM_DOMAIN'
ADDRESSING_STYLE_SUFFIX = '_S3_ADDRESSING_STYLE'
SECURE_URLS_SUFFIX, SECURE_URLS_DEFAULT = '_S3_SECURE_URLS', True
FILE_NAME_CHARSET_SUFFIX, FILE_NAME_CHARSET_DEFAULT = '_S3_FILE_NAME_CHARSET', 'utf-8'
GZIP_SUFFIX, GZIP_DEFAULT = '_IS_GZIPPED', False
PRELOAD_METADATA_SUFFIX, PRELOAD_METADATA_DEFAULT = '_PRELOAD_METADATA', False
GZIP_CONTENT_TYPES_SUFFIX, GZIP_CONTENT_TYPES_DEFAULT = '_GZIP_CONTENT_TYPES', (
    'text/css',
    'text/javascript',
    'application/javascript',
    'application/x-javascript',
    'image/svg+xml',
)
URL_PROTOCOL_SUFFIX, URL_PROTOCOL_DEFAULT = '_S3_URL_PROTOCOL', 'http:'
ENDPOINT_URL_SUFFIX = '_S3_ENDPOINT_URL'
PROXIES_SUFFIX = '_S3_PROXIES'
REGION_NAME_SUFFIX = '_S3_REGION_NAME'
USE_SSL_SUFFIX, USE_SSL_DEFAULT = '_S3_USE_SSL', True
VERIFY_SUFFIX, VERIFY_DEFAULT = '_S3_VERIFY', None
MAX_MEMORY_SIZE_SUFFIX, MAX_MEMORY_SIZE_DEFAULT = '_S3_MAX_MEMORY_SIZE', 0



class S3Boto3MetaClass(type):

    def __new__(mcs, name, bases, attrs, **kwargs):
        # create class
        nc = super().__new__(mcs, name, bases, attrs)
        # get class backend prefix
        try:
            backend_name = nc._backend_name
        except AttributeError:
            try:
                backend_name = kwargs[BACKEND_NAME_KWARG_KEY]
            except KeyError:
                raise RuntimeError(
                    f"S3Boto3MetaClass must be initialized with backend argument key {BACKEND_NAME_KWARG_KEY}")
        backend_name = str(backend_name).upper()
        if backend_name not in VALID_BACKENDS:
            raise RuntimeError(f'S3Boto3MetaClass must be initialized with valid backend key;\n'
                               f'Entered: {kwargs[BACKEND_NAME_KWARG_KEY]}\n Valid: {VALID_BACKENDS}')

        nc._backend_name = backend_name


        # set appropriate class variables for backend
        nc.access_key_names = [backend_name + ACCESS_KEY_SUFFIX, backend_name + ACCESS_KEY_SUFFIX.replace('_S3', '')]
        nc.secret_key_names = [backend_name + SECRET_KEY_SUFFIX, backend_name + SECRET_KEY_SUFFIX.replace('_S3', '')]
        print(nc.access_key_names)
        print(nc.secret_key_names)


        nc.access_key =         setting(backend_name + ACCESS_KEY_SUFFIX)
        nc.secret_key =         setting(backend_name + SECRET_KEY_SUFFIX)
        nc.file_overwrite =     setting(backend_name + FILE_OVERWRITE_SUFFIX, FILE_OVERWRITE_DEFAULT)
        nc.object_parameters =  setting(backend_name + OBJECT_PARAMETERS_SUFFIX, OBJECT_PARAMETERS_DEFAULT)
        nc.bucket_name =        setting(backend_name + BUCKET_NAME_SUFFIX)
        nc.auto_create_bucket = setting(backend_name + AUTO_CREATE_BUCKET_SUFFIX, AUTO_CREATE_BUCKET_DEFAULT)
        nc.default_acl =        setting(backend_name + DEFAULT_ACL_SUFFIX, PUBLIC_READ_TYPE)
        nc.bucket_acl =         setting(backend_name + BUCKET_ACL_SUFFIX, nc.default_acl)
        nc.querystring_auth =   setting(backend_name + QUERYSTRING_AUTH_SUFFIX, QUERYSTRING_AUTH_DEFAULT)
        nc.querystring_expire = setting(backend_name + QUERYSTRING_EXPIRE_SUFFIX, QUERYSTRING_EXPIRE_DEFAULT)
        nc.signature_version =  setting(backend_name + SIGNATURE_VERSION_SUFFIX)
        nc.reduced_redundancy = setting(backend_name + REDUCED_REDUNDANCY_SUFFIX, REDUCED_REDUNDANCY_DEFAULT)
        nc.location =           setting(backend_name + LOCATION_SUFFIX, LOCATION_DEFAULT)
        nc.encryption =         setting(backend_name + ENCRYPTION_SUFFIX, ENCRYPTION_DEFAULT)
        nc.custom_domain =      setting(backend_name + CUSTOM_DOMAIN_SUFFIX)
        nc.addressing_style =   setting(backend_name + ADDRESSING_STYLE_SUFFIX)
        nc.secure_urls =        setting(backend_name + SECURE_URLS_SUFFIX, SECURE_URLS_DEFAULT)
        nc.file_name_charset =  setting(backend_name + FILE_NAME_CHARSET_SUFFIX, FILE_NAME_CHARSET_DEFAULT)
        nc.gzip =               setting(backend_name + GZIP_SUFFIX, GZIP_DEFAULT)
        nc.preload_metadata =   setting(backend_name + PRELOAD_METADATA_SUFFIX, PRELOAD_METADATA_DEFAULT)
        nc.gzip_content_types = setting(backend_name + GZIP_CONTENT_TYPES_SUFFIX, GZIP_CONTENT_TYPES_DEFAULT)
        nc.url_protocol =       setting(backend_name + URL_PROTOCOL_SUFFIX, URL_PROTOCOL_DEFAULT)
        nc.endpoint_url =       setting(backend_name + ENDPOINT_URL_SUFFIX)
        nc.proxies =            setting(backend_name + PROXIES_SUFFIX)
        nc.region_name =        setting(backend_name + REGION_NAME_SUFFIX)
        nc.use_ssl =            setting(backend_name + USE_SSL_SUFFIX, USE_SSL_DEFAULT)
        nc.verify =             setting(backend_name + VERIFY_SUFFIX, VERIFY_DEFAULT)
        nc.max_memory_size =    setting(backend_name + MAX_MEMORY_SIZE_SUFFIX, MAX_MEMORY_SIZE_DEFAULT)
        return nc

**Comment by SpencerPinegar** [comment]
I would use a MetaClass that overrides settings on upon the initialization of the S3Boto3Storage backend to the correct values based on a class kwarg that links the storage to the appropriate keys in the Django settings File.

Below is an example

# read type keys
PUBLIC_READ_TYPE = 'public-read'
PRIVATE_READ_TYPE = 'private'
DEFAULT_CONTENT_TYPE = 'application/octet-stream'

# backend
BACKEND_NAME_CLASS_KEY = '_backend_class_name'
BACKEND_NAME_KWARG_KEY = 'backend_name'
TARDIGRADE = 'TRD'
WASABI = 'WSB'
VALID_BACKENDS = [TARDIGRADE, WASABI]


#s3 keys

ACCESS_KEY_SUFFIX = '_ACCESS_KEY_ID'
SECRET_KEY_SUFFIX = '_SECRET_ACCESS_KEY'
FILE_OVERWRITE_SUFFIX, FILE_OVERWRITE_DEFAULT = '_S3_FILE_OVERWRITE', True
OBJECT_PARAMETERS_SUFFIX, OBJECT_PARAMETERS_DEFAULT = '_S3_OBJECT_PARAMETERS', {}
BUCKET_NAME_SUFFIX = '_STORAGE_BUCKET_NAME'
AUTO_CREATE_BUCKET_SUFFIX, AUTO_CREATE_BUCKET_DEFAULT = '_AUTO_CREATE_BUCKET', False
DEFAULT_ACL_SUFFIX, DEFAULT_ACL_DEFAULT = '_DEFAULT_ACL', PUBLIC_READ_TYPE
BUCKET_ACL_SUFFIX, BUCKET_ACL_DEFAULT = '_BUCKET_ACL', PUBLIC_READ_TYPE
QUERYSTRING_AUTH_SUFFIX, QUERYSTRING_AUTH_DEFAULT = '_QUERYSTRING_AUTH', True
QUERYSTRING_EXPIRE_SUFFIX, QUERYSTRING_EXPIRE_DEFAULT = '_QUERYSTRING_EXPIRE', 3600
SIGNATURE_VERSION_SUFFIX = '_S3_SIGNATURE_VERSION'
REDUCED_REDUNDANCY_SUFFIX, REDUCED_REDUNDANCY_DEFAULT = '_REDUCED_REDUNDANCY', False
LOCATION_SUFFIX, LOCATION_DEFAULT = '_LOCATION', ''
ENCRYPTION_SUFFIX, ENCRYPTION_DEFAULT = '_S3_ENCRYPTION', False
CUSTOM_DOMAIN_SUFFIX = '_S3_CUSTOM_DOMAIN'
ADDRESSING_STYLE_SUFFIX = '_S3_ADDRESSING_STYLE'
SECURE_URLS_SUFFIX, SECURE_URLS_DEFAULT = '_S3_SECURE_URLS', True
FILE_NAME_CHARSET_SUFFIX, FILE_NAME_CHARSET_DEFAULT = '_S3_FILE_NAME_CHARSET', 'utf-8'
GZIP_SUFFIX, GZIP_DEFAULT = '_IS_GZIPPED', False
PRELOAD_METADATA_SUFFIX, PRELOAD_METADATA_DEFAULT = '_PRELOAD_METADATA', False
GZIP_CONTENT_TYPES_SUFFIX, GZIP_CONTENT_TYPES_DEFAULT = '_GZIP_CONTENT_TYPES', (
    'text/css',
    'text/javascript',
    'application/javascript',
    'application/x-javascript',
    'image/svg+xml',
)
URL_PROTOCOL_SUFFIX, URL_PROTOCOL_DEFAULT = '_S3_URL_PROTOCOL', 'http:'
ENDPOINT_URL_SUFFIX = '_S3_ENDPOINT_URL'
PROXIES_SUFFIX = '_S3_PROXIES'
REGION_NAME_SUFFIX = '_S3_REGION_NAME'
USE_SSL_SUFFIX, USE_SSL_DEFAULT = '_S3_USE_SSL', True
VERIFY_SUFFIX, VERIFY_DEFAULT = '_S3_VERIFY', None
MAX_MEMORY_SIZE_SUFFIX, MAX_MEMORY_SIZE_DEFAULT = '_S3_MAX_MEMORY_SIZE', 0



class S3Boto3MetaClass(type):

    def __new__(mcs, name, bases, attrs, **kwargs):
        # create class
        nc = super().__new__(mcs, name, bases, attrs)
        # get class backend prefix
        try:
            backend_name = nc._backend_name
        except AttributeError:
            try:
                backend_name = kwargs[BACKEND_NAME_KWARG_KEY]
            except KeyError:
                raise RuntimeError(
                    f"S3Boto3MetaClass must be initialized with backend argument key {BACKEND_NAME_KWARG_KEY}")
        backend_name = str(backend_name).upper()
        if backend_name not in VALID_BACKENDS:
            raise RuntimeError(f'S3Boto3MetaClass must be initialized with valid backend key;\n'
                               f'Entered: {kwargs[BACKEND_NAME_KWARG_KEY]}\n Valid: {VALID_BACKENDS}')

        nc._backend_name = backend_name


        # set appropriate class variables for backend
        nc.access_key_names = [backend_name + ACCESS_KEY_SUFFIX, backend_name + ACCESS_KEY_SUFFIX.replace('_S3', '')]
        nc.secret_key_names = [backend_name + SECRET_KEY_SUFFIX, backend_name + SECRET_KEY_SUFFIX.replace('_S3', '')]
        print(nc.access_key_names)
        print(nc.secret_key_names)


        nc.access_key =         setting(backend_name + ACCESS_KEY_SUFFIX)
        nc.secret_key =         setting(backend_name + SECRET_KEY_SUFFIX)
        nc.file_overwrite =     setting(backend_name + FILE_OVERWRITE_SUFFIX, FILE_OVERWRITE_DEFAULT)
        nc.object_parameters =  setting(backend_name + OBJECT_PARAMETERS_SUFFIX, OBJECT_PARAMETERS_DEFAULT)
        nc.bucket_name =        setting(backend_name + BUCKET_NAME_SUFFIX)
        nc.auto_create_bucket = setting(backend_name + AUTO_CREATE_BUCKET_SUFFIX, AUTO_CREATE_BUCKET_DEFAULT)
        nc.default_acl =        setting(backend_name + DEFAULT_ACL_SUFFIX, PUBLIC_READ_TYPE)
        nc.bucket_acl =         setting(backend_name + BUCKET_ACL_SUFFIX, nc.default_acl)
        nc.querystring_auth =   setting(backend_name + QUERYSTRING_AUTH_SUFFIX, QUERYSTRING_AUTH_DEFAULT)
        nc.querystring_expire = setting(backend_name + QUERYSTRING_EXPIRE_SUFFIX, QUERYSTRING_EXPIRE_DEFAULT)
        nc.signature_version =  setting(backend_name + SIGNATURE_VERSION_SUFFIX)
        nc.reduced_redundancy = setting(backend_name + REDUCED_REDUNDANCY_SUFFIX, REDUCED_REDUNDANCY_DEFAULT)
        nc.location =           setting(backend_name + LOCATION_SUFFIX, LOCATION_DEFAULT)
        nc.encryption =         setting(backend_name + ENCRYPTION_SUFFIX, ENCRYPTION_DEFAULT)
        nc.custom_domain =      setting(backend_name + CUSTOM_DOMAIN_SUFFIX)
        nc.addressing_style =   setting(backend_name + ADDRESSING_STYLE_SUFFIX)
        nc.secure_urls =        setting(backend_name + SECURE_URLS_SUFFIX, SECURE_URLS_DEFAULT)
        nc.file_name_charset =  setting(backend_name + FILE_NAME_CHARSET_SUFFIX, FILE_NAME_CHARSET_DEFAULT)
        nc.gzip =               setting(backend_name + GZIP_SUFFIX, GZIP_DEFAULT)
        nc.preload_metadata =   setting(backend_name + PRELOAD_METADATA_SUFFIX, PRELOAD_METADATA_DEFAULT)
        nc.gzip_content_types = setting(backend_name + GZIP_CONTENT_TYPES_SUFFIX, GZIP_CONTENT_TYPES_DEFAULT)
        nc.url_protocol =       setting(backend_name + URL_PROTOCOL_SUFFIX, URL_PROTOCOL_DEFAULT)
        nc.endpoint_url =       setting(backend_name + ENDPOINT_URL_SUFFIX)
        nc.proxies =            setting(backend_name + PROXIES_SUFFIX)
        nc.region_name =        setting(backend_name + REGION_NAME_SUFFIX)
        nc.use_ssl =            setting(backend_name + USE_SSL_SUFFIX, USE_SSL_DEFAULT)
        nc.verify =             setting(backend_name + VERIFY_SUFFIX, VERIFY_DEFAULT)
        nc.max_memory_size =    setting(backend_name + MAX_MEMORY_SIZE_SUFFIX, MAX_MEMORY_SIZE_DEFAULT)
        return nc


class S3BotoS3TRDStorage(S3Boto3Storage, metaclass=S3Boto3MetaClass, backend_name=TARDIGRADE):
    pass


class S3BotoS3WSBStorage(S3Boto3Storage, metaclass=S3Boto3MetaClass, backend_name=WASABI):
    pass

**Comment by jschneier** [comment]
Now there is in Django 4.2
