### ISSUE TITLE
S3 retrieve upload advance

### ISSUE THREAD

**Issue by millerf** [jschneier/django-storages#696]
Hi all,

I was wondering if there was an elegant way to retrieve the upload advance when saving the file to S3 for large files?

They seem to be sent in `multipart` so I am sure there is a way, but I don't want to dig into this before knowing if it was somehow implemented in `storage` already...

thanks!

**Comment by sww314** [comment]
I am not sure exactly what you are asking. Do you want to know the URL before the file is uploaded? Or something different?

I do not think this is implemented in storages. Storages implement the API from Django (https://docs.djangoproject.com/en/2.2/ref/files/storage/#the-storage-class) and is a fairly low-level file-like API. 

It is a common request to either save directly to the network storage from the client (JS or native) and then save the file location in Django. However, there is not an obvious way to do this with the current API, so it has not been tackled.

**Comment by millerf** [comment]
No, my question is about the advance of the upload. I am uploading big files to S3 and I wanted to update some local model about the %age of the file currently uploaded.

Unfortunately I don't see anything that could help me in your code...

**Comment by jschneier** [comment]
This is purely a server-side library. I have used something like Amazon Cognito to do upload from browser but that would require a different paradigm. Creating the final link by just creating a `File` is doable but is the bare minimum of the work.
