### ISSUE TITLE
Upload using HTTP POST

### ISSUE THREAD

**Issue by fabiancastano** [jschneier/django-storages#700]
Dear sirs, I try django-storages and it is very easy and efective way to integrate django and a storage service like amazon s3, give you congrutulations for this hard work.

But for my project I had to use uploads from client side, like amazon direct post. Because django-storages can not upload directly to amazon s3 like Direct Post Amazon s3*, for example: always upload file first to the tmp folder of Operative System; But we can no permit this performanse, because direct upload no overchargin our server VPS or Any server and this is work best between client side and amazon s3 service, my server is cold of work. It is fine. 

My questions is if django-storages can uplaod directly from client side: like direct post. 

Only inconvenient in Javascrip in direct form post upload is that api key is exposing.  

*https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html

Pd: I can upload a file direct post s3 bucket image in Javascript, and in the view django I can "save" a file with URL and simulate like we upload before. Too I have ussing django-storages for all side config to server static and media files.

**Comment by jschneier** [comment]
Hi, this isn't in the scope of this library. It is possible depending on exactly what you want to do but nothing to do with what we have here. Here's a link to some AWS docs that outlines one potential approach.

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/s3-example-photo-album.html

Best of luck.
