### ISSUE TITLE
Retry on Google upload 503

### ISSUE THREAD

**Issue by Natim** [jschneier/django-storages#702]
Lately we started to get a lot of 503 on Google Storage.
The model.save() method raises and creates a 500 on our end.
Is there a way to retry a couple of time in case the storage api raises a 503?

```
File "/usr/local/lib/python3.7/site-packages/storages/backends/gcloud.py", line 180, in _save
    file.blob.acl.save_predefined(self.default_acl)
File "/usr/local/lib/python3.7/site-packages/google/cloud/_http.py", line 319, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.ServiceUnavailable: 503 GET https://www.googleapis.com/storage/v1/b/bucket-id/o/uploads%2F74db120f-0a8e-5646-ef5a-30154e9f6deb_O15V4hn.jpg/acl: Backend Error
```

**Comment by sww314** [comment]
There is nothing now. I am not sure the storages layer is where you want to add a retry capability because it would block everywhere Django uses a file operation.

I think the 503s are caused by setting the ACL right after the image upload. 
This is fixed by #698, but it is not released yet. 
You can try it by installing master.

**Comment by Natim** [comment]
> I think the 503s are caused by setting the ACL right after the image upload.
> This is fixed by #698, but it is not released yet.
> You can try it by installing master.

Thank you for your answer, I am going to try this thanks.

**Comment by Natim** [comment]
I am closing for now and will reopen if I reach this issue again.

**Comment by Natim** [comment]
After almost a day in production no 503 anymore. I would be glad to have it tagged and released if someone has the mandatory permissions?
