### ISSUE TITLE
Azure broken by upstream version bump

### ISSUE THREAD

**Issue by taymonbeal** [jschneier/django-storages#704]
All URLs now return 403s. See Azure/azure-storage-python#595 for an explanation of why.

**Comment by jschneier** [comment]
I see you have a fix, do you want to open a PR with it?

**Comment by taymonbeal** [comment]
Working on it. The fix itself was trivial; creating an integration test to verify it is less so.

A particular issue I'm running into right now is that the integration tests run against the Azurite container on Docker Hub, which hasn't been updated in a year. Consequently, it doesn't accept the new signature format which azure-storage-python 2.0 generates.

This gets into a related issue: django-storages should not silently accept major version bumps of the Azure client libraries, since we've seen now that these can come with backwards-incompatible changes. Do you want to pin to 1.x, pin to 2.x, or accept (and test against) both?
