### ISSUE TITLE
django-storages is not working with latest boto3/botocore

### ISSUE THREAD

**Issue by mvbrn** [jschneier/django-storages#719]
boto3==1.9.176
botocore==1.12.176
django-storages==1.7.1

With those versions django-storages raises "ImproperlyConfigured: Could not load Boto3's S3 bindings. See https://github.com/boto/boto3"

With pinned boto3==1.9.129 and botocore==1.12.129 works just fine.

**Comment by jschneier** [comment]
I can't reproduce, I installed your same versions.

**Comment by Vuduong96** [comment]
I tried the version you mentioned, it still does not work :(. Any help?
