### ISSUE TITLE
edit upload file with azure

### ISSUE THREAD

**Issue by ThanhTuNguyen** [jschneier/django-storages#731]
hi there.

I'm working in a project which people can change their avatar in the client, but i can not do this with azure (i can do everything in admin but not in frontend) how can i do it
```

def ProfileSettingsView(request):
    form = forms.UserModifyForm(request.POST or None, instance=request.user)
    if request.method == 'POST':
        form = forms.UserModifyForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()

    return render(request, 'accounts/profile_settings.html', {'form': form})
```

is django-storage support this

**Comment by jschneier** [comment]
This library interacts server side and does not understand or work with client credentials. To do so you'd need to work with something like Amazon Cognito (or its Azure equivalent) which would still require **something** to grant permissions. If you need help on the server bits feel free to re open and add another comment.
