### ISSUE TITLE
Missing S3 authentication url params for some static paths

### ISSUE THREAD

**Issue by ajendrex** [jschneier/django-storages#734]
Hello,

some static paths are being rendered without the S3 authenticatoin url params (`AWSAccessKeyId`, `Signature` and `Expires`).
![imagen](https://user-images.githubusercontent.com/750470/62969189-b8a74180-bdda-11e9-9083-426b71f46579.png)

how should I debug this?

boto3==1.9.205
botocore==1.12.205
Django==2.2.4
django-tinymce==2.8.0
s3transfer==0.2.1

**Comment by AntoniosHadji** [comment]
I'm seeing the same issue with Django 3.02 and boto3 1.11.12.

The files that are missing the authentication urls are admin/css/fonts.css
and some svg files in admin/img/

**Comment by AntoniosHadji** [comment]
All the svg files that are failing for me are referenced via relative url `../`
The fonts.css file that is failing internally contains similar `../` relative locations for font files.

Here is an excerpt from `admin/css/base.css` which is correctly loading.
```
.addlink {
    padding-left: 16px;
    background: url(../img/icon-addlink.svg) 0 1px no-repeat;
}

.changelink, .inlinechangelink {
    padding-left: 16px;
    background: url(../img/icon-changelink.svg) 0 1px no-repeat;
}

.deletelink {
    padding-left: 16px;
    background: url(../img/icon-deletelink.svg) 0 1px no-repeat;
}
```
the above referenced urls are not resolving

**Comment by ajendrex** [comment]
Hello @AntoniosHadji,

perhaps you could give public access to your background images in S3...

Regarding my issue, I belive the problem was that the way tiny-mce was writting some static files paths was wrong, but our solution was simply to serve everything publicly on S3.

**Comment by AntoniosHadji** [comment]
@ajendrex Yes that would solve the issue, and maybe why there's not more people discussing this issue. In my case it's a corporate project and there is a lot of resistance to having any public buckets in the account.

**Comment by ajendrex** [comment]
> there is a lot of resistance to having any public buckets in the account.

I understand that you can configure public access to specific files within an private bucket, you wouldn't need to have a whole public bucket.

**Comment by probabble** [comment]
FWIW -- I just filed a related ticket with Django: https://code.djangoproject.com/ticket/31642#ticket

**Comment by fcaira** [comment]
@AntoniosHadji I'm experiencing almost exactly the same issue, and face similar inflexibility re. corporate security and public files/bucket. Have you found a solution yet?
The best one I've come up with is to re-write the stylesheets, but there are a lot...

**Comment by AntoniosHadji** [comment]
@fcaira  I loaded fonts from google fonts in the template 
```
{% extends "admin/base.html" %}
{% block extrahead %}
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
{% endblock %}
```

And I ignored the fact that icons were no longer loading.  In our case we are using standard django css and the icons missing are hardly noticeable .

**Comment by Tomply87** [comment]
Same issue. Any updates?

**Comment by denizdogan** [comment]
So basically this is impossible to fix without actually post-processing (and therefore downloading) each CSS file, which is a time-consuming process when the storage is remote.

The Django ticket [referenced above](https://github.com/jschneier/django-storages/issues/734#issuecomment-636351443) was closed as "wontfix". I personally think it's unfortunate and honestly unnecessary, since the only places where django.contrib.admin uses the `@import` syntax is one import of fonts.css, which is 20 lines of code, from base.css and one import of widgets.css from forms.css. Readability and maintainability of the stylesheets isn't even an argument in my opinion, since it's plain old CSS which has never *not* turned into an unmaintainable dish of spaghetti.

I'm not going to go out of my way to hack this into kinda working, back to local storage it is.

**Comment by dennisvang** [comment]
> @fcaira I loaded fonts from google fonts in the template
> 
> ```
> {% extends "admin/base.html" %}
> {% block extrahead %}
>   <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
> {% endblock %}
> ```
> 
> And I ignored the fact that icons were no longer loading. In our case we are using standard django css and the icons missing are hardly noticeable .

A missing `search.svg` icon on a [raw id field](https://docs.djangoproject.com/en/3.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.raw_id_fields) can be quite confusing, and a missing `widgets.css` really messes up the layout for [filter_horizontal](https://docs.djangoproject.com/en/3.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.filter_horizontal) fields.

**Comment by dennisvang** [comment]
A workaround could be to use a whitelist to set specific files to `public-read` during upload.

See [source](https://github.com/jschneier/django-storages/blob/1.11.1/storages/backends/s3boto3.py#L497) for more info.

Here's a quick example using a custom static-storage class:

    from fnmatch import fnmatch  # allows us to use wildcards, simpler than e.g. re
    from django.conf import settings
    from storages.backends.s3boto3 import S3Boto3Storage
    
    WHITELIST = ['admin/css/widgets.css', 'admin/css/fonts.css', 'admin/fonts/*.woff', 'admin/img/*.svg']

    class S3StaticStorage(S3Boto3Storage):
        bucket_name = settings.AWS_S3_STATIC_BUCKET_NAME
        default_acl = None  # use S3 bucket default (i.e. private)
        querystring_auth = True  # automatically generate pre-signed urls
        querystring_expire = 3600  # pre-signed urls expire after this many seconds

        def get_object_parameters(self, name):
            """ override the ACL value for whitelisted files """
            object_parameters = super().get_object_parameters(name=name)
            if any(fnmatch(name, pattern) for pattern in WHITELIST):
                object_parameters['ACL'] = 'public-read'
            return object_parameters

**Comment by jschneier** [comment]
`get_object_parameters` was added specifically for issues like this, maybe worth a call out in the docs.

**Comment by dennisvang** [comment]
Apparently, the `get_object_parameters()` workaround I described [above][1] does not work if the bucket's ACL is disabled using the "Bucket owner enforced" setting for "Object Ownership", despite having a working [bucket policy like that in the docs][2].

It results in the following error:

```none
botocore.exceptions.ClientError: An error occurred (AccessControlListNotSupported) when calling the PutObject operation: The bucket does not allow ACLs
```


[1]: https://github.com/jschneier/django-storages/issues/734#issuecomment-779986106
[2]: https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#iam-policy
