### ISSUE TITLE
GCS Location - How To Set

### ISSUE THREAD

**Issue by SteveChurch** [jschneier/django-storages#740]
Am I missing something, when using Django Storages how do I set the Region and Location where the Bucket is created? - It always defaults to US when auto-creating the bucket. 

Any guidance would be great, I have exhausted the documentation.

**Comment by jschneier** [comment]
You're correct, almost no one uses the auto creation logic so this feature isn't currently supported. My intent has been to remove auto-creation, do you find it useful/necessary? Generally speaking it requires elevated permission than what should be given to this library I think.

**Comment by jschneier** [comment]
Automatic bucket creation has been removed.
