### ISSUE TITLE
Multiple buckets for Google cloud storage

### ISSUE THREAD

**Issue by sr6033** [jschneier/django-storages#744]
Is there any way to access multiple buckets in GCS. Something like the below done in AWS:
```
from django.db import models
from storages.backends.s3boto import S3BotoStorage

class MyModel(models.Model):
    file_1 = models.FileField() # Uses default storage
    file_2 = models.FileField(storage=S3BotoStorage(bucket='other-bucket')) # another bucket that I need
``` 

I have been trying the below, but the default storage `GS_BUCKET_NAME` is not getting overridden:
```
file = models.FileField(storage=GoogleCloudStorage(bucket='crm-param-staging-temporary-files'), upload_to='reports', max_length=256)
```

**Comment by jschneier** [comment]
Oh for whatever reason when the `GoogleCloudStorage` was added it was `bucket_name` rather than `bucket`. Making that consistent is a good idea. That should fix your problem.

**Comment by sr6033** [comment]
@jschneier Isn't it also a nice thing to add these in the docs to make it easier for anyone to get the idea in one page itself?
