### ISSUE TITLE
S3 custom domain should be based on bucket name

### ISSUE THREAD

**Issue by rivernews** [jschneier/django-storages#748]
I override the class `S3Boto3Storage` to create my own custom storage like below

```python
class MediaStorage(S3Boto3Storage):
    bucket_name = 'my-media-bucket'
```

I was expecting the file url generated by my custom storage `MediaStorage` will honor the bucket name and give the correct file url when I do the following:

```python
media_storage = MediaStorage()
media_storage.save(additional_path, file_obj)
file_url = media_storage.url(additional_path)
```

However, the generated `file_url` gives me a 404. When I look into the url, it did not use the bucket name of `MediaStorage` in domain name. After I looked at the implementation of the class `S3Boto3Storage`, the url is indeed not using `bucket_name` to generate url, and instead it always uses `settings.AWS_S3_CUSTOM_DOMAIN`, which I already set for my static file storage.

I can see that the file is uploaded on S3, and the url S3 generated for the file is like `https://my-media-bucket.s3.amazonaws.com/path/to/the/file/`. I was expecting when I override `bucket_name`, the storage should use the bucket name to generate the url.

I'm wondering is there any reason not to use bucket name to generate the url, or set the custom domain?

I'm thinking of in class `S3Boto3Storage`, `def __init__`, let `custom_domain` honor `bucket_name` during the initialization. There're two ways I can think of:
1. Set `custom_domain` to `self.custom_domain = '{}.s3.amazonaws.com'.format(self.bucket_name)`
2. Replace the lowest level subdomain of `custom_domain` by `bucket_name`, if custom_domain is set.

If any of these sounds good, I can create a PR, but just want to make sure if there's any consideration for the current behavior or concern about the change beforehand. Thank you!

**Comment by jschneier** [comment]
``AWS_S3_CUSTOM_DOMAIN`` is meant for dealing with CDNs. It sounds like you have multiple storages and the issue is that the 2nd is using the settings from the first. Instead of using the library setting you could set `custom_domain` on the first one yourself and then the default logic should just work.

Does that make sense?

**Comment by rivernews** [comment]
Yes, I'm using two buckets, one for static and another for media files.

Do you mean setting `custom_domain` like below? Indeed it's now working, I just have to reference to `bucket_name`:

```python
class MediaStorage(S3Boto3Storage):
    bucket_name = 'my-media-bucket'
    custom_domain = '{}.s3.amazonaws.com'.format(bucket_name)
```

What I intended to do is to save a file on S3, and get the url to access the file. When I call `media_storage.url(my_file_path_within_bucket)`, I thought it will generate the file url in the bucket that I specified in `MediaStorage.bucket_name`. So I was a bit surprised when I see the url is not using my override class bucket. 

After giving a closer look at the implementation of `S3Boto3Storage.url()`, seems like if I don't set `AWS_S3_CUSTOM_DOMAIN ` in settings, it will indeed use `self.bucket` to generate the url. I'm wondering what's recommended in my case to retrieve file url, either manually set `MediaStorage.custom_domain` besides `bucket_name`, or just remove `AWS_S3_CUSTOM_DOMAIN` from settings?


The documentation doesn't mention how to override the `S3Boto3Storage` class. The current behavior of `url()` doesn't seem quite intuitive, so I think it will be helpful to provide some instruction about how to override `S3Boto3Storage`, or describe the behavior of `url()`? I can contribute to the doc if you think it will be helpful.

**Comment by jschneier** [comment]
Absolutely, updating the docs is always useful!
