### ISSUE TITLE
Digital ocean media files is private by default

### ISSUE THREAD

**Issue by Stefanitsky** [jschneier/django-storages#768]
Hello. I found a bug (maybe) https://github.com/pydanny/cookiecutter-django/issues/1878#thread-subscription-status. I cant upload media files to the digital ocean space with public rights, it's always private by default. I tried to override class attributes like `default-acl`, but nothing changed. I will be glad to see any ideas about that problem.

MEDIA settings:
```python
class MediaRootS3Boto3Storage(S3Boto3Storage):
    location = "media"
    default_acl = "public-read"


# endregion
DEFAULT_FILE_STORAGE = "config.settings.production.MediaRootS3Boto3Storage"
MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/media/"
```

**Comment by offsideAI** [comment]
The above doesn't work with Django 4.2 and higher (4.2.4 is my version).
