### ISSUE TITLE
Amazon S3 storage overwrites files with the same name by default

### ISSUE THREAD

**Issue by tomlaszczuk** [jschneier/django-storages#77]
Hi.

To change this default behavior we need to put in settings
AWS_S3_FILE_OVERWRITE = False

I haven't found that info in the official documentation. It would be nice to update this

**Comment by matthieubellon** [comment]
Hi,

I may not understand your request but this is the way S3 works. Files with exact same keys are overwritten. How would change that in settings ?

**Comment by camilonova** [comment]
I just needs to be documented somewhere. I can to that, where will be the best place?

**Comment by camilonova** [comment]
Duplicated of #50

**Comment by jschneier** [comment]
This has been documented for a while. Going to consider changing this on a major version bump.
