### ISSUE TITLE
Get uploaded image URL from Dropbox (Django Rest Framework)

### ISSUE THREAD

**Issue by akritkhanna** [jschneier/django-storages#771]
As my title describes, How to get the URL of image uploaded to Dropbox in Django Rest Framework API view.

I'm able to upload image to Dropbox but it is giving me a downloadable link in response. I searched everything possible but I'm unable to find any solution.

Getting {"avatar_url": "some_very_long_downloadable_link"}

Expected {"avatar_url": "domain.com/image.jpg"}

Thanks

**Comment by ochui** [comment]
This is not an issue, please consider closing it
