### ISSUE TITLE
SFTP Storage 

### ISSUE THREAD

**Issue by jamalroger** [jschneier/django-storages#772]
hi guys 

i have read the documentation but this  isn't enough to understand how to work with sftp 

could you please expland more how to work with sftp storage  ??
i have add to setting this params but not working

` DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

 STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

 SFTP_STORAGE_HOST='host'

 SFTP_STORAGE_ROOT='/home/jamal/'

 SFTP_STORAGE_PARAMS={
 'username':'jamal',
 'password':'xxxxx'
}
`

**Comment by jschneier** [comment]
You need to use the `SFTPStorage` backend, not the `S3Boto3` one for use with `sftp`.

**Comment by jamalroger** [comment]
Thanks
