### ISSUE TITLE
django-storages upload to S3 closes server with no error

### ISSUE THREAD

**Issue by anuj9196** [jschneier/django-storages#777]
I'm using **Django 2.x** and **django-storages** to upload media files to the **S3 Bucket**.

My model is like

    class Media(models.Model):
        user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, default=None)
        file = models.FileField(upload_to=get_media_upload_path)

The Django settings have

    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_STORAGE_BUCKET_NAME = os.environ.get('S3_STORAGE', 'test-bucket')
    AWS_DEFAULT_ACL = 'public-read'

and the environment variable is set for

    AWS_ACCESS_KEY_ID=my-key
    AWS_SECRET_ACCESS_KEY=my-secret

**When I upload a file from the postman, it closes the server without any error.**

I tried debugging DRF Serializer's save method

    def save(self, **kwargs):
        log.info('Saving with kwargs: {}'.format(kwargs))
        new = super().save(**kwargs)
        log.info('Saved: {}'.format(new))
        return new

It prints the first line, but no output after the `super().save()` line.

Removing `django-storages` configuration from the settings file is working fine and uploading files in the local directory.

> Edit 2: Upload from Django shell

uploading from Django shell with the following command

    file = File(open('/path/to/file'))
    m = Media(user=user, file=file)
    m.save()

gives error

    File "/home/scanova/.virtualenvs/qcg-TqOLHEIu/lib/python3.7/site-packages/s3transfer/upload.py", line 86, in read
       return self._fileobj.read(amount)
    File "/home/scanova/.virtualenvs/qcg-TqOLHEIu/lib/python3.7/codecs.py", line 322, in decode
       (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 10: invalid continuation byte

**Comment by sseveringhaus-newclassrooms** [comment]
You probably need to open your file in binary mode:
```
file = File(open('/path/to/file', 'rb'))
```
