### ISSUE TITLE
Multiple S3 Buckets

### ISSUE THREAD

**Issue by steverecio** [jschneier/django-storages#789]
Is there a way to create two separate s3 buckets? One with public-read and one set to private? Some files uploaded I need to proxy through my server for security reasons (private bucket) and another that I'd like to serve the files directly from s3 (public bucket). What's the best way to do that?

I see `AWS_STORAGE_BUCKET_NAME` takes a string and not a list so it seems like there's only one bucket that you can use with django-storages?

**Comment by jschneier** [comment]
Generally what people do is import the class, subclass it and then set the properties on the class level (which can be done through environment variable for the sensitive ones).

**Comment by jschneier** [comment]
I should add this to the docs since it seems like a pretty common ask.

**Comment by steverecio** [comment]
Ok yeah maybe documentation would help. I tried subclassing `S3Boto3Storage` but couldn't get it working. I ended up just creating a new folder in my primary bucket called `public` with anonymous GET access.

**Comment by jschneier** [comment]
On file fields you can specify `storage=` by default it uses the default storage. Just mentioning in case that’s why you couldn’t get it working.
