### ISSUE TITLE
Development files uploaded to production

### ISSUE THREAD

**Issue by JimmyVT** [jschneier/django-storages#796]
Hi !

I've just installed django-storages[google] on my development machine. Everything works fine, but I noticed that the files I upload on develoment are actually uploaded to my production bucket.

Is this normal behavior? Are there special settings for development?

Thank you!

**Comment by jschneier** [comment]
I recommend setting up a separate bucket and to set it via env var. The
other option is to use a different kind of storage for local dev.

Both have trade offs.
