### ISSUE TITLE
folder creation feature

### ISSUE THREAD

**Issue by lijoev** [jschneier/django-storages#804]
Is there a way to create folder using django-storages in s3. I could upload files to s3 using django-storage but i could not do it for folder.

**Comment by igorpejic** [comment]
You need to upload all the files, and then create the directory manually.

Take a look at: https://stackoverflow.com/a/59730164/3865158

**Comment by jschneier** [comment]
S3 is a completely flat structure. The illusion of "directories" or "folders" is a convention with using `/`.
