### ISSUE TITLE
Upload file to Azure Blobstore with only SAS token, with no account key

### ISSUE THREAD

**Issue by julzhk** [jschneier/django-storages#815]
I would like to upload a file from Django with just AZURE_TOKEN_CREDENTIAL set, but no AZURE_ACCOUNT_KEY but it doesn't seem to work - I get the following errors: 

```
  AttributeError: 'str' object has no attribute 'sign_request'
  azure.common.AzureException: 'str' object has no attribute 'signed_session'
```

My relevant settings are:
```
AZURE_URL_EXPIRATION_SECS =9999
AZURE_ACCOUNT_NAME = '<my_account>'
AZURE_CONTAINER = 'assets'
AZURE_OVERWRITE_FILES = True
AZURE_SSL = True
AZURE_TOKEN_CREDENTIAL = '?sv=2019-02-02&ss=b&srt=co&sp=<OMITTED>'
DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'
```

Thanks in advance for any suggestions or hints!

**Comment by nitely** [comment]
The token credential is for to access files. What you want is the `AZURE_SAS_TOKEN` setting. I forgot to document it.

As a workaround you can use the connection string for any missing setting.
Example:
`AZURE_CONNECTION_STRING='BlobEndpoint=https://storagesample.blob.core.windows.net;
SharedAccessSignature=sv=2015-04-05&sr=b&si=tutorial-policy-635959936145100803&sig=9aCzs76n0E7y5BpEi2GvsSv433BZa22leDOZXX%2BXXIU%3D'`
