### ISSUE TITLE
dropbox storages pattern error

### ISSUE THREAD

**Issue by maharshi-b** [jschneier/django-storages#817]
This is my  settings code
DEFAULT_FILE_STORAGE = 'storages.backends.dropbox.DropBoxStorage'
DROPBOX_OAUTH2_TOKEN = "my token"
DROPBOX_ROOT_PATH = "Apps/Djangoproject"

ValidationError:  did not match pattern '(/(.|[\r\n])*|id:.*)|(rev:[0-9a-f]{9,})|(ns:[0-9]+(/.*)?)'
how to solve this  issue?

**Comment by jschneier** [comment]
Likely your root path doesn't match the regex, please check out Dropbox library docs or ask the maintainer there, this is not a django-storages issue.
