### ISSUE TITLE
Cannot configure CDN for Azure

### ISSUE THREAD

**Issue by rhewid** [jschneier/django-storages#822]
Hello there!

I want to create a CDN connection to cache data on the azure storage for my website.
For that I want to use a SAS(Shared Access Signature) and not the account key.
The following parameters are being used:

AZURE_ACCOUNT_NAME = <name of the account>
AZURE_TOKEN_CREDENTIAL = <?sv=2020... > # The SAS key
AZURE_CUSTOM_DOMAIN = <https://_**mycdnname**_.azureedge.net>
AZURE_CACHE_CONTROL = "public,max-age=31536000,immutable"
DEFAULT_FILE_STORAGE = <file storage name>
STATICFILES_STORAGE = <name of the static folder>

These settings produce the following error:

` self.account_key should not be None.`

As already mentioned I want to use it **without** the AZURE_ACCOUNT_KEY and instead use SAS.
I also tried pasting the AZURE_TOKEN_CREDENTIAL value to the AZURE_ACCOUNT_KEY which results in 403 errors. 

Thank you in advance!

**Comment by nitely** [comment]
Set `AZURE_SAS_TOKEN` instead of `AZURE_TOKEN_CREDENTIAL`. See #815
