### ISSUE TITLE
Blackbraze support

### ISSUE THREAD

**Issue by kousuke-takeuchi** [jschneier/django-storages#83]
Backbraze will release cloud storage service like S3, but cheaper.
This low-cost storage will be expand with considering following article.

http://techcrunch.com/2015/09/22/backblaze-b2/

so, it would be nice to implement into django-storages.
Backbraze doesn't release in public now, but they provide nice docs.
We can start from now although the service is not start yet.

https://www.backblaze.com/b2/docs/

Best Regards.
Kousuke Takeuchi

**Comment by bartoszhernas** [comment]
Is anyone working on this?

**Comment by fresh-django** [comment]
I have beta access and I've been messing around with this. However, I'm not entirely sure it belongs in django-storages as I think to utilize B2 properly and efficiently you'll need to store a bunch of stuff in the db for each file, which is more than simply a storage backend. 

I'm keen to get this working as a stable solution, however I have to admit I've ver little django experience. 

Here's my efforts so far: http://pastebin.com/DSipfXdc

**Comment by miki725** [comment]
Havent looked at Backblaze docs however I think it would be nice it if can be included with django-storages. In simple implementation, this library can assume a single version of the file. Basically mimic S3 behavior as much as possible. If people will need to utilize more advanced B2 features, they will have to implement the more advanced functionality themselves or use only-B2-specific storage backend (if one is ever created on PyPI).

**Comment by gagandeep** [comment]
Didn't tried yet but seems libcloud support backblaze. So, that could be utilized.

**Comment by bedros** [comment]
check out b2 tools which has sync command with --delete option, it would not keep versions and it would overwrite existing files

**Comment by royendgel** [comment]
Hi there, I did this, is their any guide how to integrate this in django-storages https://github.com/royendgel/django-backblazeb2-storage ? or simply pull-request?

**Comment by metakermit** [comment]
Another potentially relevant implementation [here](https://github.com/amlatyrngom/django-b2storage). It seems to support urls, which in @royendgel's version seems to be under development – https://github.com/royendgel/django-backblazeb2-storage/pull/6

**Comment by psychok7** [comment]
Any movement on this??

@royendgel if you could make a Pull Request i don't see why they would not accept it

**Comment by metakermit** [comment]
You can use @royendgel's version. The URL issue has been fixed. Installation instructions in the README:

https://github.com/royendgel/django-backblazeb2-storage
