### ISSUE TITLE
Deal Multiple Dynamic s3-Buckets 

### ISSUE THREAD

**Issue by hbiswas-ecl** [jschneier/django-storages#832]
Is there a way to specify custom bucket name  depend on Model instance.

suppose, `image` is field name of a model, `bucket_name` is  also a field of this model which containing bucket name. Can I pass this `bucket_name` to `S3Boto3Storage` as bucket
** Every instances of the model  may use different bucket name also based on logic

`image = models.ImageField(storage=S3Boto3Storage())`

**Comment by jschneier** [comment]
Yes you could have used multiple instances and with 4.2 there exists a STORAGES api.
