### ISSUE TITLE
SFTPStorage silently swallows exception for connection failures

### ISSUE THREAD

**Issue by pansapiens** [jschneier/django-storages#835]
Specifically: https://github.com/jschneier/django-storages/blob/ec9579b48606517a489bb79a869c78462c322422/storages/backends/sftpstorage.py#L81-L82

Wouldn't it be better to raise the exception to allow it to be handled by calling code ?
It's been causing issues in my use case, since there's no easy way to handle connection failure to SFTP servers that are offline.

eg attempting to connect to a server that doesn't exist:
```python
from storages.backends.sftpstorage import SFTPStorage

params = dict(port=22,
              username='root',
              password='hunter')
storage = SFTPStorage(host='does-not.exist-domain.example.com', params=params)
storage._connect()
storage.sftp
```

Outputs:
```
[Errno -2] Name or service not known
[Errno -2] Name or service not known
```

rather than raising an exception.

I can work around this issue by calling these private methods before attempting to use the `SFTPStorage` instance, but it's more of a hacky workaround:
```
storage._connect()  # so that ._ssh exists
 # will raise an exception if connection fails
storage._ssh.connect(storage._host, **storage._params)
```

**Comment by jschneier** [comment]
Yep. If you open a PR I will merge it.

Also, think you mean `hunter2` :)

**Comment by pansapiens** [comment]
Will do. Not sure what you mean by `*******` though :)
