### ISSUE TITLE
Image not being deleted from Google Cloud Storage

### ISSUE THREAD

**Issue by deadpyxel** [jschneier/django-storages#848]
Hello, first, thanks for the awesome library you built.

I'm developing a Django Rest Framework API using your library to handle file upload and using TDD to develop my API. 

In your documentation you say `Deleting an object deletes the file it uses, if there are no other objects still using that file`, so once the tearDown occurs, the file should be deleted from GCP too as I understood.

This is not happening, and since I can upload files fine, I wonder if this is misconfiguration or an edge case with unit testing. This is an example of the unit test I'm running:
```python
def test_can_attach_file_to_ticket(self):
        url = reverse("ticket-details", kwargs={"pk": self.dummy_ticket.pk})
        image = generate_dummy_image()
        data = {"attachments": image}

        response = self.client.patch(url, data, format="multipart")

        self.assertEqual(
            response.status_code,
            status.HTTP_200_OK,
            msg=f"Error: Response code was {response.status_code}, {response.content}",
        )
        self.assertIn("attachments", response.json())
        self.assertEquals(response.json()["attachments"], image)
```
`generate_dummy_image` is a function that just generates a simple 50x50 image to test the upload. The field `attachments` right now holds only one image, but later will be converted to an Array field, that will store at max 5 images. Just so you know, upload is fine, is the removal that is giving me trouble. I also tested removal with a DELETE request, and the file stays there.

I also tried to create a `tearDown`:
```python
def tearDown(self):
    for ticket in Ticket.objects.all():
        ticket.delete()
```

So I am in need of some guidance. Sorry if this is a very basic error by me.

**Comment by jschneier** [comment]
Unfortunately the docs are wrong & were likely copy/pasted from an earlier backend. Django *used* to do that but hasn't in a while, see:

https://stackoverflow.com/questions/16041232/django-delete-filefield
https://docs.djangoproject.com/en/3.0/releases/1.3/#deleting-a-model-doesn-t-delete-associated-files

I will fix the docs.

**Comment by deadpyxel** [comment]
Thanks for the reply. I'll handle the deletion using some custom code.
