### ISSUE TITLE
Django 3.0 - No module names 'django.utils.six'

### ISSUE THREAD

**Issue by python-force** [jschneier/django-storages#849]
Six was removed in Django 3.0

https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py
`from django.utils.six.moves.urllib import parse as urlparse`

**Comment by jdufresne** [comment]
This issue will be fixed by PR #709.

**Comment by python-force** [comment]
Do you know probably when? - the PR was opened 10 months ago

**Comment by rjmackay** [comment]
I think this may already be fixed? It looks like six is now only imported if it's available.

**Comment by jschneier** [comment]
Fixed in 1.8
