### ISSUE TITLE
Auto creation of buckets

### ISSUE THREAD

**Issue by WhyNotHugo** [jschneier/django-storages#850]
Hi. I've been using `AWS_AUTO_CREATE_BUCKET` for a long while now, since it's super useful for development, CI, and testing.

I've now seen this new warning:
```
/usr/local/lib/python3.8/site-packages/storages/backends/s3boto3.py:279: DeprecationWarning: Automatic bucket creation will be removed in version 1.10. It encourages using overly broad credentials with this library. Either create it before manually or use one of a myriad of automatic configuration management tools. Unset AWS_AUTO_CREATE_BUCKET (it defaults to False) to silence this warning.
```

I strongly rely on this feature, and it'll harm development enormously for me. I really don't see the rationale for removing it.

On many of my projects, we use numerous buckets, and run local development environments, testing and CI with `minio` (an S3-like local service). Thanks to it, setting up a new local environment is just running the app, and new buckets are created for us automatically.  
However, with this change, creating local development environments (which happens for weekly) and CI (which happens multiple times a day) will become extremely clumbersome; since I'll need to figure out mechanisms of creating buckets, and somehow hack this into the app's bootstrap (or maybe patch the storage somehow?).

Can we discuss keeping this very useful feature around? It's working great as-is, and I'd really hate having to create and install an additional django app just to re-implement this.

**Comment by WhyNotHugo** [comment]
Hi. Any feedback here?

I'd like to know if this is open for discussion, or if it's a taken decision by the author with no room for open discussion.

**Comment by zerolab** [comment]
There is this old comment - https://github.com/jschneier/django-storages/issues/574#issuecomment-417755274 - that suggest the deprecation is there because it introduces more issues than it solves.
Maybe this could be used with `DEBUG=True` only?

**Comment by humitos** [comment]
>  Maybe this could be used with `DEBUG=True` only?

This is exactly the use case that I personally need. So that would solve my issue at least.

**Comment by WhyNotHugo** [comment]
`DEBUG=True` would work when developing, but not CI. I'd rather avoid having to write scripts to create those.

FWIW, this change won't make irresponsable users start using more restrictive permissions in AWS.

**Comment by jschneier** [comment]
Not reopening.
