### ISSUE TITLE
Subclassing SFTPStorage

### ISSUE THREAD

**Issue by DoctorJohn** [jschneier/django-storages#851]
I'd like to subclass the SFTPStorage class so that I can have multiple SFTP backends. That's already conveniently possible with most of the other backends, as their settings can be provided using class variables.

The SFTPStorage class, however, only works with global settings or parameters passed to it's `__init__` method. Thus subclassing requires overriding `__init__`, which doesn't feel as clean as providing class variables.

Is this intended? Otherwise I could create an PR which would adjust the SFTPStorage to allow convenient subclassing similar to the other backends.

**Comment by jschneier** [comment]
Sure, would absolutely accept a PR

**Comment by DoctorJohn** [comment]
@jschneier I prepared a PR (#852), it's ready to be reviewed.

**Comment by jschneier** [comment]
Closed via #852
