### ISSUE TITLE
azure_storage.py => TypeError: __init__() got an unexpected keyword argument 'token_credential'

### ISSUE THREAD

**Issue by ernestocasanova** [jschneier/django-storages#861]
Hi. I'm facing one issue with this package. I'm currently using Azure container to serve my static and media files, but the next error happens every time I install the package.

Error: \env\lib\site-packages\storages\backends\azure_storage.py", line 163, in _blob_service
    endpoint_suffix=self.endpoint_suffix)
TypeError: __init__() got an unexpected keyword argument 'token_credential'

To fix i need removing/comment the line 162 => **token_credential=self.token_credential,**

I'm running with Django 2.2.5 and Python 3.6 (64-bit). Any idea for the reason that this happen?

**Comment by jschneier** [comment]
What version of `azure-storage-blob` do you have installed? Looks like it was added in 1.2.0 or so.

**Comment by ernestocasanova** [comment]
Hi, I have the azure-storage-blob==12.1.0 installed.

**Comment by ernestocasanova** [comment]
Hi, I removed the solution virtual env and install all again, looks like I found the correct versions match, without comment or remove any code. I'm goig to test and I'll send feedback to close this issue.

For Python 3.6 and:

Django==2.2.5
azure-common==1.1.16
azure-core==1.3.0
azure-mgmt-nspkg==3.0.2
azure-nspkg==3.0.2
azure-storage==0.36.0
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
azure-storage-nspkg==3.0.0
django-storages==1.9.1

**Comment by ernestocasanova** [comment]
I you can close the issue, It was in fact package mismatch versions. Thanks for your time.
