### ISSUE TITLE
FileField.save() appears to be failing silently using S3Boto3Storage

### ISSUE THREAD

**Issue by nthall** [jschneier/django-storages#863]
I'm using django-storages 1.9.1, python 3.6.8, django 1.11.18, and boto3 1.10.45. My app includes a model which generates a file and saves it to a FileField. I'm using S3Boto3Storage as my backend. When I try to do `instance.file_field.save(filename, file_obj)`, there is no error, but if I then check `instance.file_field` it is None. However the file does get uploaded to the correct place in S3. To have the file accessible as expected, after `instance.file_field.save()` I'm additionally assigning `instance.file_field.name = filename` and saving the model instance again. This "works," but it feels clunky and doesn't seem right. I cannot figure out whether I am doing something wrong, or if the issue lies somewhere else.

**Comment by jschneier** [comment]
Can you set a breakpoint and see what's going on? The name is properly returned from `_save` and I just spelunked a little bit into Django which seems like it should do it.

**Comment by nthall** [comment]
apologies - while going back to put in breakpoints, i found the error on our end.
