### ISSUE TITLE
from azure.storage.blob import BlobPermissions gives import error in azure_storage.py

### ISSUE THREAD

**Issue by shubham-lks** [jschneier/django-storages#877]
hi,

I am using azure-storage-blob==12.3.0. while sublcassing AzureStorage, it gives the  following error:
cannot import name 'BlobPermissions'

I figured out that in new version this model "BlobPermission" has been renamed.

any solution to it?

Thanks,
Shubham

**Comment by patagoniapy** [comment]
Came to post the same issue.

**Comment by patagoniapy** [comment]
Do you happen to know what the model BlobPermission is now named?

**Comment by shubham-lks** [comment]
I guess BlobSASPermissions. its like one do only one thing. 
Could you find any workaround? I wasted one whole day to nothing.

> Do you happen to know what the model BlobPermission is now named?

**Comment by patagoniapy** [comment]
> I guess BlobSASPermissions. its like one do only one thing. 
> 
> Could you find any workaround? I wasted one whole day to nothing.
> 
> 
> 
> > Do you happen to know what the model BlobPermission is now named?
> 
> 
> 
> 

It appears `django-storages` doesn’t support `azure-sdk-12`. In order to make it work you’d need to instal an older version of `azure-sdk`

**Comment by jschneier** [comment]
There is an open PR. On the next version I will merge that in and drop current support.

**Comment by shubham-lks** [comment]
> There is an open PR. On the next version I will merge that in and drop current support.

Great Thanks alot man. It would be a great help :) when can we expect the next version?

Thanks,
shubham

**Comment by shubham-lks** [comment]
Hey! any update on this?

**Comment by cmberryau** [comment]
Looks like it got missed in the release

**Comment by anthonylauly** [comment]
Hey, any update about the next version, I am eagerly waiting for django storages to support azure-sdk-12

**Comment by surfgreendev** [comment]
Looking forward for an update as well!

**Comment by Vipin-Pootheri** [comment]
@jschneier 
Any update on this issue ?

**Comment by jschneier** [comment]
Fixed by #805
