### ISSUE TITLE
Scaling up with asynchronous writes/uploads?

### ISSUE THREAD

**Issue by nodje** [jschneier/django-storages#881]
I stumble upon your s3 implementation and it strikes me as a lot more refined that what we have produced!

That being said, I may be wrong but I haven't seen anything that would process the write/uploads to the cloud asynchronous.

We do massive amounts of files upload and doing it asynchronously using some queuing system seems to be the right thing to do.
And I think we could easily use the the `default_storage` class and have write operations executed through a queuing system.

But what about FileField usage? I'm not sure how I could make this asynchronous.
I mean what if I have many users all upload at the same time, each uploads is blocking so it'd better go in to a new Thread or be send to a job queue.

Am I totally wrong here? Wouldn't this benefit from having some async processing solution backed in? Thread management or be pluggable to a queuing system?

**Comment by jschneier** [comment]
The boto3 implementation is already threadsafe.

The purpose of this package is to implement Django's file API, nothing else.

Once you actually receive the file you must do something with it. You could, for example, store it on the filesystem for a short amount of time. I'm not quite sure what you're looking for but I don't think this is the right place to put it.
