### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Jihadik** [jschneier/django-storages#884]
What are the plans on releasing the latest changes?  
I saw you added CloudFront signing support, which is super useful.

How can we help to move this forward?

**Comment by jdufresne** [comment]
Hi @jschneier, thoughts on rolling a new release soon? It would be great to get some of the new features and to drop the many deprecation warnings emitted by the current django-storages version. There was [talk](https://github.com/jschneier/django-storages/pull/709#issuecomment-598554219) of doing a release back in March, so maybe now things have settled enough to proceed? Cheers and thanks.
