### ISSUE TITLE
Forbidden objects return as False for exists call in S3Boto

### ISSUE THREAD

**Issue by Chris7** [jschneier/django-storages#902]
The exists api makes no distinction between a file that does not exist and one that is inaccessible (https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py#L463). This leads the caller to not know they don't have the required permission to a bucket (and due to amazon's wonderful apis, you can have the ability to upload a file but not retrieve it), so it isn't always obvious this is the case.

One possibility: raise an error for forbidden by checking the client error code, or return `None` perhaps if it isn't possible to determine if the file exists or not.

**Comment by MatejMijoski** [comment]
Did you find a way to actually check if the file exists? This lib should already implement that as it has the necessary credentials.

**Comment by jschneier** [comment]
We check for 404 on the exists check now which is the best we can do.
