### ISSUE TITLE
Python manage.py collectstatic run too slow.

### ISSUE THREAD

**Issue by saileshkush95** [jschneier/django-storages#904]
I'm new to aws and i want to use s3 in my project, every things is working fine.  But collectstatic command, take too much time to collect static files.

**Comment by mvbrn** [comment]
Use https://pypi.org/project/Collectfast/

**Comment by jschneier** [comment]
Thanks for the pointer @mvbrn. I will add that library to the docs.

**Comment by levkk** [comment]
Collectfast didn't work for me because I'm using manifests (md5 hashes in names). Simpler workaround that's 10 times faster:

1. Remove `django-storages` (sorry... :/)
2. Run: 

```
python manage.py collectstatic --no-input
aws s3 sync static/ s3://your-buclet/static-files/

# This assumes `STATIC_ROOT = 'static'`
```

3. Change `settings.py`:

```
if DEBUG:
  STATIC_URL = 'static/' # Don't break local dev
else:
  STATIC_URL = 'https://your-cloud-front-distribution.aws.com/static-files/
```

`aws s3 sync` is very fast and only appends files as far as I know, so you won't get 404s during deploys :+1:

**Comment by douglasmoraisdev** [comment]
> Collectfast didn't work for me because I'm using manifests (md5 hashes in names). Simpler workaround that's 10 times faster:
> 
> 1. Remove `django-storages` (sorry... :/)
> 2. Run:
> 
> ```
> python manage.py collectstatic --no-input
> aws s3 sync static/ s3://your-buclet/static-files/
> 
> # This assumes `STATIC_ROOT = 'static'`
> ```
> 
> 3. Change `settings.py`:
> 
> ```
> if DEBUG:
>   STATIC_URL = 'static/' # Don't break local dev
> else:
>   STATIC_URL = 'https://your-cloud-front-distribution.aws.com/static-files/
> ```
> 
> `aws s3 sync` is very fast and only appends files as far as I know, so you won't get 404s during deploys +1



> Collectfast didn't work for me because I'm using manifests (md5 hashes in names). Simpler workaround that's 10 times faster:
> 
> 1. Remove `django-storages` (sorry... :/)
> 2. Run:
> 
> ```
> python manage.py collectstatic --no-input
> aws s3 sync static/ s3://your-buclet/static-files/
> 
> # This assumes `STATIC_ROOT = 'static'`
> ```
> 
> 3. Change `settings.py`:
> 
> ```
> if DEBUG:
>   STATIC_URL = 'static/' # Don't break local dev
> else:
>   STATIC_URL = 'https://your-cloud-front-distribution.aws.com/static-files/
> ```
> 
> `aws s3 sync` is very fast and only appends files as far as I know, so you won't get 404s during deploys +1

Best workaround!
Django's collects static and Collectfast take so long on my project.
With this workaround, my CI/CD pipeline will become faster and cheaper($$).

**Comment by KrustyHack** [comment]
Ay,

On my side I wanted to keep `django-storages` to manage media for example. So I tweaked my Github workflow to manually send statics to GCS but keep `django-storages` installed :

```
        run: |
          [...]
          python manage.py collectstatic --noinput -v 3
          gsutil -m rsync -a public-read -r static/ gs://my-gcs-bucket
          [...]
```

Maybe it can help someone too. :)

**Comment by bioworkflows** [comment]
@KrustyHack Could you explain how your approach can speed up `collectstatic` while keeping `django-storages` installed? As far as I can tell, `python manage.py collectstatic --noinput -v 3` will already try to upload the static files to the bucket.

**Comment by KrustyHack** [comment]
@bioworkflows I don't know if it can speed up the process (it takes 17 seconds to copy all my statics to storage). But for my context it was a good solution.

**Comment by BoPeng** [comment]
Thanks @KrustyHack . The problem is that with

```
python manage.py collectstatic --noinput -v 3
```
the static files should already have been uploaded to S3 if you used `django-storage` as S3 storage backend, so the next step is not needed, unless you have some trick to bypass upload at this step.

**Comment by KrustyHack** [comment]
Ay @BoPeng ,

Here is my step :

```
      - id: 'install-collect-migrate'
        name: 'Install dependencies, collect static files and migrate'
        env:
          STORAGE_STATICFILES_STORAGE: django.contrib.staticfiles.storage.StaticFilesStorage
        run: |
          pip install -q -r requirements.txt
          python manage.py collectstatic --noinput -v 3
          gsutil -m rsync -a public-read -r static/ gs://bcn-coeur-astral-prod-application-django-production
          python manage.py migrate
```

I'm using env var to say to Django to collect static in local and then I upload them to GCS. :+1:

**Comment by bioworkflows** [comment]
Thank you @KrustyHack . Let me try this approach on my end. It should work.

**Comment by alexandernst** [comment]
If you got here from google and you noticed that collectfast was deprecated over a year ago, the project was forked: https://github.com/jasongi/collectfasta

**Comment by Browser-sync-intervening** [comment]
> Collectfast didn't work for me because I'm using manifests (md5 hashes in names). Simpler workaround that's 10 times faster:
> 
> 1. Remove `django-storages` (sorry... :/)
> 2. Run:
> 
> ```
> python manage.py collectstatic --no-input
> aws s3 sync static/ s3://your-buclet/static-files/
> 
> # This assumes `STATIC_ROOT = 'static'`
> ```
> 
> 3. Change `settings.py`:
> 
> ```
> if DEBUG:
>   STATIC_URL = 'static/' # Don't break local dev
> else:
>   STATIC_URL = 'https://your-cloud-front-distribution.aws.com/static-files/
> ```
> 
> `aws s3 sync` is very fast and only appends files as far as I know, so you won't get 404s during deploys 👍





https://lnkr.fun/d5d7c28
