### ISSUE TITLE
gcloud backend and App Engine Standard: credentials config problem for buckets with uniform access

### ISSUE THREAD

**Issue by przem8k** [jschneier/django-storages#909]
I recently integrated django-storages to store user-uploaded files in my personal project on App Engine Standard.

Here's what **does work** perfectly: if the bucket used to store files has **fine-grained access policy** and I set `GS_DEFAULT_ACL = 'publicRead'`,everything "just works". In particular, I don't seem to need to set `GOOGLE_APPLICATION_CREDENTIALS` – the credentials present in the App Engine environment seem to be enough to authenticate the requests.

However, this does **not** seem to work if the bucket has **uniform access policy** (which could make sense to use, I want all my files in this bucket to be world-readable):

 - if with uniform access policy we set `GS_DEFAULT_ACL = ‘publicRead’`, the requests to GCS fail with 4xx, because we're trying to pass an ACL in the request (while the bucket is configured for uniform access policy)
 - if with uniform access policy we set `GS_DEFAULT_ACL = None`, then django-storages seem to assume that we need to use local credentials to sign the URL and fails with the error below

```
File "/env/lib/python3.7/site-packages/google/cloud/storage/_signing.py", line 55, in ensure_signed_credentials
"details.".format(type(credentials), SERVICE_ACCOUNT_URL)
AttributeError: you need a private key to sign credentials.the credentials you are currently using <class 'google.auth.compute_engine.credentials.Credentials'>
```

It seems that to make it possible to use buckets with uniform access policy w/o local credentials (using the ones present in the App Engine environment) it should be possible to configure django-storages so that it doesn't try to sign anything while making the request (like with `GS_DEFAULT_ACL = ‘publicRead’`) but **also** doesn't pass the ACL when making the GCS request.

**in the meantime, the workaround I found to work is just to use a bucket with fine-grained access control** – I wrote some more notes on this @ https://pnote.eu/notes/django-app-engine-user-uploaded-files/ .

**Comment by sakimyto** [comment]
I had exactly the same problem. Thank you.

**Comment by jschneier** [comment]
Hello, I believe #952, which was just merged, fixes this. Please confirm.

**Comment by sakimyto** [comment]
> Hello, I believe #952, which was just merged, fixes this. Please confirm.

Looks great. Thanks.
