### ISSUE TITLE
Doc needs fixing? AWS_S3_MAX_MEMORY_SIZE default is ALWAYS roll over

### ISSUE THREAD

**Issue by Palisand** [jschneier/django-storages#921]
The `s3Boto3` backend [uses `SpooledTemporaryFile` with a `max_size` set to `AWS_S3_MAX_MEMORY_SIZE`](https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py#L126-L129), which [defaults to `0`](https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py#L323). The docs state that this default means ["do not roll over"](https://github.com/jschneier/django-storages/blob/master/docs/backends/amazon-S3.rst#settings). However, a `max_size` of `0` means that the S3 content will [always be written to disk](https://docs.python.org/3/library/tempfile.html#tempfile.SpooledTemporaryFile), no? From the [`tempfile.SpooledTemporaryFile` source code](https://github.com/python/cpython/blob/e55de68be3e5b977a17d3c0ac9805b0feff8fedc/Lib/tempfile.py#L623-L667):

```python
    def _check(self, file):
        if self._rolled: return
        max_size = self._max_size
        if max_size and file.tell() > max_size:
            self.rollover()
```

**Comment by jschneier** [comment]
`max_size` is falsy so I think not?

**Comment by Palisand** [comment]
Ah yes, good point!
