### ISSUE TITLE
Default value for AWS_S3_MAX_MEMORY_SIZE is dangerous for large files

### ISSUE THREAD

**Issue by swiatekm** [jschneier/django-storages#936]
`AWS_S3_MAX_MEMORY_SIZE` sets the max size for a [SpooledTemporaryFile](https://docs.python.org/3/library/tempfile.html#tempfile.SpooledTemporaryFile), which the `S3Boto3StorageFile` uses for temporary storage. The default of 0 means "never rollover, keep contents only in memory", which causes issues with large files. In particular, even if we only want to read the first X bytes of the file, the current implementation (https://github.com/jschneier/django-storages/blob/b9bec8bf4b823c6c05613068749307754789a7b7/storages/backends/s3boto3.py#L133) will still download the whole thing and keep it in memory.

I think this is an unpleasantly surprising default - that users don't expect their files to be kept wholly in memory whenever their contents are accessed, irrespective of their size. The current default behaviour of "keep the buffer in memory always" should be an opt-in rather than an opt-out.

Let me know if I'm missing something here. Given that I've used storages for a while and haven't ever noticed this, I assume the typical use cases don't care. I don't think changing the default would really impact them in a negative way, though.

**Comment by jschneier** [comment]
Closed in #1359
