### ISSUE TITLE
How to add metadata including user information?(S3)

### ISSUE THREAD

**Issue by Nasubikun** [jschneier/django-storages#939]
I learned in order to add meta-data to S3, I have to override S3Boto3Storage.get_object_parameters.
Since I want to add user information to the metadata, I need to add "request" as an argument in get_object_parameters.
What is the best way to pass "request" to get_object_parameters?

**Comment by jschneier** [comment]
There is no guarantee that your storage will be used in a request context. It could be run as part of a management script, for example.

In general I wouldn't recommend storing this kind of data in the file metadata, but you can. You can override `get_object_parameters` and call out to any arbitrary thing you want.

**Comment by jschneier** [comment]
There is also `FileField`'s [upload_to](https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.FileField.upload_to).
