### ISSUE TITLE
How to make S3Boto3Storage to delete source file after uploaded to S3?

### ISSUE THREAD

**Issue by RecNes** [jschneier/django-storages#943]
I'm using a PDF generating service. Service is returning data you sent as generated PDF. API is reading incoming stream and writes into a temporary disk file and saves to Django model file field.

After saving model S3Boto3Storage uploads pdf to S3 bucket. But afterwards temporary PDF file remains. Is there any option for S3Boto3Storage to delete source file after uploaded the file into S3 bucket?

Can I use BytesIO instead of creating a temporary file? Is there any catch for S3Boto3Storage when using BytesIO?

**Comment by WhyNotHugo** [comment]
The storage does not create any temporary file -- the file you're seeing is a file you're creating, so you should deleted manually after persisting it.

You can also use Python `TemporaryFile` just fine, just make sure you specify a `name`.

**Comment by RecNes** [comment]
Thanks for the reply.
