### ISSUE TITLE
Inefficient implementation of `listdir` in the S3 backend

### ISSUE THREAD

**Issue by aaugustin** [jschneier/django-storages#95]
The [current implementation](https://github.com/jschneier/django-storages/blob/f2880b16b57a36b241a54932255e1a852c0e0ac7/storages/backends/s3boto.py#L441) gets the lists of all objects in the bucket.

Not only is this inefficient, but it also breaks on large buckets because of a bug in boto: https://github.com/boto/boto/issues/3006

You should steal the [more efficient implementation](https://github.com/etianen/django-s3-storage/blob/e8c1cb2d2b65c8c7047c7851c65af31f091312c9/django_s3_storage/storage.py#L261) from django-s3-storage.

**Comment by blitzd** [comment]
@jdufresne I'm unable to get your code to work, the problem being that the get_paginator call is happening on s3.ServiceResource object which has no attribute 'get_paginator'. So far as I can see the get_paginator method is only on s3.client objects. Any insight?

**Comment by jdufresne** [comment]
@blitzd I made some edits to call `get_paginator()` on the client object instead of the resource. Could you give it another test?

**Comment by blitzd** [comment]
@jdufresne Getting there, but I had to go with:

```python
        for page in pages:
            if page.get('CommonPrefixes'):
                for entry in page['CommonPrefixes']:
                    directories.append(posixpath.relpath(entry['Prefix'], path))
            if page.get('Contents'):
                for entry in page['Contents']:
                    files.append(posixpath.relpath(entry['Key'], path))
```

...as the keys may not exist in the response it seems.

**Comment by jdufresne** [comment]
Thanks for testing. I've updated the PR with your findings.
