### ISSUE TITLE
S3Boto3Storage as a staticfiles storage

### ISSUE THREAD

**Issue by WhyNotHugo** [jschneier/django-storages#951]
Using `storages.backends.s3boto3.S3Boto3Storage` as a staticfiles storage work fine, however, it breaks with `DEBUG=True`, since it generates URLs for the storage. One would need to run `collectstatic` after every file-save, and this takes a couple of minute (which ends up being the opposite of a live reload).

In the past, I've worked around this by using a different storage when `DEBUG=True`, but this just leads to other issues due to inconsistent settings.

I'm wondering if anyone has worked on a `S3Boto3StaticfilesStorage` storage, which uses `STATIC_URL` in development, and does the usual on production.

**Comment by jschneier** [comment]
To fix issues that have come up around `url()` I added a new staticfiles storage in #968. That could be extended with any new hooks or parameters that are needed.
