### ISSUE TITLE
Bug: using google bucket with uniform access, the file is uploaded, ImageField value is not set.

### ISSUE THREAD

**Issue by MeRuslan** [jschneier/django-storages#962]
Hello!
I've got a bucket with uniform access at my hands, I have set everything up accoring to the documentation
(set ``GS_DEFAULT_ACL`` to ``None`` and set ``GS_QUERYSTRING_AUTH`` to ``False``) 

Now django uploads the file, but fails to set the model field value.
I.e. the image gets uploaded, but ``ImageField`` value remains None.

**Comment by streinhard** [comment]
The flag `GS_QUERYSTRING_AUTH` hasn't been released to PyPI yet. Try installing django-storages from github directly:

`pip install -e 'git+https://github.com/jschneier/django-storages.git#egg=django-storages'`

And it should work. Cheers!

**Comment by jschneier** [comment]
This was released.

**Comment by streinhard** [comment]
Awesome, thanks for the release!

**Comment by MeRuslan** [comment]
Thanks!
