### ISSUE TITLE
How to do reverse operation from s3 key to django storage ?

### ISSUE THREAD

**Issue by Javedgouri** [jschneier/django-storages#966]

**Comment by jschneier** [comment]
Can you clarify what you're looking to do? If you've got a `FileField` you should just be able to examine the `name`. Otherwise it can be slightly more complicated, especially if you have overwriting protection enabled.

**Comment by Javedgouri** [comment]
@jschneier  i have directly upload file to s3 using presigned post url .
How i can link that file with django storage.
