### ISSUE TITLE
GCP: File Field saved files successfully but in database it's null

### ISSUE THREAD

**Issue by Iamsdt** [jschneier/django-storages#972]
I am working on a project, that hosted on GCP Compute Instance VM. But when upload and save any file into the File Field, it's saving that file in google cloud storage successfully. And it's showing
"The table <name> was added successfully. " But if I open any saved data again, the file picker field showing the save option as blank and there is no saved file. I am accessing this table using rest API, and this file picker field coming as null.

Here is my code -

**setting.py**
```
DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
GS_BUCKET_NAME = '<bucket-name>"'
```

here is the model code
```
class UserTable(models.Model):
        image_url = models.FileField(upload_to='user_pic//%Y/%m', blank=True)
```

Screenshot During data save
![image](https://user-images.githubusercontent.com/11135732/103157223-fc85c580-47da-11eb-9324-c1f2a40b8e6d.png)
When I open any saved object, it looks like this way
![image](https://user-images.githubusercontent.com/11135732/103157086-ea575780-47d9-11eb-80e7-9e55eca4d837.png)

Libraries and Versions
1. Django -> 3.1.2
2. djangorestframework -> 3.12.1
3. django-storages -> 1.11.1

**Comment by sww314** [comment]
@Iamsdt my guess is your file is actually uploading and saved in the database fine. The issue is actually on retrieval when your try to generate a signed url. This issue is written specific to Cloud Run, but I think problem is easy to run into with the wrong permissions.

https://github.com/jschneier/django-storages/issues/941
