### ISSUE TITLE
GS_EXPIRATION set to 30 days still new signed url is generated on each access of file object.

### ISSUE THREAD

**Issue by kathanshah** [jschneier/django-storages#979]
GS_EXPIRATION set to 30 days still new signed url is generated on each access of file object.
In Serializer, Django Admin both.

**Comment by sww314** [comment]
The signed url is not cached anywhere. The `GS_EXPIRATION` is expiration time for the link. 

If you want to cache your links you can do that, but you would do that by caching the view or part of the view.
Make sure you set the cache expire to a shorter time than the `GS_EXPIRATION`.

**Comment by kathanshah** [comment]
Got it, i can cache the values and check in serializer for its expiry and if it has still enough time will use the cached field value.
onetime storing will also need to do while check that and if its none or expired.

Thanks
