### ISSUE TITLE
Assign already uploaded object to a file field?

### ISSUE THREAD

**Issue by IdanYekutiel** [jschneier/django-storages#983]
Hi! I have been trying to figure this out but I haven't been able to.

Let's say I have ``test.png`` and I decide to upload it to aws manually to ``test/somefolder/test.png``. Is there any way that I can tell django that, instead of uploading the file directly, I want to assign it the file that is already on aws? I feel like this would be super useful.

**Comment by emanlodovice** [comment]
I believe you can just assign a string to the file field.

e.g.
```
record.my_fielfield = 'test/somefolder/test.png'
record.save()
```

**Comment by IdanYekutiel** [comment]
Oh, cool! I didn't know that. I'm gonna try it out tomorrow and tell you if it works.
