### ISSUE TITLE
S3Boto3Storage have unimplemented abstract methods

### ISSUE THREAD

**Issue by jaroslawporada** [jschneier/django-storages#985]
Pylint raise following errors:
W0223: Method 'get_accessed_time' is abstract in class 'Storage' but is not overridden (abstract-method)
W0223: Method 'get_created_time' is abstract in class 'Storage' but is not overridden (abstract-method)

**Comment by jschneier** [comment]
Not all of these methods are meaningful in a remote storage context. I think `get_created_time` could be but I don't think anyone cares?

From the boto3 docs what we are calling `get_modified_time` should probably be called `get_created_time` actually.
