### ISSUE TITLE
Setup.py should list extas_require for each storage backend

### ISSUE THREAD

**Issue by mlissner** [jschneier/django-storages#986]
I'm doing a bit of dependency cleanup, and I noticed that we have boto3 listed on our requirements.txt list. That surprised me a bit because our code doesn't actually call boto3 at any point. Instead, it's a sub-dependency of django-storage when using the s3 backend. 

In theory, it shouldn't be listed in our requirements file because if django-storage wants to upgrade the version of boto3 that's required, it can't do so smoothly. Instead, all users of django-storage lock boto3 at fairly random versions (if you're lucky, they upgrade them).

I think there are two possible fixes for this:

1. Require all the sub-dependencies when installing django-storage. 

    That'd bring a raft of dependencies, but would mean a simple `pip install django-storages` would be all folks need. I don't like this approach, but it's possible.

1. Use [optional dependencies](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html?highlight=extras#optional-dependencies) so that folks can install whatever backend they plan to use.

    This would mean that folks install with: `pip install django-storages[boto3]` or similar and that they'd only get the deps they need. It'd also allow django-storages to set the required deps for each backend to make sure things stayed compatible.

I'm really bad at packaging, so I'm not sure I could take this on, but it seems like something that should be done correctly for a package of this popularity, if it's possible. (Apologies if I'm missing a subtlety here, and thank you, thank you, for this great package.)

**Comment by jschneier** [comment]
This was implemented at some point.
