### ISSUE TITLE
Documentation/feature update for Dropbox api v2

### ISSUE THREAD

**Issue by compmonks** [jschneier/django-storages#993]
The Dropbox API has changed and now supports refresh tokens : https://developers.dropbox.com/oauth-guide
Currently the oAUTH token to be used for Django-storages is only provided as ‘short-lived’ for 4 hours by Dropbox and a new one can be used by sending a refresh token. Documentation or feature update necessary?

**Comment by jschneier** [comment]
Fixed by #1159.
